// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/basic/basic.proto

package basic

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for BasicSrv service

type BasicSrvService interface {
}

type basicSrvService struct {
	c    client.Client
	name string
}

func NewBasicSrvService(name string, c client.Client) BasicSrvService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "basic"
	}
	return &basicSrvService{
		c:    c,
		name: name,
	}
}

// Server API for BasicSrv service

type BasicSrvHandler interface {
}

func RegisterBasicSrvHandler(s server.Server, hdlr BasicSrvHandler, opts ...server.HandlerOption) error {
	type basicSrv interface {
	}
	type BasicSrv struct {
		basicSrv
	}
	h := &basicSrvHandler{hdlr}
	return s.Handle(s.NewHandler(&BasicSrv{h}, opts...))
}

type basicSrvHandler struct {
	BasicSrvHandler
}
