{
    "dbConfig":{ #数据库配置
        "driverName":"mysql",
        "server":"127.0.0.1",
        "port":3306,
        "user":"root",
        "password":"123456",
        "database":"test",
        "dateSourceName":"",
        "isDebug":true
    },
    "filePath":"static/upload",#前缀加./或不加表示在该程序下，只加/表示在磁盘文件下
    "webp":{ ##需要和docker一致
        "HOST": "127.0.0.1",
        "PORT": 3333,
        "QUALITY": 80,
        "IMG_PATH": "/path/to/pics",
        "EXHAUST_PATH": "",
        "ALLOWED_TYPES": ["jpg","png","jpeg","bmp"]
    },
    "redisConfig":{
        "network":"",
        "addr":"127.0.0.1:6379",
        "password":"",
        "db":1
    },
    "txOcrApi":{
        "region":"ap-beijing",
        "endpoint":"ocr.tencentcloudapi.com",
        "secretId":"AKIDnQsERTVtSuTtAenY2LTbZN4aeS5YuMYX",
        "secretKey":"0d7NuAGF4k4veDmCSXSfnlYQA91Tr6BN"
    },
    "jwt":{
        "secret":"weixiao_keji_007",
        "TimeOut":1800
    },
    "yzm":{
        "width":6,
        "TimeOut":60
    },
    "emailConfig":{
        "emailType":0,
        "userName":"943885179@qq.com",
        "password":"ppiqtqrtrzdpbcjf",
        "bcc":[

        ],
        "cc":[

        ],
        "to":[

        ],
        "subject":"weixiaoqaq",
        "text":"",
        "html":""
    },
    "services":{
        "userSrv":{
            "etcd":"",
            "name":"com.weixiao.userSrv",
            "version":"latest",
            "ip":"",
            "port":0
        },
        "userCli":{
            "etcd":"",
            "name":"com.weixiao.userCli",
            "version":"latest",
            "ip":"",
            "port":8701
        },
        "sendSrv":{
            "etcd":"",
            "name":"com.weixiao.sendSrv",
            "version":"latest",
            "ip":"",
            "port":8702
        },
        "sendCli":{
            "etcd":"",
            "name":"com.weixiao.sendCli",
            "version":"latest",
            "ip":"",
            "port":8703
        },
        "fileSrv":{
            "etcd":"",
            "name":"com.weixiao.fileSrv",
            "version":"latest",
            "ip":"",
            "port":8704
        },
        "fileCli":{
            "etcd":"",
            "name":"com.weixiao.fileCli",
            "version":"latest",
            "ip":"",
            "port":8705
        },
        "midCli":{
            "etcd":"",
            "name":"com.weixiao.midCli",#中间服务调用micro接口
            "version":"latest",
        }
    }
}