{
    "dbConfig":{ #数据库配置
        "dbType":1,
        "driverName":"dbType=>mysql:0,postgres:1,sqlserver:2",
        "server":"127.0.0.1",
        "port":5432,
        "user":"postgres",
        "password":"123abc",
        "database":"test",
        "dateSourceName":"",
        "isDebug":true
    },
    "filePath":"static/upload",#前缀加./或不加表示在该程序下，只加/表示在磁盘文件下
    "webp":{ ##需要和docker一致
        "HOST": "127.0.0.1",
        "PORT": 3333,
        "QUALITY": 80,
        "IMG_PATH": "/path/to/pics",
        "EXHAUST_PATH": "",
        "ALLOWED_TYPES": ["jpg","png","jpeg","bmp"]
    },
    "redisConfig":{
        "network":"",
        "addr":"127.0.0.1:6379",
        "password":"",
        "db":1
    },
    "txOcrApi":{
        "region":"ap-beijing",
        "endpoint":"ocr.tencentcloudapi.com",
        "secretId":"AKIDnQsERTVtSuTtAenY2LTbZN4aeS5YuMYX",
        "secretKey":"0d7NuAGF4k4veDmCSXSfnlYQA91Tr6BN"
    },
    "jwt":{
        "secret":"weixiao_keji_007",
        "TimeOut":1800
    },
    "yzm":{
        "width":6,
        "TimeOut":60
    },
    "emailConfig":{
        "emailType":0,
        "userName":"943885179@qq.com",
        "password":"ppiqtqrtrzdpbcjf",
        "bcc":[

        ],
        "cc":[

        ],
        "to":[

        ],
        "subject":"weixiaoqaq",
        "text":"",
        "html":""
    },
    "services":{
        "basicSrv":{
            "etcd":"127.0.0.1:2379",
            "name":"com.weixiao.api.basic",
            "version":"latest",
            "ip":"",
            "port":0
        },
        "basicCli":{
            "etcd":"",
            "nac_os":"",
            "name":"com.weixiao.web.basic",
            "version":"latest",
            "ip":"",
            ## "port":8701
        },
        "sendSrv":{
           "etcd":"127.0.0.1:2379",
            ##"nacos":"console.nacos.io:80",
            #"nacos":"127.0.0.1:8848",
            # "consul":"127.0.0.1:8500" # micro_registry=consul;micro_registry_address=127.0.0.1:8500
            "name":"go.micro.api.weixiao.send",
            "version":"latest",
            "ip":"",
            "port":8702
        },
        "sendCli":{
            "etcd":"",
            "name":"com.weixiao.web.send",
            "version":"latest",
            "ip":"",
            "port":8703
        },
        "fileSrv":{
            "etcd":"",
            "name":"com.weixiao.api.file",
            "version":"latest",
            "ip":"",
            ## "port":8704
        },
        "fileCli":{
            "etcd":"",
            "name":"com.weixiao.web.file",
            "version":"latest",
            "ip":"",
            ## "port":8705
        },
        "productSrv":{
            "etcd":"",
            "name":"com.weixiao.api.product",
            "version":"latest",
            "ip":"",
            "port":8706
        },
        "productCli":{
            "etcd":"",
            "name":"com.weixiao.web.product",
            "version":"latest",
            "ip":"",
            "port":8707
        },
        "midCli":{
            "etcd":"",
            "name":"com.weixiao.web.mid",#中间服务调用micro接口
            "version":"latest",
        }
    },
    "nac_os_server_configs":[
        {
            "scheme":"",
            "context_path":"/nacos",
            "ip_addr":"127.0.0.1",
            "port":8848
        }
    ]
}