// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sysuser.proto

package sysuser

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginType int32

const (
	LoginType_NAME  LoginType = 0
	LoginType_PHONE LoginType = 1
	LoginType_EMAIL LoginType = 2
)

var LoginType_name = map[int32]string{
	0: "NAME",
	1: "PHONE",
	2: "EMAIL",
}

var LoginType_value = map[string]int32{
	"NAME":  0,
	"PHONE": 1,
	"EMAIL": 2,
}

func (x LoginType) String() string {
	return proto.EnumName(LoginType_name, int32(x))
}

func (LoginType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0d42e5eade424557, []int{0}
}

type UserType int32

const (
	UserType_ADMIN    UserType = 0
	UserType_PLATFORM UserType = 1
	UserType_SHOP     UserType = 2
	UserType_CUSTOMER UserType = 3
)

var UserType_name = map[int32]string{
	0: "ADMIN",
	1: "PLATFORM",
	2: "SHOP",
	3: "CUSTOMER",
}

var UserType_value = map[string]int32{
	"ADMIN":    0,
	"PLATFORM": 1,
	"SHOP":     2,
	"CUSTOMER": 3,
}

func (x UserType) String() string {
	return proto.EnumName(UserType_name, int32(x))
}

func (UserType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0d42e5eade424557, []int{1}
}

//用户登录
type LoginReq struct {
	LoginType              LoginType `protobuf:"varint,1,opt,name=login_type,json=loginType,proto3,enum=sysuser.LoginType" json:"login_type,omitempty"`
	UserNameOrPhoneOrEmail string    `protobuf:"bytes,2,opt,name=user_name_or_phone_or_email,json=userNameOrPhoneOrEmail,proto3" json:"user_name_or_phone_or_email,omitempty"`
	UserPasswordOrCode     string    `protobuf:"bytes,3,opt,name=user_password_or_code,json=userPasswordOrCode,proto3" json:"user_password_or_code,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}  `json:"-"`
	XXX_unrecognized       []byte    `json:"-"`
	XXX_sizecache          int32     `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d42e5eade424557, []int{0}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetLoginType() LoginType {
	if m != nil {
		return m.LoginType
	}
	return LoginType_NAME
}

func (m *LoginReq) GetUserNameOrPhoneOrEmail() string {
	if m != nil {
		return m.UserNameOrPhoneOrEmail
	}
	return ""
}

func (m *LoginReq) GetUserPasswordOrCode() string {
	if m != nil {
		return m.UserPasswordOrCode
	}
	return ""
}

//用户登录返回
type LoginResp struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserImg              string   `protobuf:"bytes,3,opt,name=user_img,json=userImg,proto3" json:"user_img,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d42e5eade424557, []int{1}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResp) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoginResp) GetUserImg() string {
	if m != nil {
		return m.UserImg
	}
	return ""
}

//用户注册请求
type RegistryReq struct {
	UserType             UserType `protobuf:"varint,6,opt,name=user_type,json=userType,proto3,enum=sysuser.UserType" json:"user_type,omitempty"`
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserPassword         string   `protobuf:"bytes,2,opt,name=user_password,json=userPassword,proto3" json:"user_password,omitempty"`
	UserPasswordAgain    string   `protobuf:"bytes,3,opt,name=user_password_again,json=userPasswordAgain,proto3" json:"user_password_again,omitempty"`
	UserPhone            string   `protobuf:"bytes,4,opt,name=user_phone,json=userPhone,proto3" json:"user_phone,omitempty"`
	UserPhoneCode        string   `protobuf:"bytes,5,opt,name=user_phone_code,json=userPhoneCode,proto3" json:"user_phone_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistryReq) Reset()         { *m = RegistryReq{} }
func (m *RegistryReq) String() string { return proto.CompactTextString(m) }
func (*RegistryReq) ProtoMessage()    {}
func (*RegistryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d42e5eade424557, []int{2}
}

func (m *RegistryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistryReq.Unmarshal(m, b)
}
func (m *RegistryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistryReq.Marshal(b, m, deterministic)
}
func (m *RegistryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistryReq.Merge(m, src)
}
func (m *RegistryReq) XXX_Size() int {
	return xxx_messageInfo_RegistryReq.Size(m)
}
func (m *RegistryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistryReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegistryReq proto.InternalMessageInfo

func (m *RegistryReq) GetUserType() UserType {
	if m != nil {
		return m.UserType
	}
	return UserType_ADMIN
}

func (m *RegistryReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RegistryReq) GetUserPassword() string {
	if m != nil {
		return m.UserPassword
	}
	return ""
}

func (m *RegistryReq) GetUserPasswordAgain() string {
	if m != nil {
		return m.UserPasswordAgain
	}
	return ""
}

func (m *RegistryReq) GetUserPhone() string {
	if m != nil {
		return m.UserPhone
	}
	return ""
}

func (m *RegistryReq) GetUserPhoneCode() string {
	if m != nil {
		return m.UserPhoneCode
	}
	return ""
}

//修改密码
type ChangePasswordReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserPassword         string   `protobuf:"bytes,2,opt,name=user_password,json=userPassword,proto3" json:"user_password,omitempty"`
	UserPasswordAgain    string   `protobuf:"bytes,3,opt,name=user_password_again,json=userPasswordAgain,proto3" json:"user_password_again,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordReq) Reset()         { *m = ChangePasswordReq{} }
func (m *ChangePasswordReq) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordReq) ProtoMessage()    {}
func (*ChangePasswordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d42e5eade424557, []int{3}
}

func (m *ChangePasswordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordReq.Unmarshal(m, b)
}
func (m *ChangePasswordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordReq.Marshal(b, m, deterministic)
}
func (m *ChangePasswordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordReq.Merge(m, src)
}
func (m *ChangePasswordReq) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordReq.Size(m)
}
func (m *ChangePasswordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordReq proto.InternalMessageInfo

func (m *ChangePasswordReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ChangePasswordReq) GetUserPassword() string {
	if m != nil {
		return m.UserPassword
	}
	return ""
}

func (m *ChangePasswordReq) GetUserPasswordAgain() string {
	if m != nil {
		return m.UserPasswordAgain
	}
	return ""
}

type UserInfoListReq struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Row                  int32    `protobuf:"varint,2,opt,name=row,proto3" json:"row,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserPhone            string   `protobuf:"bytes,4,opt,name=user_phone,json=userPhone,proto3" json:"user_phone,omitempty"`
	UserEmail            string   `protobuf:"bytes,5,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoListReq) Reset()         { *m = UserInfoListReq{} }
func (m *UserInfoListReq) String() string { return proto.CompactTextString(m) }
func (*UserInfoListReq) ProtoMessage()    {}
func (*UserInfoListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d42e5eade424557, []int{4}
}

func (m *UserInfoListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoListReq.Unmarshal(m, b)
}
func (m *UserInfoListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoListReq.Marshal(b, m, deterministic)
}
func (m *UserInfoListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoListReq.Merge(m, src)
}
func (m *UserInfoListReq) XXX_Size() int {
	return xxx_messageInfo_UserInfoListReq.Size(m)
}
func (m *UserInfoListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoListReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoListReq proto.InternalMessageInfo

func (m *UserInfoListReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *UserInfoListReq) GetRow() int32 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *UserInfoListReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserInfoListReq) GetUserPhone() string {
	if m != nil {
		return m.UserPhone
	}
	return ""
}

func (m *UserInfoListReq) GetUserEmail() string {
	if m != nil {
		return m.UserEmail
	}
	return ""
}

type UserInfoListResp struct {
	Total                int64    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data                 *any.Any `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoListResp) Reset()         { *m = UserInfoListResp{} }
func (m *UserInfoListResp) String() string { return proto.CompactTextString(m) }
func (*UserInfoListResp) ProtoMessage()    {}
func (*UserInfoListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d42e5eade424557, []int{5}
}

func (m *UserInfoListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoListResp.Unmarshal(m, b)
}
func (m *UserInfoListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoListResp.Marshal(b, m, deterministic)
}
func (m *UserInfoListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoListResp.Merge(m, src)
}
func (m *UserInfoListResp) XXX_Size() int {
	return xxx_messageInfo_UserInfoListResp.Size(m)
}
func (m *UserInfoListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoListResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoListResp proto.InternalMessageInfo

func (m *UserInfoListResp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *UserInfoListResp) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

//角色请求
type RoleReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoleName             string   `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	RoleExplain          string   `protobuf:"bytes,3,opt,name=role_explain,json=roleExplain,proto3" json:"role_explain,omitempty"`
	MenId                []int64  `protobuf:"varint,4,rep,packed,name=men_id,json=menId,proto3" json:"men_id,omitempty"`
	SrvId                []int64  `protobuf:"varint,5,rep,packed,name=srv_id,json=srvId,proto3" json:"srv_id,omitempty"`
	ApiId                []int64  `protobuf:"varint,6,rep,packed,name=api_id,json=apiId,proto3" json:"api_id,omitempty"`
	PId                  int64    `protobuf:"varint,7,opt,name=p_id,json=pId,proto3" json:"p_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleReq) Reset()         { *m = RoleReq{} }
func (m *RoleReq) String() string { return proto.CompactTextString(m) }
func (*RoleReq) ProtoMessage()    {}
func (*RoleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d42e5eade424557, []int{6}
}

func (m *RoleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleReq.Unmarshal(m, b)
}
func (m *RoleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleReq.Marshal(b, m, deterministic)
}
func (m *RoleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleReq.Merge(m, src)
}
func (m *RoleReq) XXX_Size() int {
	return xxx_messageInfo_RoleReq.Size(m)
}
func (m *RoleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoleReq proto.InternalMessageInfo

func (m *RoleReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RoleReq) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *RoleReq) GetRoleExplain() string {
	if m != nil {
		return m.RoleExplain
	}
	return ""
}

func (m *RoleReq) GetMenId() []int64 {
	if m != nil {
		return m.MenId
	}
	return nil
}

func (m *RoleReq) GetSrvId() []int64 {
	if m != nil {
		return m.SrvId
	}
	return nil
}

func (m *RoleReq) GetApiId() []int64 {
	if m != nil {
		return m.ApiId
	}
	return nil
}

func (m *RoleReq) GetPId() int64 {
	if m != nil {
		return m.PId
	}
	return 0
}

//用户组请求
type UserGroupReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupName            string   `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	GroupExplain         string   `protobuf:"bytes,3,opt,name=group_explain,json=groupExplain,proto3" json:"group_explain,omitempty"`
	RoleId               []int64  `protobuf:"varint,4,rep,packed,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGroupReq) Reset()         { *m = UserGroupReq{} }
func (m *UserGroupReq) String() string { return proto.CompactTextString(m) }
func (*UserGroupReq) ProtoMessage()    {}
func (*UserGroupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d42e5eade424557, []int{7}
}

func (m *UserGroupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGroupReq.Unmarshal(m, b)
}
func (m *UserGroupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGroupReq.Marshal(b, m, deterministic)
}
func (m *UserGroupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGroupReq.Merge(m, src)
}
func (m *UserGroupReq) XXX_Size() int {
	return xxx_messageInfo_UserGroupReq.Size(m)
}
func (m *UserGroupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGroupReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserGroupReq proto.InternalMessageInfo

func (m *UserGroupReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserGroupReq) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *UserGroupReq) GetGroupExplain() string {
	if m != nil {
		return m.GroupExplain
	}
	return ""
}

func (m *UserGroupReq) GetRoleId() []int64 {
	if m != nil {
		return m.RoleId
	}
	return nil
}

type MenuReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	I18N                 string   `protobuf:"bytes,4,opt,name=i18n,proto3" json:"i18n,omitempty"`
	Link                 string   `protobuf:"bytes,5,opt,name=link,proto3" json:"link,omitempty"`
	ExternalLink         string   `protobuf:"bytes,6,opt,name=external_link,json=externalLink,proto3" json:"external_link,omitempty"`
	Target               string   `protobuf:"bytes,7,opt,name=target,proto3" json:"target,omitempty"`
	Sort                 string   `protobuf:"bytes,8,opt,name=sort,proto3" json:"sort,omitempty"`
	Badge                int32    `protobuf:"varint,9,opt,name=badge,proto3" json:"badge,omitempty"`
	BadgeDoc             string   `protobuf:"bytes,10,opt,name=badge_doc,json=badgeDoc,proto3" json:"badge_doc,omitempty"`
	BadgeStatus          string   `protobuf:"bytes,11,opt,name=badge_status,json=badgeStatus,proto3" json:"badge_status,omitempty"`
	Acl                  string   `protobuf:"bytes,12,opt,name=acl,proto3" json:"acl,omitempty"`
	Hide                 bool     `protobuf:"varint,13,opt,name=hide,proto3" json:"hide,omitempty"`
	Disabled             bool     `protobuf:"varint,14,opt,name=disabled,proto3" json:"disabled,omitempty"`
	HideInBreadcrumb     bool     `protobuf:"varint,15,opt,name=hideInBreadcrumb,proto3" json:"hideInBreadcrumb,omitempty"`
	Shortcut             bool     `protobuf:"varint,16,opt,name=shortcut,proto3" json:"shortcut,omitempty"`
	ShortcutRoot         bool     `protobuf:"varint,17,opt,name=shortcut_root,json=shortcutRoot,proto3" json:"shortcut_root,omitempty"`
	Reuse                bool     `protobuf:"varint,18,opt,name=reuse,proto3" json:"reuse,omitempty"`
	Icon                 string   `protobuf:"bytes,19,opt,name=icon,proto3" json:"icon,omitempty"`
	Pid                  int64    `protobuf:"varint,20,opt,name=pid,proto3" json:"pid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MenuReq) Reset()         { *m = MenuReq{} }
func (m *MenuReq) String() string { return proto.CompactTextString(m) }
func (*MenuReq) ProtoMessage()    {}
func (*MenuReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d42e5eade424557, []int{8}
}

func (m *MenuReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MenuReq.Unmarshal(m, b)
}
func (m *MenuReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MenuReq.Marshal(b, m, deterministic)
}
func (m *MenuReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MenuReq.Merge(m, src)
}
func (m *MenuReq) XXX_Size() int {
	return xxx_messageInfo_MenuReq.Size(m)
}
func (m *MenuReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MenuReq.DiscardUnknown(m)
}

var xxx_messageInfo_MenuReq proto.InternalMessageInfo

func (m *MenuReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MenuReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MenuReq) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *MenuReq) GetI18N() string {
	if m != nil {
		return m.I18N
	}
	return ""
}

func (m *MenuReq) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *MenuReq) GetExternalLink() string {
	if m != nil {
		return m.ExternalLink
	}
	return ""
}

func (m *MenuReq) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *MenuReq) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *MenuReq) GetBadge() int32 {
	if m != nil {
		return m.Badge
	}
	return 0
}

func (m *MenuReq) GetBadgeDoc() string {
	if m != nil {
		return m.BadgeDoc
	}
	return ""
}

func (m *MenuReq) GetBadgeStatus() string {
	if m != nil {
		return m.BadgeStatus
	}
	return ""
}

func (m *MenuReq) GetAcl() string {
	if m != nil {
		return m.Acl
	}
	return ""
}

func (m *MenuReq) GetHide() bool {
	if m != nil {
		return m.Hide
	}
	return false
}

func (m *MenuReq) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *MenuReq) GetHideInBreadcrumb() bool {
	if m != nil {
		return m.HideInBreadcrumb
	}
	return false
}

func (m *MenuReq) GetShortcut() bool {
	if m != nil {
		return m.Shortcut
	}
	return false
}

func (m *MenuReq) GetShortcutRoot() bool {
	if m != nil {
		return m.ShortcutRoot
	}
	return false
}

func (m *MenuReq) GetReuse() bool {
	if m != nil {
		return m.Reuse
	}
	return false
}

func (m *MenuReq) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *MenuReq) GetPid() int64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

type ApiReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Service              string   `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	ApiExplain           string   `protobuf:"bytes,4,opt,name=api_explain,json=apiExplain,proto3" json:"api_explain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiReq) Reset()         { *m = ApiReq{} }
func (m *ApiReq) String() string { return proto.CompactTextString(m) }
func (*ApiReq) ProtoMessage()    {}
func (*ApiReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d42e5eade424557, []int{9}
}

func (m *ApiReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiReq.Unmarshal(m, b)
}
func (m *ApiReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiReq.Marshal(b, m, deterministic)
}
func (m *ApiReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiReq.Merge(m, src)
}
func (m *ApiReq) XXX_Size() int {
	return xxx_messageInfo_ApiReq.Size(m)
}
func (m *ApiReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiReq.DiscardUnknown(m)
}

var xxx_messageInfo_ApiReq proto.InternalMessageInfo

func (m *ApiReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ApiReq) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ApiReq) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *ApiReq) GetApiExplain() string {
	if m != nil {
		return m.ApiExplain
	}
	return ""
}

type SrvReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Service              string   `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	SrvExplain           string   `protobuf:"bytes,4,opt,name=srv_explain,json=srvExplain,proto3" json:"srv_explain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SrvReq) Reset()         { *m = SrvReq{} }
func (m *SrvReq) String() string { return proto.CompactTextString(m) }
func (*SrvReq) ProtoMessage()    {}
func (*SrvReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d42e5eade424557, []int{10}
}

func (m *SrvReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SrvReq.Unmarshal(m, b)
}
func (m *SrvReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SrvReq.Marshal(b, m, deterministic)
}
func (m *SrvReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SrvReq.Merge(m, src)
}
func (m *SrvReq) XXX_Size() int {
	return xxx_messageInfo_SrvReq.Size(m)
}
func (m *SrvReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SrvReq.DiscardUnknown(m)
}

var xxx_messageInfo_SrvReq proto.InternalMessageInfo

func (m *SrvReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SrvReq) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *SrvReq) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *SrvReq) GetSrvExplain() string {
	if m != nil {
		return m.SrvExplain
	}
	return ""
}

type TreeReq struct {
	Id                   int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 string     `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Text                 string     `protobuf:"bytes,3,opt,name=Text,proto3" json:"Text,omitempty"`
	Sort                 int32      `protobuf:"varint,4,opt,name=Sort,proto3" json:"Sort,omitempty"`
	PId                  int64      `protobuf:"varint,5,opt,name=p_id,json=pId,proto3" json:"p_id,omitempty"`
	Children             []*TreeReq `protobuf:"bytes,6,rep,name=Children,proto3" json:"Children,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TreeReq) Reset()         { *m = TreeReq{} }
func (m *TreeReq) String() string { return proto.CompactTextString(m) }
func (*TreeReq) ProtoMessage()    {}
func (*TreeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d42e5eade424557, []int{11}
}

func (m *TreeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TreeReq.Unmarshal(m, b)
}
func (m *TreeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TreeReq.Marshal(b, m, deterministic)
}
func (m *TreeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TreeReq.Merge(m, src)
}
func (m *TreeReq) XXX_Size() int {
	return xxx_messageInfo_TreeReq.Size(m)
}
func (m *TreeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TreeReq.DiscardUnknown(m)
}

var xxx_messageInfo_TreeReq proto.InternalMessageInfo

func (m *TreeReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TreeReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *TreeReq) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *TreeReq) GetSort() int32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *TreeReq) GetPId() int64 {
	if m != nil {
		return m.PId
	}
	return 0
}

func (m *TreeReq) GetChildren() []*TreeReq {
	if m != nil {
		return m.Children
	}
	return nil
}

type DelReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelReq) Reset()         { *m = DelReq{} }
func (m *DelReq) String() string { return proto.CompactTextString(m) }
func (*DelReq) ProtoMessage()    {}
func (*DelReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d42e5eade424557, []int{12}
}

func (m *DelReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelReq.Unmarshal(m, b)
}
func (m *DelReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelReq.Marshal(b, m, deterministic)
}
func (m *DelReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelReq.Merge(m, src)
}
func (m *DelReq) XXX_Size() int {
	return xxx_messageInfo_DelReq.Size(m)
}
func (m *DelReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelReq proto.InternalMessageInfo

func (m *DelReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type EditResp struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditResp) Reset()         { *m = EditResp{} }
func (m *EditResp) String() string { return proto.CompactTextString(m) }
func (*EditResp) ProtoMessage()    {}
func (*EditResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d42e5eade424557, []int{13}
}

func (m *EditResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditResp.Unmarshal(m, b)
}
func (m *EditResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditResp.Marshal(b, m, deterministic)
}
func (m *EditResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditResp.Merge(m, src)
}
func (m *EditResp) XXX_Size() int {
	return xxx_messageInfo_EditResp.Size(m)
}
func (m *EditResp) XXX_DiscardUnknown() {
	xxx_messageInfo_EditResp.DiscardUnknown(m)
}

var xxx_messageInfo_EditResp proto.InternalMessageInfo

func (m *EditResp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterEnum("sysuser.LoginType", LoginType_name, LoginType_value)
	proto.RegisterEnum("sysuser.UserType", UserType_name, UserType_value)
	proto.RegisterType((*LoginReq)(nil), "sysuser.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "sysuser.LoginResp")
	proto.RegisterType((*RegistryReq)(nil), "sysuser.RegistryReq")
	proto.RegisterType((*ChangePasswordReq)(nil), "sysuser.ChangePasswordReq")
	proto.RegisterType((*UserInfoListReq)(nil), "sysuser.UserInfoListReq")
	proto.RegisterType((*UserInfoListResp)(nil), "sysuser.UserInfoListResp")
	proto.RegisterType((*RoleReq)(nil), "sysuser.RoleReq")
	proto.RegisterType((*UserGroupReq)(nil), "sysuser.UserGroupReq")
	proto.RegisterType((*MenuReq)(nil), "sysuser.MenuReq")
	proto.RegisterType((*ApiReq)(nil), "sysuser.ApiReq")
	proto.RegisterType((*SrvReq)(nil), "sysuser.SrvReq")
	proto.RegisterType((*TreeReq)(nil), "sysuser.TreeReq")
	proto.RegisterType((*DelReq)(nil), "sysuser.DelReq")
	proto.RegisterType((*EditResp)(nil), "sysuser.EditResp")
}

func init() { proto.RegisterFile("sysuser.proto", fileDescriptor_0d42e5eade424557) }

var fileDescriptor_0d42e5eade424557 = []byte{
	// 1241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcf, 0x6e, 0xdb, 0x46,
	0x13, 0x37, 0xad, 0xff, 0x63, 0xd9, 0xa6, 0x37, 0x4e, 0x3e, 0x46, 0x41, 0xf0, 0xb9, 0x2c, 0x50,
	0x18, 0x69, 0x21, 0xd7, 0x6e, 0x0b, 0x14, 0xc8, 0x49, 0xb1, 0xd5, 0x46, 0x80, 0x65, 0x19, 0x94,
	0x72, 0x68, 0x2f, 0x02, 0x2d, 0x6e, 0x28, 0xc2, 0x14, 0x97, 0x59, 0x52, 0x8a, 0x85, 0xbe, 0x45,
	0x0f, 0x7d, 0x8b, 0x1e, 0xfa, 0x40, 0x7d, 0x8d, 0x02, 0xbd, 0x15, 0x33, 0xbb, 0xa4, 0x44, 0x47,
	0x4d, 0x7d, 0x68, 0x6f, 0x33, 0xbf, 0x99, 0xd9, 0x99, 0xf9, 0xcd, 0x70, 0x97, 0xb0, 0x9b, 0x2c,
	0x93, 0x79, 0xc2, 0x65, 0x3b, 0x96, 0x22, 0x15, 0xac, 0xa6, 0xd5, 0xd6, 0x53, 0x5f, 0x08, 0x3f,
	0xe4, 0x27, 0x04, 0xdf, 0xcc, 0xdf, 0x9e, 0xb8, 0xd1, 0x52, 0xf9, 0xd8, 0xbf, 0x1a, 0x50, 0xbf,
	0x14, 0x7e, 0x10, 0x39, 0xfc, 0x1d, 0x3b, 0x05, 0x08, 0x51, 0x1e, 0xa7, 0xcb, 0x98, 0x5b, 0xc6,
	0x91, 0x71, 0xbc, 0x77, 0xc6, 0xda, 0xd9, 0xa1, 0xe4, 0x36, 0x5a, 0xc6, 0xdc, 0x69, 0x84, 0x99,
	0xc8, 0x5e, 0xc2, 0x33, 0x34, 0x8e, 0x23, 0x77, 0xc6, 0xc7, 0x42, 0x8e, 0xe3, 0xa9, 0x88, 0x48,
	0xe0, 0x33, 0x37, 0x08, 0xad, 0xed, 0x23, 0xe3, 0xb8, 0xe1, 0x3c, 0x41, 0x97, 0x2b, 0x77, 0xc6,
	0x07, 0xf2, 0x1a, 0xed, 0x03, 0xd9, 0x45, 0x2b, 0x3b, 0x85, 0xc7, 0x14, 0x1c, 0xbb, 0x49, 0xf2,
	0x5e, 0x48, 0x0f, 0xe3, 0x26, 0xc2, 0xe3, 0x56, 0x89, 0xc2, 0x18, 0x1a, 0xaf, 0xb5, 0x6d, 0x20,
	0xcf, 0x85, 0xc7, 0xed, 0x1f, 0xa0, 0xa1, 0xcb, 0x4d, 0x62, 0x76, 0x08, 0x95, 0x54, 0xdc, 0xf2,
	0x88, 0x4a, 0x6d, 0x38, 0x4a, 0x61, 0xcf, 0xa0, 0x91, 0x97, 0xa4, 0x0b, 0xa8, 0x67, 0x05, 0xb0,
	0xa7, 0x40, 0xf2, 0x38, 0x98, 0xf9, 0x3a, 0x4b, 0x0d, 0xf5, 0xde, 0xcc, 0xb7, 0xff, 0x30, 0x60,
	0xc7, 0xe1, 0x7e, 0x90, 0xa4, 0x72, 0x89, 0x6c, 0xb4, 0xf5, 0x39, 0x44, 0x46, 0x95, 0xc8, 0x38,
	0xc8, 0xc9, 0x78, 0x93, 0x70, 0x49, 0x5c, 0xd0, 0x71, 0x44, 0x45, 0x21, 0xaf, 0x71, 0x2f, 0xef,
	0xa7, 0xb0, 0x5b, 0x68, 0x55, 0x17, 0xd6, 0x5c, 0x6f, 0x91, 0xb5, 0xe1, 0x51, 0x91, 0x0f, 0xd7,
	0x77, 0x83, 0x48, 0xd7, 0x79, 0xb0, 0xee, 0xda, 0x41, 0x03, 0x7b, 0x0e, 0xa0, 0xfc, 0x91, 0x54,
	0xab, 0x4c, 0x6e, 0x54, 0x03, 0xb1, 0xcc, 0x3e, 0x83, 0xfd, 0x95, 0x59, 0x11, 0x5b, 0x21, 0x9f,
	0xdd, 0xdc, 0x87, 0x38, 0xbd, 0x83, 0x83, 0xf3, 0xa9, 0x1b, 0xf9, 0x3c, 0x3b, 0x1d, 0xbb, 0xdf,
	0x83, 0xed, 0xc0, 0xa3, 0x36, 0x4a, 0xce, 0x76, 0xe0, 0xfd, 0x27, 0x0d, 0xd8, 0x3f, 0x1b, 0xb0,
	0x8f, 0x4c, 0xf6, 0xa2, 0xb7, 0xe2, 0x32, 0x48, 0x52, 0x4c, 0xcc, 0xa0, 0x1c, 0xbb, 0xbe, 0x62,
	0xb0, 0xe2, 0x90, 0xcc, 0x4c, 0x28, 0x49, 0xf1, 0x9e, 0x52, 0x56, 0x1c, 0x14, 0x8b, 0x64, 0x97,
	0xee, 0x91, 0xfd, 0x0f, 0xbc, 0x64, 0x66, 0xb5, 0xa2, 0x95, 0x95, 0x99, 0xb6, 0xd2, 0x76, 0xc0,
	0x2c, 0xd6, 0x94, 0x6d, 0x5a, 0xea, 0x86, 0x9a, 0x10, 0xa5, 0xb0, 0x63, 0x28, 0x7b, 0x6e, 0xea,
	0x52, 0x5d, 0x3b, 0x67, 0x87, 0x6d, 0xf5, 0x99, 0xb5, 0xb3, 0xcf, 0xac, 0xdd, 0x89, 0x96, 0x0e,
	0x79, 0xd8, 0xbf, 0x19, 0x50, 0x73, 0x44, 0xc8, 0x37, 0x31, 0xfb, 0x0c, 0x1a, 0x52, 0x84, 0xbc,
	0xb0, 0xaf, 0x08, 0x50, 0x2b, 0x9f, 0x40, 0x93, 0x8c, 0xfc, 0x2e, 0x0e, 0x57, 0x54, 0xee, 0x20,
	0xd6, 0x55, 0x10, 0x7b, 0x0c, 0xd5, 0x19, 0x8f, 0xc6, 0x81, 0x67, 0x95, 0x8f, 0x4a, 0x58, 0xdc,
	0x8c, 0x47, 0x3d, 0x0f, 0xe1, 0x44, 0x2e, 0x10, 0xae, 0x28, 0x38, 0x91, 0x0b, 0x05, 0xbb, 0x71,
	0x80, 0x70, 0x55, 0xc1, 0x6e, 0x1c, 0xf4, 0x3c, 0x76, 0x00, 0xe5, 0x18, 0xc1, 0x1a, 0x95, 0x55,
	0x8a, 0x7b, 0x9e, 0xfd, 0x13, 0x34, 0x91, 0x87, 0xef, 0xa5, 0x98, 0xc7, 0x9b, 0xea, 0x7e, 0x0e,
	0xe0, 0xa3, 0x6d, 0xbd, 0xf0, 0x06, 0x21, 0xd9, 0xc6, 0x2b, 0x73, 0xb1, 0xf4, 0x26, 0x81, 0x59,
	0xed, 0xff, 0x83, 0x1a, 0xb5, 0x97, 0x17, 0x5f, 0x45, 0xb5, 0xe7, 0xd9, 0x7f, 0x96, 0xa0, 0xd6,
	0xe7, 0xd1, 0x7c, 0x53, 0x62, 0x13, 0x4a, 0xb7, 0x7c, 0xa9, 0x33, 0xa2, 0x88, 0x3b, 0x93, 0xf2,
	0xbb, 0x54, 0xa7, 0x20, 0x19, 0xb1, 0xe0, 0xf4, 0xdb, 0x48, 0x8f, 0x9f, 0x64, 0xc4, 0xc2, 0x20,
	0xba, 0xd5, 0x33, 0x27, 0x19, 0xeb, 0xe4, 0x77, 0x29, 0x97, 0x91, 0x1b, 0x8e, 0xc9, 0x58, 0x55,
	0x75, 0x66, 0xe0, 0x25, 0x3a, 0x3d, 0x81, 0x6a, 0xea, 0x4a, 0x9f, 0xa7, 0x44, 0x50, 0xc3, 0xd1,
	0x1a, 0x1e, 0x98, 0x08, 0x99, 0x5a, 0x75, 0x75, 0x20, 0xca, 0xb8, 0x2b, 0x37, 0xae, 0xe7, 0x73,
	0xab, 0x41, 0xeb, 0xaa, 0x14, 0x9c, 0x32, 0x09, 0x63, 0x4f, 0x4c, 0x2c, 0x50, 0x53, 0x26, 0xe0,
	0x42, 0x4c, 0x70, 0xca, 0xca, 0x98, 0xa4, 0x6e, 0x3a, 0x4f, 0xac, 0x1d, 0x35, 0x65, 0xc2, 0x86,
	0x04, 0x61, 0xd3, 0xee, 0x24, 0xb4, 0x9a, 0xaa, 0x69, 0x77, 0x12, 0x62, 0xee, 0x69, 0xe0, 0x71,
	0x6b, 0xf7, 0xc8, 0x38, 0xae, 0x3b, 0x24, 0xb3, 0x16, 0xd4, 0xbd, 0x20, 0x71, 0x6f, 0x42, 0xee,
	0x59, 0x7b, 0x84, 0xe7, 0x3a, 0x7b, 0x01, 0x26, 0xfa, 0xf4, 0xa2, 0x57, 0x92, 0xbb, 0xde, 0x44,
	0xce, 0x67, 0x37, 0xd6, 0x3e, 0xf9, 0x7c, 0x80, 0xe3, 0x39, 0xc9, 0x54, 0xc8, 0x74, 0x32, 0x4f,
	0x2d, 0x53, 0x9d, 0x93, 0xe9, 0x48, 0x58, 0x26, 0x8f, 0xa5, 0x10, 0xa9, 0x75, 0x40, 0x0e, 0xcd,
	0x0c, 0x74, 0x84, 0x20, 0x12, 0x24, 0x9f, 0x27, 0xdc, 0x62, 0x64, 0x54, 0x0a, 0xcd, 0x64, 0x22,
	0x22, 0xeb, 0x91, 0x9e, 0xc9, 0x44, 0x44, 0xd8, 0x58, 0x1c, 0x78, 0xd6, 0xa1, 0x5e, 0xbc, 0xc0,
	0xb3, 0x6f, 0xa1, 0xda, 0x89, 0x83, 0x4d, 0x93, 0xb7, 0xa0, 0x96, 0x70, 0xb9, 0x08, 0x26, 0xd9,
	0xbe, 0x65, 0x2a, 0x0e, 0x68, 0xc6, 0xd3, 0xa9, 0xf0, 0xf4, 0x0e, 0x68, 0x8d, 0xfd, 0x1f, 0x76,
	0x70, 0xdd, 0xb3, 0x1d, 0x54, 0xcb, 0x00, 0x6e, 0x1c, 0xe8, 0x0d, 0xc4, 0x64, 0x43, 0xb9, 0xf8,
	0xd7, 0x92, 0xe1, 0x27, 0x77, 0x2f, 0x59, 0x22, 0x17, 0x59, 0xb2, 0x5f, 0x0c, 0xa8, 0x8d, 0x24,
	0xdf, 0x78, 0x0d, 0x30, 0x28, 0xe3, 0x6d, 0xac, 0x73, 0x91, 0x8c, 0xd8, 0x68, 0x6d, 0xaf, 0x47,
	0x7a, 0xaf, 0x87, 0xb8, 0x72, 0x65, 0x75, 0x3f, 0xa2, 0x9c, 0x7f, 0xbd, 0x95, 0xfc, 0xeb, 0x65,
	0x5f, 0x40, 0xfd, 0x7c, 0x1a, 0x84, 0x9e, 0xe4, 0x11, 0x7d, 0xe9, 0x3b, 0x67, 0x66, 0xfe, 0x78,
	0xe9, 0x12, 0x9c, 0xdc, 0xc3, 0xb6, 0xa0, 0x7a, 0xc1, 0xc3, 0x0d, 0x65, 0xd9, 0x2d, 0xa8, 0x77,
	0xbd, 0x40, 0xdd, 0x82, 0xf7, 0x6c, 0x2f, 0x3e, 0xd7, 0x8f, 0x31, 0x3d, 0x7f, 0x75, 0x28, 0x5f,
	0x75, 0xfa, 0x5d, 0x73, 0x8b, 0x35, 0xa0, 0x72, 0xfd, 0x7a, 0x70, 0xd5, 0x35, 0x0d, 0x14, 0xbb,
	0xfd, 0x4e, 0xef, 0xd2, 0xdc, 0x7e, 0xf1, 0x12, 0xea, 0xd9, 0xa3, 0x89, 0x70, 0xe7, 0xa2, 0xdf,
	0xbb, 0x32, 0xb7, 0x58, 0x13, 0xea, 0xd7, 0x97, 0x9d, 0xd1, 0x77, 0x03, 0xa7, 0x6f, 0x1a, 0x78,
	0xc8, 0xf0, 0xf5, 0xe0, 0xda, 0xdc, 0x46, 0xfc, 0xfc, 0xcd, 0x70, 0x34, 0xe8, 0x77, 0x1d, 0xb3,
	0x74, 0xf6, 0x7b, 0x15, 0x6a, 0x18, 0x3d, 0x94, 0x0b, 0xf6, 0x25, 0x54, 0x28, 0x2b, 0x3b, 0x28,
	0xfe, 0x9a, 0x38, 0xfc, 0x5d, 0x8b, 0xdd, 0x87, 0x92, 0xd8, 0xde, 0x62, 0xdf, 0x40, 0x3d, 0x7b,
	0xd8, 0xd9, 0x61, 0xee, 0xb1, 0xf6, 0xd6, 0xb7, 0x56, 0x47, 0x65, 0xcd, 0xda, 0x5b, 0xac, 0x03,
	0x7b, 0xc5, 0x77, 0x91, 0xb5, 0x72, 0xb7, 0x0f, 0x1e, 0xcc, 0xcd, 0x47, 0x74, 0xd5, 0x1d, 0x9a,
	0xbd, 0x25, 0xcc, 0x2a, 0xfc, 0x40, 0xac, 0x3d, 0x7b, 0xad, 0xa7, 0x7f, 0x63, 0xa1, 0x63, 0x4e,
	0xf5, 0x10, 0x44, 0xc8, 0xd9, 0x6a, 0x8c, 0xfa, 0x41, 0xd9, 0x9c, 0xf9, 0x04, 0x6a, 0x38, 0x51,
	0x8c, 0xd8, 0xcf, 0xed, 0x6a, 0xc6, 0x9b, 0x03, 0x5e, 0xc2, 0x2e, 0x6a, 0xf9, 0x95, 0xcf, 0x1e,
	0x17, 0x2a, 0xca, 0x9e, 0x81, 0xcd, 0xc1, 0x5f, 0x43, 0xf3, 0x82, 0x87, 0xab, 0xd8, 0x87, 0xa5,
	0xd4, 0x6d, 0xe1, 0x3d, 0xbf, 0xd6, 0x96, 0xbe, 0xf6, 0x3f, 0xd6, 0x16, 0x45, 0x3c, 0x2c, 0xc7,
	0x09, 0xd4, 0x50, 0xeb, 0xc4, 0xc1, 0x5a, 0x80, 0xba, 0x5e, 0x36, 0x07, 0xb4, 0xe9, 0x53, 0x28,
	0xfa, 0x3f, 0x20, 0x01, 0x6e, 0xe6, 0x2a, 0x40, 0x5d, 0x29, 0x1f, 0x4b, 0x50, 0xf4, 0x7f, 0x00,
	0x4b, 0xf8, 0xd1, 0xb2, 0x0f, 0xbe, 0xe1, 0x8f, 0xb1, 0x44, 0x11, 0x0f, 0xca, 0xf1, 0x6a, 0xff,
	0xc7, 0x5d, 0xfa, 0x6b, 0x39, 0xd1, 0xb6, 0x9b, 0x2a, 0xa9, 0x5f, 0xfd, 0x15, 0x00, 0x00, 0xff,
	0xff, 0xeb, 0x09, 0xdd, 0x42, 0x53, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserSrvClient is the client API for UserSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserSrvClient interface {
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	Registry(ctx context.Context, in *RegistryReq, opts ...grpc.CallOption) (*EditResp, error)
	ChangePassword(ctx context.Context, in *ChangePasswordReq, opts ...grpc.CallOption) (*EditResp, error)
	UserInfoList(ctx context.Context, in *UserInfoListReq, opts ...grpc.CallOption) (*UserInfoListResp, error)
	EditRole(ctx context.Context, in *RoleReq, opts ...grpc.CallOption) (*EditResp, error)
	DelRole(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*EditResp, error)
	EditUserGroup(ctx context.Context, in *UserGroupReq, opts ...grpc.CallOption) (*EditResp, error)
	DelUserGroup(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*EditResp, error)
	EditMenu(ctx context.Context, in *MenuReq, opts ...grpc.CallOption) (*EditResp, error)
	DelMenu(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*EditResp, error)
	EditApi(ctx context.Context, in *ApiReq, opts ...grpc.CallOption) (*EditResp, error)
	DelApi(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*EditResp, error)
	EditSrv(ctx context.Context, in *SrvReq, opts ...grpc.CallOption) (*EditResp, error)
	DelSrv(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*EditResp, error)
	EditTree(ctx context.Context, in *TreeReq, opts ...grpc.CallOption) (*EditResp, error)
	DelTree(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*EditResp, error)
}

type userSrvClient struct {
	cc *grpc.ClientConn
}

func NewUserSrvClient(cc *grpc.ClientConn) UserSrvClient {
	return &userSrvClient{cc}
}

func (c *userSrvClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, "/sysuser.UserSrv/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSrvClient) Registry(ctx context.Context, in *RegistryReq, opts ...grpc.CallOption) (*EditResp, error) {
	out := new(EditResp)
	err := c.cc.Invoke(ctx, "/sysuser.UserSrv/Registry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSrvClient) ChangePassword(ctx context.Context, in *ChangePasswordReq, opts ...grpc.CallOption) (*EditResp, error) {
	out := new(EditResp)
	err := c.cc.Invoke(ctx, "/sysuser.UserSrv/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSrvClient) UserInfoList(ctx context.Context, in *UserInfoListReq, opts ...grpc.CallOption) (*UserInfoListResp, error) {
	out := new(UserInfoListResp)
	err := c.cc.Invoke(ctx, "/sysuser.UserSrv/UserInfoList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSrvClient) EditRole(ctx context.Context, in *RoleReq, opts ...grpc.CallOption) (*EditResp, error) {
	out := new(EditResp)
	err := c.cc.Invoke(ctx, "/sysuser.UserSrv/EditRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSrvClient) DelRole(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*EditResp, error) {
	out := new(EditResp)
	err := c.cc.Invoke(ctx, "/sysuser.UserSrv/DelRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSrvClient) EditUserGroup(ctx context.Context, in *UserGroupReq, opts ...grpc.CallOption) (*EditResp, error) {
	out := new(EditResp)
	err := c.cc.Invoke(ctx, "/sysuser.UserSrv/EditUserGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSrvClient) DelUserGroup(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*EditResp, error) {
	out := new(EditResp)
	err := c.cc.Invoke(ctx, "/sysuser.UserSrv/DelUserGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSrvClient) EditMenu(ctx context.Context, in *MenuReq, opts ...grpc.CallOption) (*EditResp, error) {
	out := new(EditResp)
	err := c.cc.Invoke(ctx, "/sysuser.UserSrv/EditMenu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSrvClient) DelMenu(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*EditResp, error) {
	out := new(EditResp)
	err := c.cc.Invoke(ctx, "/sysuser.UserSrv/DelMenu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSrvClient) EditApi(ctx context.Context, in *ApiReq, opts ...grpc.CallOption) (*EditResp, error) {
	out := new(EditResp)
	err := c.cc.Invoke(ctx, "/sysuser.UserSrv/EditApi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSrvClient) DelApi(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*EditResp, error) {
	out := new(EditResp)
	err := c.cc.Invoke(ctx, "/sysuser.UserSrv/DelApi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSrvClient) EditSrv(ctx context.Context, in *SrvReq, opts ...grpc.CallOption) (*EditResp, error) {
	out := new(EditResp)
	err := c.cc.Invoke(ctx, "/sysuser.UserSrv/EditSrv", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSrvClient) DelSrv(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*EditResp, error) {
	out := new(EditResp)
	err := c.cc.Invoke(ctx, "/sysuser.UserSrv/DelSrv", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSrvClient) EditTree(ctx context.Context, in *TreeReq, opts ...grpc.CallOption) (*EditResp, error) {
	out := new(EditResp)
	err := c.cc.Invoke(ctx, "/sysuser.UserSrv/EditTree", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSrvClient) DelTree(ctx context.Context, in *DelReq, opts ...grpc.CallOption) (*EditResp, error) {
	out := new(EditResp)
	err := c.cc.Invoke(ctx, "/sysuser.UserSrv/DelTree", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserSrvServer is the server API for UserSrv service.
type UserSrvServer interface {
	Login(context.Context, *LoginReq) (*LoginResp, error)
	Registry(context.Context, *RegistryReq) (*EditResp, error)
	ChangePassword(context.Context, *ChangePasswordReq) (*EditResp, error)
	UserInfoList(context.Context, *UserInfoListReq) (*UserInfoListResp, error)
	EditRole(context.Context, *RoleReq) (*EditResp, error)
	DelRole(context.Context, *DelReq) (*EditResp, error)
	EditUserGroup(context.Context, *UserGroupReq) (*EditResp, error)
	DelUserGroup(context.Context, *DelReq) (*EditResp, error)
	EditMenu(context.Context, *MenuReq) (*EditResp, error)
	DelMenu(context.Context, *DelReq) (*EditResp, error)
	EditApi(context.Context, *ApiReq) (*EditResp, error)
	DelApi(context.Context, *DelReq) (*EditResp, error)
	EditSrv(context.Context, *SrvReq) (*EditResp, error)
	DelSrv(context.Context, *DelReq) (*EditResp, error)
	EditTree(context.Context, *TreeReq) (*EditResp, error)
	DelTree(context.Context, *DelReq) (*EditResp, error)
}

// UnimplementedUserSrvServer can be embedded to have forward compatible implementations.
type UnimplementedUserSrvServer struct {
}

func (*UnimplementedUserSrvServer) Login(ctx context.Context, req *LoginReq) (*LoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedUserSrvServer) Registry(ctx context.Context, req *RegistryReq) (*EditResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Registry not implemented")
}
func (*UnimplementedUserSrvServer) ChangePassword(ctx context.Context, req *ChangePasswordReq) (*EditResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (*UnimplementedUserSrvServer) UserInfoList(ctx context.Context, req *UserInfoListReq) (*UserInfoListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserInfoList not implemented")
}
func (*UnimplementedUserSrvServer) EditRole(ctx context.Context, req *RoleReq) (*EditResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditRole not implemented")
}
func (*UnimplementedUserSrvServer) DelRole(ctx context.Context, req *DelReq) (*EditResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelRole not implemented")
}
func (*UnimplementedUserSrvServer) EditUserGroup(ctx context.Context, req *UserGroupReq) (*EditResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditUserGroup not implemented")
}
func (*UnimplementedUserSrvServer) DelUserGroup(ctx context.Context, req *DelReq) (*EditResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelUserGroup not implemented")
}
func (*UnimplementedUserSrvServer) EditMenu(ctx context.Context, req *MenuReq) (*EditResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditMenu not implemented")
}
func (*UnimplementedUserSrvServer) DelMenu(ctx context.Context, req *DelReq) (*EditResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelMenu not implemented")
}
func (*UnimplementedUserSrvServer) EditApi(ctx context.Context, req *ApiReq) (*EditResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditApi not implemented")
}
func (*UnimplementedUserSrvServer) DelApi(ctx context.Context, req *DelReq) (*EditResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelApi not implemented")
}
func (*UnimplementedUserSrvServer) EditSrv(ctx context.Context, req *SrvReq) (*EditResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditSrv not implemented")
}
func (*UnimplementedUserSrvServer) DelSrv(ctx context.Context, req *DelReq) (*EditResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelSrv not implemented")
}
func (*UnimplementedUserSrvServer) EditTree(ctx context.Context, req *TreeReq) (*EditResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditTree not implemented")
}
func (*UnimplementedUserSrvServer) DelTree(ctx context.Context, req *DelReq) (*EditResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelTree not implemented")
}

func RegisterUserSrvServer(s *grpc.Server, srv UserSrvServer) {
	s.RegisterService(&_UserSrv_serviceDesc, srv)
}

func _UserSrv_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSrvServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sysuser.UserSrv/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSrvServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSrv_Registry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSrvServer).Registry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sysuser.UserSrv/Registry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSrvServer).Registry(ctx, req.(*RegistryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSrv_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSrvServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sysuser.UserSrv/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSrvServer).ChangePassword(ctx, req.(*ChangePasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSrv_UserInfoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSrvServer).UserInfoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sysuser.UserSrv/UserInfoList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSrvServer).UserInfoList(ctx, req.(*UserInfoListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSrv_EditRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSrvServer).EditRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sysuser.UserSrv/EditRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSrvServer).EditRole(ctx, req.(*RoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSrv_DelRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSrvServer).DelRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sysuser.UserSrv/DelRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSrvServer).DelRole(ctx, req.(*DelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSrv_EditUserGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSrvServer).EditUserGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sysuser.UserSrv/EditUserGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSrvServer).EditUserGroup(ctx, req.(*UserGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSrv_DelUserGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSrvServer).DelUserGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sysuser.UserSrv/DelUserGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSrvServer).DelUserGroup(ctx, req.(*DelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSrv_EditMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSrvServer).EditMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sysuser.UserSrv/EditMenu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSrvServer).EditMenu(ctx, req.(*MenuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSrv_DelMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSrvServer).DelMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sysuser.UserSrv/DelMenu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSrvServer).DelMenu(ctx, req.(*DelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSrv_EditApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSrvServer).EditApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sysuser.UserSrv/EditApi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSrvServer).EditApi(ctx, req.(*ApiReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSrv_DelApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSrvServer).DelApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sysuser.UserSrv/DelApi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSrvServer).DelApi(ctx, req.(*DelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSrv_EditSrv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SrvReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSrvServer).EditSrv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sysuser.UserSrv/EditSrv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSrvServer).EditSrv(ctx, req.(*SrvReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSrv_DelSrv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSrvServer).DelSrv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sysuser.UserSrv/DelSrv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSrvServer).DelSrv(ctx, req.(*DelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSrv_EditTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TreeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSrvServer).EditTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sysuser.UserSrv/EditTree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSrvServer).EditTree(ctx, req.(*TreeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSrv_DelTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSrvServer).DelTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sysuser.UserSrv/DelTree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSrvServer).DelTree(ctx, req.(*DelReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserSrv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sysuser.UserSrv",
	HandlerType: (*UserSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _UserSrv_Login_Handler,
		},
		{
			MethodName: "Registry",
			Handler:    _UserSrv_Registry_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _UserSrv_ChangePassword_Handler,
		},
		{
			MethodName: "UserInfoList",
			Handler:    _UserSrv_UserInfoList_Handler,
		},
		{
			MethodName: "EditRole",
			Handler:    _UserSrv_EditRole_Handler,
		},
		{
			MethodName: "DelRole",
			Handler:    _UserSrv_DelRole_Handler,
		},
		{
			MethodName: "EditUserGroup",
			Handler:    _UserSrv_EditUserGroup_Handler,
		},
		{
			MethodName: "DelUserGroup",
			Handler:    _UserSrv_DelUserGroup_Handler,
		},
		{
			MethodName: "EditMenu",
			Handler:    _UserSrv_EditMenu_Handler,
		},
		{
			MethodName: "DelMenu",
			Handler:    _UserSrv_DelMenu_Handler,
		},
		{
			MethodName: "EditApi",
			Handler:    _UserSrv_EditApi_Handler,
		},
		{
			MethodName: "DelApi",
			Handler:    _UserSrv_DelApi_Handler,
		},
		{
			MethodName: "EditSrv",
			Handler:    _UserSrv_EditSrv_Handler,
		},
		{
			MethodName: "DelSrv",
			Handler:    _UserSrv_DelSrv_Handler,
		},
		{
			MethodName: "EditTree",
			Handler:    _UserSrv_EditTree_Handler,
		},
		{
			MethodName: "DelTree",
			Handler:    _UserSrv_DelTree_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sysuser.proto",
}
