// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/dbmodel/dbmodel.proto

package dbmodel

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Timestamp from public import google/protobuf/timestamp.proto
type Timestamp = timestamp.Timestamp

type LoginType int32

const (
	LoginType_NAME  LoginType = 0
	LoginType_PHONE LoginType = 1
	LoginType_EMAIL LoginType = 2
)

var LoginType_name = map[int32]string{
	0: "NAME",
	1: "PHONE",
	2: "EMAIL",
}

var LoginType_value = map[string]int32{
	"NAME":  0,
	"PHONE": 1,
	"EMAIL": 2,
}

func (x LoginType) String() string {
	return proto.EnumName(LoginType_name, int32(x))
}

func (LoginType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{0}
}

type UserType int32

const (
	UserType_ADMIN    UserType = 0
	UserType_PLATFORM UserType = 1
	UserType_SHOP     UserType = 2
	UserType_CUSTOMER UserType = 3
)

var UserType_name = map[int32]string{
	0: "ADMIN",
	1: "PLATFORM",
	2: "SHOP",
	3: "CUSTOMER",
}

var UserType_value = map[string]int32{
	"ADMIN":    0,
	"PLATFORM": 1,
	"SHOP":     2,
	"CUSTOMER": 3,
}

func (x UserType) String() string {
	return proto.EnumName(UserType_name, int32(x))
}

func (UserType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{1}
}

type FileType int32

const (
	FileType_USERLOG     FileType = 0
	FileType_SHOPLOG     FileType = 1
	FileType_PLATFORMIMG FileType = 2
	FileType_INDEXLBTIMG FileType = 3
	FileType_PRODUCTIMG  FileType = 4
	FileType_OTHERIMG    FileType = 5
)

var FileType_name = map[int32]string{
	0: "USERLOG",
	1: "SHOPLOG",
	2: "PLATFORMIMG",
	3: "INDEXLBTIMG",
	4: "PRODUCTIMG",
	5: "OTHERIMG",
}

var FileType_value = map[string]int32{
	"USERLOG":     0,
	"SHOPLOG":     1,
	"PLATFORMIMG": 2,
	"INDEXLBTIMG": 3,
	"PRODUCTIMG":  4,
	"OTHERIMG":    5,
}

func (x FileType) String() string {
	return proto.EnumName(FileType_name, int32(x))
}

func (FileType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{2}
}

type SysUser struct {
	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName  string `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	TrueName  string `protobuf:"bytes,3,opt,name=true_name,json=trueName,proto3" json:"true_name,omitempty"`
	UserPhone string `protobuf:"bytes,4,opt,name=user_phone,json=userPhone,proto3" json:"user_phone,omitempty"`
	//string user_password=22;
	//string wx_open_id=23;
	UserWx               string              `protobuf:"bytes,5,opt,name=user_wx,json=userWx,proto3" json:"user_wx,omitempty"`
	UserEmail            string              `protobuf:"bytes,6,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	UserQq               string              `protobuf:"bytes,7,opt,name=user_qq,json=userQq,proto3" json:"user_qq,omitempty"`
	UserTel              string              `protobuf:"bytes,8,opt,name=user_tel,json=userTel,proto3" json:"user_tel,omitempty"`
	Balance              string              `protobuf:"bytes,9,opt,name=balance,proto3" json:"balance,omitempty"`
	IdCard               string              `protobuf:"bytes,10,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`
	Point                int64               `protobuf:"varint,11,opt,name=point,proto3" json:"point,omitempty"`
	ProvinceId           int64               `protobuf:"varint,12,opt,name=province_id,json=provinceId,proto3" json:"province_id,omitempty"`
	Province             *SysTree            `protobuf:"bytes,13,opt,name=province,proto3" json:"province,omitempty"`
	CityId               int64               `protobuf:"varint,14,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	City                 *SysTree            `protobuf:"bytes,15,opt,name=city,proto3" json:"city,omitempty"`
	AreaId               int64               `protobuf:"varint,16,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	Area                 *SysTree            `protobuf:"bytes,17,opt,name=area,proto3" json:"area,omitempty"`
	Address              string              `protobuf:"bytes,18,opt,name=address,proto3" json:"address,omitempty"`
	Vip                  int32               `protobuf:"varint,19,opt,name=vip,proto3" json:"vip,omitempty"`
	BankName             string              `protobuf:"bytes,20,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	BranchName           string              `protobuf:"bytes,21,opt,name=branch_name,json=branchName,proto3" json:"branch_name,omitempty"`
	Bankcard             string              `protobuf:"bytes,22,opt,name=bankcard,proto3" json:"bankcard,omitempty"`
	BankCardName         string              `protobuf:"bytes,23,opt,name=bank_card_name,json=bankCardName,proto3" json:"bank_card_name,omitempty"`
	UserIcon             int64               `protobuf:"varint,24,opt,name=user_icon,json=userIcon,proto3" json:"user_icon,omitempty"`
	Icon                 *SysFile            `protobuf:"bytes,25,opt,name=icon,proto3" json:"icon,omitempty"`
	Roles                []*SysRole          `protobuf:"bytes,26,rep,name=roles,proto3" json:"roles,omitempty"`
	Groups               []*SysGroup         `protobuf:"bytes,27,rep,name=groups,proto3" json:"groups,omitempty"`
	LogisticsAddresss    []*LogisticsAddress `protobuf:"bytes,28,rep,name=logistics_addresss,json=logisticsAddresss,proto3" json:"logistics_addresss,omitempty"`
	Qualifications       []*Qualification    `protobuf:"bytes,29,rep,name=qualifications,proto3" json:"qualifications,omitempty"`
	UserType             UserType            `protobuf:"varint,30,opt,name=user_type,json=userType,proto3,enum=dbmodel.UserType" json:"user_type,omitempty"`
	Created              int64               `protobuf:"varint,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64               `protobuf:"varint,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SysUser) Reset()         { *m = SysUser{} }
func (m *SysUser) String() string { return proto.CompactTextString(m) }
func (*SysUser) ProtoMessage()    {}
func (*SysUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{0}
}

func (m *SysUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysUser.Unmarshal(m, b)
}
func (m *SysUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysUser.Marshal(b, m, deterministic)
}
func (m *SysUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysUser.Merge(m, src)
}
func (m *SysUser) XXX_Size() int {
	return xxx_messageInfo_SysUser.Size(m)
}
func (m *SysUser) XXX_DiscardUnknown() {
	xxx_messageInfo_SysUser.DiscardUnknown(m)
}

var xxx_messageInfo_SysUser proto.InternalMessageInfo

func (m *SysUser) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SysUser) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *SysUser) GetTrueName() string {
	if m != nil {
		return m.TrueName
	}
	return ""
}

func (m *SysUser) GetUserPhone() string {
	if m != nil {
		return m.UserPhone
	}
	return ""
}

func (m *SysUser) GetUserWx() string {
	if m != nil {
		return m.UserWx
	}
	return ""
}

func (m *SysUser) GetUserEmail() string {
	if m != nil {
		return m.UserEmail
	}
	return ""
}

func (m *SysUser) GetUserQq() string {
	if m != nil {
		return m.UserQq
	}
	return ""
}

func (m *SysUser) GetUserTel() string {
	if m != nil {
		return m.UserTel
	}
	return ""
}

func (m *SysUser) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *SysUser) GetIdCard() string {
	if m != nil {
		return m.IdCard
	}
	return ""
}

func (m *SysUser) GetPoint() int64 {
	if m != nil {
		return m.Point
	}
	return 0
}

func (m *SysUser) GetProvinceId() int64 {
	if m != nil {
		return m.ProvinceId
	}
	return 0
}

func (m *SysUser) GetProvince() *SysTree {
	if m != nil {
		return m.Province
	}
	return nil
}

func (m *SysUser) GetCityId() int64 {
	if m != nil {
		return m.CityId
	}
	return 0
}

func (m *SysUser) GetCity() *SysTree {
	if m != nil {
		return m.City
	}
	return nil
}

func (m *SysUser) GetAreaId() int64 {
	if m != nil {
		return m.AreaId
	}
	return 0
}

func (m *SysUser) GetArea() *SysTree {
	if m != nil {
		return m.Area
	}
	return nil
}

func (m *SysUser) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SysUser) GetVip() int32 {
	if m != nil {
		return m.Vip
	}
	return 0
}

func (m *SysUser) GetBankName() string {
	if m != nil {
		return m.BankName
	}
	return ""
}

func (m *SysUser) GetBranchName() string {
	if m != nil {
		return m.BranchName
	}
	return ""
}

func (m *SysUser) GetBankcard() string {
	if m != nil {
		return m.Bankcard
	}
	return ""
}

func (m *SysUser) GetBankCardName() string {
	if m != nil {
		return m.BankCardName
	}
	return ""
}

func (m *SysUser) GetUserIcon() int64 {
	if m != nil {
		return m.UserIcon
	}
	return 0
}

func (m *SysUser) GetIcon() *SysFile {
	if m != nil {
		return m.Icon
	}
	return nil
}

func (m *SysUser) GetRoles() []*SysRole {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *SysUser) GetGroups() []*SysGroup {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *SysUser) GetLogisticsAddresss() []*LogisticsAddress {
	if m != nil {
		return m.LogisticsAddresss
	}
	return nil
}

func (m *SysUser) GetQualifications() []*Qualification {
	if m != nil {
		return m.Qualifications
	}
	return nil
}

func (m *SysUser) GetUserType() UserType {
	if m != nil {
		return m.UserType
	}
	return UserType_ADMIN
}

func (m *SysUser) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *SysUser) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type SysFile struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Size                 int64    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	FileExplain          string   `protobuf:"bytes,5,opt,name=file_explain,json=fileExplain,proto3" json:"file_explain,omitempty"`
	Sort                 int32    `protobuf:"varint,6,opt,name=sort,proto3" json:"sort,omitempty"`
	FileType             FileType `protobuf:"varint,7,opt,name=file_type,json=fileType,proto3,enum=dbmodel.FileType" json:"file_type,omitempty"`
	FileSuffix           string   `protobuf:"bytes,8,opt,name=file_suffix,json=fileSuffix,proto3" json:"file_suffix,omitempty"`
	Created              int64    `protobuf:"varint,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SysFile) Reset()         { *m = SysFile{} }
func (m *SysFile) String() string { return proto.CompactTextString(m) }
func (*SysFile) ProtoMessage()    {}
func (*SysFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{1}
}

func (m *SysFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysFile.Unmarshal(m, b)
}
func (m *SysFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysFile.Marshal(b, m, deterministic)
}
func (m *SysFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysFile.Merge(m, src)
}
func (m *SysFile) XXX_Size() int {
	return xxx_messageInfo_SysFile.Size(m)
}
func (m *SysFile) XXX_DiscardUnknown() {
	xxx_messageInfo_SysFile.DiscardUnknown(m)
}

var xxx_messageInfo_SysFile proto.InternalMessageInfo

func (m *SysFile) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SysFile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SysFile) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *SysFile) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SysFile) GetFileExplain() string {
	if m != nil {
		return m.FileExplain
	}
	return ""
}

func (m *SysFile) GetSort() int32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *SysFile) GetFileType() FileType {
	if m != nil {
		return m.FileType
	}
	return FileType_USERLOG
}

func (m *SysFile) GetFileSuffix() string {
	if m != nil {
		return m.FileSuffix
	}
	return ""
}

func (m *SysFile) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *SysFile) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type SysTree struct {
	Id                   int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 string     `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Text                 string     `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Sort                 int32      `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	PId                  int64      `protobuf:"varint,5,opt,name=p_id,json=pId,proto3" json:"p_id,omitempty"`
	Children             []*SysTree `protobuf:"bytes,6,rep,name=children,proto3" json:"children,omitempty"`
	Created              int64      `protobuf:"varint,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64      `protobuf:"varint,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SysTree) Reset()         { *m = SysTree{} }
func (m *SysTree) String() string { return proto.CompactTextString(m) }
func (*SysTree) ProtoMessage()    {}
func (*SysTree) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{2}
}

func (m *SysTree) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysTree.Unmarshal(m, b)
}
func (m *SysTree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysTree.Marshal(b, m, deterministic)
}
func (m *SysTree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysTree.Merge(m, src)
}
func (m *SysTree) XXX_Size() int {
	return xxx_messageInfo_SysTree.Size(m)
}
func (m *SysTree) XXX_DiscardUnknown() {
	xxx_messageInfo_SysTree.DiscardUnknown(m)
}

var xxx_messageInfo_SysTree proto.InternalMessageInfo

func (m *SysTree) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SysTree) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *SysTree) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *SysTree) GetSort() int32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *SysTree) GetPId() int64 {
	if m != nil {
		return m.PId
	}
	return 0
}

func (m *SysTree) GetChildren() []*SysTree {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *SysTree) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *SysTree) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

//用户组请求
type SysGroup struct {
	Id                   int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupName            string     `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	GroupExplain         string     `protobuf:"bytes,3,opt,name=group_explain,json=groupExplain,proto3" json:"group_explain,omitempty"`
	Roles                []*SysRole `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	Users                []*SysRole `protobuf:"bytes,5,rep,name=users,proto3" json:"users,omitempty"`
	Created              int64      `protobuf:"varint,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64      `protobuf:"varint,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SysGroup) Reset()         { *m = SysGroup{} }
func (m *SysGroup) String() string { return proto.CompactTextString(m) }
func (*SysGroup) ProtoMessage()    {}
func (*SysGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{3}
}

func (m *SysGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysGroup.Unmarshal(m, b)
}
func (m *SysGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysGroup.Marshal(b, m, deterministic)
}
func (m *SysGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysGroup.Merge(m, src)
}
func (m *SysGroup) XXX_Size() int {
	return xxx_messageInfo_SysGroup.Size(m)
}
func (m *SysGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_SysGroup.DiscardUnknown(m)
}

var xxx_messageInfo_SysGroup proto.InternalMessageInfo

func (m *SysGroup) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SysGroup) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *SysGroup) GetGroupExplain() string {
	if m != nil {
		return m.GroupExplain
	}
	return ""
}

func (m *SysGroup) GetRoles() []*SysRole {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *SysGroup) GetUsers() []*SysRole {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *SysGroup) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *SysGroup) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

//角色请求
type SysRole struct {
	Id                   int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoleName             string     `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	RoleExplain          string     `protobuf:"bytes,3,opt,name=role_explain,json=roleExplain,proto3" json:"role_explain,omitempty"`
	Menus                []*SysMenu `protobuf:"bytes,4,rep,name=menus,proto3" json:"menus,omitempty"`
	Srvs                 []*SysSrv  `protobuf:"bytes,5,rep,name=srvs,proto3" json:"srvs,omitempty"`
	Apis                 []*SysApi  `protobuf:"bytes,6,rep,name=apis,proto3" json:"apis,omitempty"`
	Users                []*SysUser `protobuf:"bytes,7,rep,name=users,proto3" json:"users,omitempty"`
	PId                  int64      `protobuf:"varint,8,opt,name=p_id,json=pId,proto3" json:"p_id,omitempty"`
	Children             []*SysRole `protobuf:"bytes,9,rep,name=children,proto3" json:"children,omitempty"`
	Created              int64      `protobuf:"varint,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64      `protobuf:"varint,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SysRole) Reset()         { *m = SysRole{} }
func (m *SysRole) String() string { return proto.CompactTextString(m) }
func (*SysRole) ProtoMessage()    {}
func (*SysRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{4}
}

func (m *SysRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysRole.Unmarshal(m, b)
}
func (m *SysRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysRole.Marshal(b, m, deterministic)
}
func (m *SysRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysRole.Merge(m, src)
}
func (m *SysRole) XXX_Size() int {
	return xxx_messageInfo_SysRole.Size(m)
}
func (m *SysRole) XXX_DiscardUnknown() {
	xxx_messageInfo_SysRole.DiscardUnknown(m)
}

var xxx_messageInfo_SysRole proto.InternalMessageInfo

func (m *SysRole) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SysRole) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *SysRole) GetRoleExplain() string {
	if m != nil {
		return m.RoleExplain
	}
	return ""
}

func (m *SysRole) GetMenus() []*SysMenu {
	if m != nil {
		return m.Menus
	}
	return nil
}

func (m *SysRole) GetSrvs() []*SysSrv {
	if m != nil {
		return m.Srvs
	}
	return nil
}

func (m *SysRole) GetApis() []*SysApi {
	if m != nil {
		return m.Apis
	}
	return nil
}

func (m *SysRole) GetUsers() []*SysUser {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *SysRole) GetPId() int64 {
	if m != nil {
		return m.PId
	}
	return 0
}

func (m *SysRole) GetChildren() []*SysRole {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *SysRole) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *SysRole) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type SysMenu struct {
	Id                   int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Key                  string     `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Text                 string     `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	I18N                 string     `protobuf:"bytes,4,opt,name=i18n,proto3" json:"i18n,omitempty"`
	Link                 string     `protobuf:"bytes,5,opt,name=link,proto3" json:"link,omitempty"`
	ExternalLink         string     `protobuf:"bytes,6,opt,name=external_link,json=externalLink,proto3" json:"external_link,omitempty"`
	Target               string     `protobuf:"bytes,7,opt,name=target,proto3" json:"target,omitempty"`
	Sort                 string     `protobuf:"bytes,8,opt,name=sort,proto3" json:"sort,omitempty"`
	Badge                int32      `protobuf:"varint,9,opt,name=badge,proto3" json:"badge,omitempty"`
	BadgeDoc             string     `protobuf:"bytes,10,opt,name=badge_doc,json=badgeDoc,proto3" json:"badge_doc,omitempty"`
	BadgeStatus          string     `protobuf:"bytes,11,opt,name=badge_status,json=badgeStatus,proto3" json:"badge_status,omitempty"`
	Acl                  string     `protobuf:"bytes,12,opt,name=acl,proto3" json:"acl,omitempty"`
	Hide                 bool       `protobuf:"varint,13,opt,name=hide,proto3" json:"hide,omitempty"`
	Disabled             bool       `protobuf:"varint,14,opt,name=disabled,proto3" json:"disabled,omitempty"`
	HideInBreadcrumb     bool       `protobuf:"varint,15,opt,name=hideInBreadcrumb,proto3" json:"hideInBreadcrumb,omitempty"`
	Shortcut             bool       `protobuf:"varint,16,opt,name=shortcut,proto3" json:"shortcut,omitempty"`
	ShortcutRoot         bool       `protobuf:"varint,17,opt,name=shortcut_root,json=shortcutRoot,proto3" json:"shortcut_root,omitempty"`
	Reuse                bool       `protobuf:"varint,18,opt,name=reuse,proto3" json:"reuse,omitempty"`
	Icon                 string     `protobuf:"bytes,19,opt,name=icon,proto3" json:"icon,omitempty"`
	PId                  int64      `protobuf:"varint,20,opt,name=p_id,json=pId,proto3" json:"p_id,omitempty"`
	Children             []*SysMenu `protobuf:"bytes,21,rep,name=children,proto3" json:"children,omitempty"`
	Group                bool       `protobuf:"varint,22,opt,name=group,proto3" json:"group,omitempty"`
	Created              int64      `protobuf:"varint,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64      `protobuf:"varint,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SysMenu) Reset()         { *m = SysMenu{} }
func (m *SysMenu) String() string { return proto.CompactTextString(m) }
func (*SysMenu) ProtoMessage()    {}
func (*SysMenu) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{5}
}

func (m *SysMenu) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysMenu.Unmarshal(m, b)
}
func (m *SysMenu) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysMenu.Marshal(b, m, deterministic)
}
func (m *SysMenu) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysMenu.Merge(m, src)
}
func (m *SysMenu) XXX_Size() int {
	return xxx_messageInfo_SysMenu.Size(m)
}
func (m *SysMenu) XXX_DiscardUnknown() {
	xxx_messageInfo_SysMenu.DiscardUnknown(m)
}

var xxx_messageInfo_SysMenu proto.InternalMessageInfo

func (m *SysMenu) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SysMenu) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SysMenu) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *SysMenu) GetI18N() string {
	if m != nil {
		return m.I18N
	}
	return ""
}

func (m *SysMenu) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *SysMenu) GetExternalLink() string {
	if m != nil {
		return m.ExternalLink
	}
	return ""
}

func (m *SysMenu) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *SysMenu) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *SysMenu) GetBadge() int32 {
	if m != nil {
		return m.Badge
	}
	return 0
}

func (m *SysMenu) GetBadgeDoc() string {
	if m != nil {
		return m.BadgeDoc
	}
	return ""
}

func (m *SysMenu) GetBadgeStatus() string {
	if m != nil {
		return m.BadgeStatus
	}
	return ""
}

func (m *SysMenu) GetAcl() string {
	if m != nil {
		return m.Acl
	}
	return ""
}

func (m *SysMenu) GetHide() bool {
	if m != nil {
		return m.Hide
	}
	return false
}

func (m *SysMenu) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *SysMenu) GetHideInBreadcrumb() bool {
	if m != nil {
		return m.HideInBreadcrumb
	}
	return false
}

func (m *SysMenu) GetShortcut() bool {
	if m != nil {
		return m.Shortcut
	}
	return false
}

func (m *SysMenu) GetShortcutRoot() bool {
	if m != nil {
		return m.ShortcutRoot
	}
	return false
}

func (m *SysMenu) GetReuse() bool {
	if m != nil {
		return m.Reuse
	}
	return false
}

func (m *SysMenu) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *SysMenu) GetPId() int64 {
	if m != nil {
		return m.PId
	}
	return 0
}

func (m *SysMenu) GetChildren() []*SysMenu {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *SysMenu) GetGroup() bool {
	if m != nil {
		return m.Group
	}
	return false
}

func (m *SysMenu) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *SysMenu) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type SysApi struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Service              string   `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	ApiExplain           string   `protobuf:"bytes,4,opt,name=api_explain,json=apiExplain,proto3" json:"api_explain,omitempty"`
	Created              int64    `protobuf:"varint,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SysApi) Reset()         { *m = SysApi{} }
func (m *SysApi) String() string { return proto.CompactTextString(m) }
func (*SysApi) ProtoMessage()    {}
func (*SysApi) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{6}
}

func (m *SysApi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysApi.Unmarshal(m, b)
}
func (m *SysApi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysApi.Marshal(b, m, deterministic)
}
func (m *SysApi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysApi.Merge(m, src)
}
func (m *SysApi) XXX_Size() int {
	return xxx_messageInfo_SysApi.Size(m)
}
func (m *SysApi) XXX_DiscardUnknown() {
	xxx_messageInfo_SysApi.DiscardUnknown(m)
}

var xxx_messageInfo_SysApi proto.InternalMessageInfo

func (m *SysApi) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SysApi) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *SysApi) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *SysApi) GetApiExplain() string {
	if m != nil {
		return m.ApiExplain
	}
	return ""
}

func (m *SysApi) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *SysApi) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type SysSrv struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Service              string   `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	SrvExplain           string   `protobuf:"bytes,4,opt,name=srv_explain,json=srvExplain,proto3" json:"srv_explain,omitempty"`
	Created              int64    `protobuf:"varint,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SysSrv) Reset()         { *m = SysSrv{} }
func (m *SysSrv) String() string { return proto.CompactTextString(m) }
func (*SysSrv) ProtoMessage()    {}
func (*SysSrv) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{7}
}

func (m *SysSrv) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysSrv.Unmarshal(m, b)
}
func (m *SysSrv) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysSrv.Marshal(b, m, deterministic)
}
func (m *SysSrv) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysSrv.Merge(m, src)
}
func (m *SysSrv) XXX_Size() int {
	return xxx_messageInfo_SysSrv.Size(m)
}
func (m *SysSrv) XXX_DiscardUnknown() {
	xxx_messageInfo_SysSrv.DiscardUnknown(m)
}

var xxx_messageInfo_SysSrv proto.InternalMessageInfo

func (m *SysSrv) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SysSrv) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *SysSrv) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *SysSrv) GetSrvExplain() string {
	if m != nil {
		return m.SrvExplain
	}
	return ""
}

func (m *SysSrv) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *SysSrv) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type LogisticsAddress struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IsDefault            bool     `protobuf:"varint,2,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	User                 *SysUser `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	ProvinceId           int64    `protobuf:"varint,12,opt,name=province_id,json=provinceId,proto3" json:"province_id,omitempty"`
	Province             *SysTree `protobuf:"bytes,13,opt,name=province,proto3" json:"province,omitempty"`
	CityId               int64    `protobuf:"varint,14,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	City                 *SysTree `protobuf:"bytes,15,opt,name=city,proto3" json:"city,omitempty"`
	AreaId               int64    `protobuf:"varint,16,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	Area                 *SysTree `protobuf:"bytes,17,opt,name=area,proto3" json:"area,omitempty"`
	Address              string   `protobuf:"bytes,18,opt,name=address,proto3" json:"address,omitempty"`
	Created              int64    `protobuf:"varint,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogisticsAddress) Reset()         { *m = LogisticsAddress{} }
func (m *LogisticsAddress) String() string { return proto.CompactTextString(m) }
func (*LogisticsAddress) ProtoMessage()    {}
func (*LogisticsAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{8}
}

func (m *LogisticsAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogisticsAddress.Unmarshal(m, b)
}
func (m *LogisticsAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogisticsAddress.Marshal(b, m, deterministic)
}
func (m *LogisticsAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogisticsAddress.Merge(m, src)
}
func (m *LogisticsAddress) XXX_Size() int {
	return xxx_messageInfo_LogisticsAddress.Size(m)
}
func (m *LogisticsAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_LogisticsAddress.DiscardUnknown(m)
}

var xxx_messageInfo_LogisticsAddress proto.InternalMessageInfo

func (m *LogisticsAddress) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LogisticsAddress) GetIsDefault() bool {
	if m != nil {
		return m.IsDefault
	}
	return false
}

func (m *LogisticsAddress) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LogisticsAddress) GetUser() *SysUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *LogisticsAddress) GetProvinceId() int64 {
	if m != nil {
		return m.ProvinceId
	}
	return 0
}

func (m *LogisticsAddress) GetProvince() *SysTree {
	if m != nil {
		return m.Province
	}
	return nil
}

func (m *LogisticsAddress) GetCityId() int64 {
	if m != nil {
		return m.CityId
	}
	return 0
}

func (m *LogisticsAddress) GetCity() *SysTree {
	if m != nil {
		return m.City
	}
	return nil
}

func (m *LogisticsAddress) GetAreaId() int64 {
	if m != nil {
		return m.AreaId
	}
	return 0
}

func (m *LogisticsAddress) GetArea() *SysTree {
	if m != nil {
		return m.Area
	}
	return nil
}

func (m *LogisticsAddress) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *LogisticsAddress) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *LogisticsAddress) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type Qualification struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IsDefault            bool                 `protobuf:"varint,2,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	UserId               int64                `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	User                 *SysUser             `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	QuaTypeId            int64                `protobuf:"varint,5,opt,name=qua_type_id,json=quaTypeId,proto3" json:"qua_type_id,omitempty"`
	QuaType              *SysTree             `protobuf:"bytes,6,opt,name=qua_type,json=quaType,proto3" json:"qua_type,omitempty"`
	QuaFileId            int64                `protobuf:"varint,7,opt,name=qua_file_id,json=quaFileId,proto3" json:"qua_file_id,omitempty"`
	QuaFile              *SysTree             `protobuf:"bytes,8,opt,name=qua_file,json=quaFile,proto3" json:"qua_file,omitempty"`
	QuaExplain           string               `protobuf:"bytes,9,opt,name=qua_explain,json=quaExplain,proto3" json:"qua_explain,omitempty"`
	QuaNumber            string               `protobuf:"bytes,10,opt,name=qua_number,json=quaNumber,proto3" json:"qua_number,omitempty"`
	StartTimes           *timestamp.Timestamp `protobuf:"bytes,11,opt,name=start_times,json=startTimes,proto3" json:"start_times,omitempty"`
	EndTimes             *timestamp.Timestamp `protobuf:"bytes,12,opt,name=end_times,json=endTimes,proto3" json:"end_times,omitempty"`
	Created              int64                `protobuf:"varint,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64                `protobuf:"varint,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Qualification) Reset()         { *m = Qualification{} }
func (m *Qualification) String() string { return proto.CompactTextString(m) }
func (*Qualification) ProtoMessage()    {}
func (*Qualification) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{9}
}

func (m *Qualification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Qualification.Unmarshal(m, b)
}
func (m *Qualification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Qualification.Marshal(b, m, deterministic)
}
func (m *Qualification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Qualification.Merge(m, src)
}
func (m *Qualification) XXX_Size() int {
	return xxx_messageInfo_Qualification.Size(m)
}
func (m *Qualification) XXX_DiscardUnknown() {
	xxx_messageInfo_Qualification.DiscardUnknown(m)
}

var xxx_messageInfo_Qualification proto.InternalMessageInfo

func (m *Qualification) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Qualification) GetIsDefault() bool {
	if m != nil {
		return m.IsDefault
	}
	return false
}

func (m *Qualification) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Qualification) GetUser() *SysUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Qualification) GetQuaTypeId() int64 {
	if m != nil {
		return m.QuaTypeId
	}
	return 0
}

func (m *Qualification) GetQuaType() *SysTree {
	if m != nil {
		return m.QuaType
	}
	return nil
}

func (m *Qualification) GetQuaFileId() int64 {
	if m != nil {
		return m.QuaFileId
	}
	return 0
}

func (m *Qualification) GetQuaFile() *SysTree {
	if m != nil {
		return m.QuaFile
	}
	return nil
}

func (m *Qualification) GetQuaExplain() string {
	if m != nil {
		return m.QuaExplain
	}
	return ""
}

func (m *Qualification) GetQuaNumber() string {
	if m != nil {
		return m.QuaNumber
	}
	return ""
}

func (m *Qualification) GetStartTimes() *timestamp.Timestamp {
	if m != nil {
		return m.StartTimes
	}
	return nil
}

func (m *Qualification) GetEndTimes() *timestamp.Timestamp {
	if m != nil {
		return m.EndTimes
	}
	return nil
}

func (m *Qualification) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Qualification) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type SysShop struct {
	Id                   int64      `protobuf:"varint,100,opt,name=id,proto3" json:"id,omitempty"`
	ShopName             string     `protobuf:"bytes,1,opt,name=shop_name,json=shopName,proto3" json:"shop_name,omitempty"`
	ShopExplain          string     `protobuf:"bytes,2,opt,name=shop_explain,json=shopExplain,proto3" json:"shop_explain,omitempty"`
	IsSht                bool       `protobuf:"varint,3,opt,name=is_sht,json=isSht,proto3" json:"is_sht,omitempty"`
	ShtExplain           string     `protobuf:"bytes,4,opt,name=sht_explain,json=shtExplain,proto3" json:"sht_explain,omitempty"`
	AppId                string     `protobuf:"bytes,5,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Appsecret            string     `protobuf:"bytes,6,opt,name=appsecret,proto3" json:"appsecret,omitempty"`
	Grade                float32    `protobuf:"fixed32,7,opt,name=grade,proto3" json:"grade,omitempty"`
	GradeWl              float32    `protobuf:"fixed32,8,opt,name=grade_wl,json=gradeWl,proto3" json:"grade_wl,omitempty"`
	GradeFw              float32    `protobuf:"fixed32,9,opt,name=grade_fw,json=gradeFw,proto3" json:"grade_fw,omitempty"`
	GradeMs              float32    `protobuf:"fixed32,10,opt,name=grade_ms,json=gradeMs,proto3" json:"grade_ms,omitempty"`
	Cash                 int32      `protobuf:"varint,11,opt,name=cash,proto3" json:"cash,omitempty"`
	Sort                 int32      `protobuf:"varint,12,opt,name=sort,proto3" json:"sort,omitempty"`
	Comments             int32      `protobuf:"varint,13,opt,name=comments,proto3" json:"comments,omitempty"`
	Vip                  int32      `protobuf:"varint,14,opt,name=vip,proto3" json:"vip,omitempty"`
	Point                float32    `protobuf:"fixed32,15,opt,name=point,proto3" json:"point,omitempty"`
	Logo                 *SysFile   `protobuf:"bytes,16,opt,name=logo,proto3" json:"logo,omitempty"`
	Classify             []*SysFile `protobuf:"bytes,17,rep,name=classify,proto3" json:"classify,omitempty"`
	User                 []*SysUser `protobuf:"bytes,18,rep,name=user,proto3" json:"user,omitempty"`
	Imgs                 []*SysFile `protobuf:"bytes,19,rep,name=imgs,proto3" json:"imgs,omitempty"`
	Created              int64      `protobuf:"varint,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64      `protobuf:"varint,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SysShop) Reset()         { *m = SysShop{} }
func (m *SysShop) String() string { return proto.CompactTextString(m) }
func (*SysShop) ProtoMessage()    {}
func (*SysShop) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{10}
}

func (m *SysShop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysShop.Unmarshal(m, b)
}
func (m *SysShop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysShop.Marshal(b, m, deterministic)
}
func (m *SysShop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysShop.Merge(m, src)
}
func (m *SysShop) XXX_Size() int {
	return xxx_messageInfo_SysShop.Size(m)
}
func (m *SysShop) XXX_DiscardUnknown() {
	xxx_messageInfo_SysShop.DiscardUnknown(m)
}

var xxx_messageInfo_SysShop proto.InternalMessageInfo

func (m *SysShop) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SysShop) GetShopName() string {
	if m != nil {
		return m.ShopName
	}
	return ""
}

func (m *SysShop) GetShopExplain() string {
	if m != nil {
		return m.ShopExplain
	}
	return ""
}

func (m *SysShop) GetIsSht() bool {
	if m != nil {
		return m.IsSht
	}
	return false
}

func (m *SysShop) GetShtExplain() string {
	if m != nil {
		return m.ShtExplain
	}
	return ""
}

func (m *SysShop) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *SysShop) GetAppsecret() string {
	if m != nil {
		return m.Appsecret
	}
	return ""
}

func (m *SysShop) GetGrade() float32 {
	if m != nil {
		return m.Grade
	}
	return 0
}

func (m *SysShop) GetGradeWl() float32 {
	if m != nil {
		return m.GradeWl
	}
	return 0
}

func (m *SysShop) GetGradeFw() float32 {
	if m != nil {
		return m.GradeFw
	}
	return 0
}

func (m *SysShop) GetGradeMs() float32 {
	if m != nil {
		return m.GradeMs
	}
	return 0
}

func (m *SysShop) GetCash() int32 {
	if m != nil {
		return m.Cash
	}
	return 0
}

func (m *SysShop) GetSort() int32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *SysShop) GetComments() int32 {
	if m != nil {
		return m.Comments
	}
	return 0
}

func (m *SysShop) GetVip() int32 {
	if m != nil {
		return m.Vip
	}
	return 0
}

func (m *SysShop) GetPoint() float32 {
	if m != nil {
		return m.Point
	}
	return 0
}

func (m *SysShop) GetLogo() *SysFile {
	if m != nil {
		return m.Logo
	}
	return nil
}

func (m *SysShop) GetClassify() []*SysFile {
	if m != nil {
		return m.Classify
	}
	return nil
}

func (m *SysShop) GetUser() []*SysUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *SysShop) GetImgs() []*SysFile {
	if m != nil {
		return m.Imgs
	}
	return nil
}

func (m *SysShop) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *SysShop) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type Product struct {
	Id                   int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GoodsCode            string      `protobuf:"bytes,2,opt,name=goods_code,json=goodsCode,proto3" json:"goods_code,omitempty"`
	GoodsByname          string      `protobuf:"bytes,3,opt,name=goods_byname,json=goodsByname,proto3" json:"goods_byname,omitempty"`
	Factory              string      `protobuf:"bytes,4,opt,name=factory,proto3" json:"factory,omitempty"`
	ProAddress           string      `protobuf:"bytes,5,opt,name=pro_address,json=proAddress,proto3" json:"pro_address,omitempty"`
	ApprovalNum          string      `protobuf:"bytes,6,opt,name=approval_num,json=approvalNum,proto3" json:"approval_num,omitempty"`
	Spec                 string      `protobuf:"bytes,7,opt,name=spec,proto3" json:"spec,omitempty"`
	DosageForm           string      `protobuf:"bytes,8,opt,name=dosage_form,json=dosageForm,proto3" json:"dosage_form,omitempty"`
	Unit                 string      `protobuf:"bytes,9,opt,name=unit,proto3" json:"unit,omitempty"`
	Opcode               string      `protobuf:"bytes,10,opt,name=opcode,proto3" json:"opcode,omitempty"`
	MpackTotal           float32     `protobuf:"fixed32,11,opt,name=mpack_total,json=mpackTotal,proto3" json:"mpack_total,omitempty"`
	PackTotal            float32     `protobuf:"fixed32,12,opt,name=pack_total,json=packTotal,proto3" json:"pack_total,omitempty"`
	IsUnbundled          bool        `protobuf:"varint,13,opt,name=is_unbundled,json=isUnbundled,proto3" json:"is_unbundled,omitempty"`
	IsStop               bool        `protobuf:"varint,14,opt,name=is_stop,json=isStop,proto3" json:"is_stop,omitempty"`
	GoodsExplain         string      `protobuf:"bytes,15,opt,name=goods_explain,json=goodsExplain,proto3" json:"goods_explain,omitempty"`
	Shop                 *SysShop    `protobuf:"bytes,16,opt,name=shop,proto3" json:"shop,omitempty"`
	Imgs                 *SysFile    `protobuf:"bytes,17,opt,name=imgs,proto3" json:"imgs,omitempty"`
	ProductSkus          *ProductSku `protobuf:"bytes,18,opt,name=product_skus,json=productSkus,proto3" json:"product_skus,omitempty"`
	Created              int64       `protobuf:"varint,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64       `protobuf:"varint,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{11}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetGoodsCode() string {
	if m != nil {
		return m.GoodsCode
	}
	return ""
}

func (m *Product) GetGoodsByname() string {
	if m != nil {
		return m.GoodsByname
	}
	return ""
}

func (m *Product) GetFactory() string {
	if m != nil {
		return m.Factory
	}
	return ""
}

func (m *Product) GetProAddress() string {
	if m != nil {
		return m.ProAddress
	}
	return ""
}

func (m *Product) GetApprovalNum() string {
	if m != nil {
		return m.ApprovalNum
	}
	return ""
}

func (m *Product) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

func (m *Product) GetDosageForm() string {
	if m != nil {
		return m.DosageForm
	}
	return ""
}

func (m *Product) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *Product) GetOpcode() string {
	if m != nil {
		return m.Opcode
	}
	return ""
}

func (m *Product) GetMpackTotal() float32 {
	if m != nil {
		return m.MpackTotal
	}
	return 0
}

func (m *Product) GetPackTotal() float32 {
	if m != nil {
		return m.PackTotal
	}
	return 0
}

func (m *Product) GetIsUnbundled() bool {
	if m != nil {
		return m.IsUnbundled
	}
	return false
}

func (m *Product) GetIsStop() bool {
	if m != nil {
		return m.IsStop
	}
	return false
}

func (m *Product) GetGoodsExplain() string {
	if m != nil {
		return m.GoodsExplain
	}
	return ""
}

func (m *Product) GetShop() *SysShop {
	if m != nil {
		return m.Shop
	}
	return nil
}

func (m *Product) GetImgs() *SysFile {
	if m != nil {
		return m.Imgs
	}
	return nil
}

func (m *Product) GetProductSkus() *ProductSku {
	if m != nil {
		return m.ProductSkus
	}
	return nil
}

func (m *Product) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Product) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type ProductSku struct {
	Id      int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SkuName string `protobuf:"bytes,2,opt,name=sku_name,json=skuName,proto3" json:"sku_name,omitempty"`
	//Attributes: datatypes.JSON([]byte(`{"name": "jinzhu", "age": 18, "tags": ["tag1", "tag2"], "orgs": {"orga": "orga"}}`)),
	AttriListBt          []byte   `protobuf:"bytes,3,opt,name=attri_list_bt,json=attriListBt,proto3" json:"attri_list_bt,omitempty"`
	Point                float32  `protobuf:"fixed32,4,opt,name=point,proto3" json:"point,omitempty"`
	SellPrice            float32  `protobuf:"fixed32,5,opt,name=sell_price,json=sellPrice,proto3" json:"sell_price,omitempty"`
	MarketPrice          float32  `protobuf:"fixed32,6,opt,name=market_price,json=marketPrice,proto3" json:"market_price,omitempty"`
	SalePrice            float32  `protobuf:"fixed32,7,opt,name=sale_price,json=salePrice,proto3" json:"sale_price,omitempty"`
	SalePriceErp         float32  `protobuf:"fixed32,8,opt,name=sale_price_erp,json=salePriceErp,proto3" json:"sale_price_erp,omitempty"`
	Stock                float32  `protobuf:"fixed32,9,opt,name=stock,proto3" json:"stock,omitempty"`
	IsChecked            bool     `protobuf:"varint,10,opt,name=is_checked,json=isChecked,proto3" json:"is_checked,omitempty"`
	Goods                *Product `protobuf:"bytes,11,opt,name=goods,proto3" json:"goods,omitempty"`
	Created              int64    `protobuf:"varint,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductSku) Reset()         { *m = ProductSku{} }
func (m *ProductSku) String() string { return proto.CompactTextString(m) }
func (*ProductSku) ProtoMessage()    {}
func (*ProductSku) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{12}
}

func (m *ProductSku) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductSku.Unmarshal(m, b)
}
func (m *ProductSku) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductSku.Marshal(b, m, deterministic)
}
func (m *ProductSku) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductSku.Merge(m, src)
}
func (m *ProductSku) XXX_Size() int {
	return xxx_messageInfo_ProductSku.Size(m)
}
func (m *ProductSku) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductSku.DiscardUnknown(m)
}

var xxx_messageInfo_ProductSku proto.InternalMessageInfo

func (m *ProductSku) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductSku) GetSkuName() string {
	if m != nil {
		return m.SkuName
	}
	return ""
}

func (m *ProductSku) GetAttriListBt() []byte {
	if m != nil {
		return m.AttriListBt
	}
	return nil
}

func (m *ProductSku) GetPoint() float32 {
	if m != nil {
		return m.Point
	}
	return 0
}

func (m *ProductSku) GetSellPrice() float32 {
	if m != nil {
		return m.SellPrice
	}
	return 0
}

func (m *ProductSku) GetMarketPrice() float32 {
	if m != nil {
		return m.MarketPrice
	}
	return 0
}

func (m *ProductSku) GetSalePrice() float32 {
	if m != nil {
		return m.SalePrice
	}
	return 0
}

func (m *ProductSku) GetSalePriceErp() float32 {
	if m != nil {
		return m.SalePriceErp
	}
	return 0
}

func (m *ProductSku) GetStock() float32 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *ProductSku) GetIsChecked() bool {
	if m != nil {
		return m.IsChecked
	}
	return false
}

func (m *ProductSku) GetGoods() *Product {
	if m != nil {
		return m.Goods
	}
	return nil
}

func (m *ProductSku) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *ProductSku) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type Orders struct {
	Id                   int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNumber          string       `protobuf:"bytes,2,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	SerialNumber         string       `protobuf:"bytes,3,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	OrderItems           []*OrderItem `protobuf:"bytes,4,rep,name=order_items,json=orderItems,proto3" json:"order_items,omitempty"`
	Created              int64        `protobuf:"varint,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64        `protobuf:"varint,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Orders) Reset()         { *m = Orders{} }
func (m *Orders) String() string { return proto.CompactTextString(m) }
func (*Orders) ProtoMessage()    {}
func (*Orders) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{13}
}

func (m *Orders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Orders.Unmarshal(m, b)
}
func (m *Orders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Orders.Marshal(b, m, deterministic)
}
func (m *Orders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Orders.Merge(m, src)
}
func (m *Orders) XXX_Size() int {
	return xxx_messageInfo_Orders.Size(m)
}
func (m *Orders) XXX_DiscardUnknown() {
	xxx_messageInfo_Orders.DiscardUnknown(m)
}

var xxx_messageInfo_Orders proto.InternalMessageInfo

func (m *Orders) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Orders) GetOrderNumber() string {
	if m != nil {
		return m.OrderNumber
	}
	return ""
}

func (m *Orders) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *Orders) GetOrderItems() []*OrderItem {
	if m != nil {
		return m.OrderItems
	}
	return nil
}

func (m *Orders) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Orders) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type OrderItem struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GoodsSkuId           int64    `protobuf:"varint,2,opt,name=goods_sku_id,json=goodsSkuId,proto3" json:"goods_sku_id,omitempty"`
	OrderId              int64    `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Orders               *Orders  `protobuf:"bytes,4,opt,name=orders,proto3" json:"orders,omitempty"`
	UnitPrice            float32  `protobuf:"fixed32,5,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	PayUnitPrice         float32  `protobuf:"fixed32,6,opt,name=pay_unit_price,json=payUnitPrice,proto3" json:"pay_unit_price,omitempty"`
	Quantity             float32  `protobuf:"fixed32,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	SendQuantity         float32  `protobuf:"fixed32,8,opt,name=send_quantity,json=sendQuantity,proto3" json:"send_quantity,omitempty"`
	TotalPrice           float32  `protobuf:"fixed32,9,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Created              int64    `protobuf:"varint,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderItem) Reset()         { *m = OrderItem{} }
func (m *OrderItem) String() string { return proto.CompactTextString(m) }
func (*OrderItem) ProtoMessage()    {}
func (*OrderItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{14}
}

func (m *OrderItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderItem.Unmarshal(m, b)
}
func (m *OrderItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderItem.Marshal(b, m, deterministic)
}
func (m *OrderItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderItem.Merge(m, src)
}
func (m *OrderItem) XXX_Size() int {
	return xxx_messageInfo_OrderItem.Size(m)
}
func (m *OrderItem) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderItem.DiscardUnknown(m)
}

var xxx_messageInfo_OrderItem proto.InternalMessageInfo

func (m *OrderItem) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OrderItem) GetGoodsSkuId() int64 {
	if m != nil {
		return m.GoodsSkuId
	}
	return 0
}

func (m *OrderItem) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *OrderItem) GetOrders() *Orders {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *OrderItem) GetUnitPrice() float32 {
	if m != nil {
		return m.UnitPrice
	}
	return 0
}

func (m *OrderItem) GetPayUnitPrice() float32 {
	if m != nil {
		return m.PayUnitPrice
	}
	return 0
}

func (m *OrderItem) GetQuantity() float32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *OrderItem) GetSendQuantity() float32 {
	if m != nil {
		return m.SendQuantity
	}
	return 0
}

func (m *OrderItem) GetTotalPrice() float32 {
	if m != nil {
		return m.TotalPrice
	}
	return 0
}

func (m *OrderItem) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *OrderItem) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func init() {
	proto.RegisterEnum("dbmodel.LoginType", LoginType_name, LoginType_value)
	proto.RegisterEnum("dbmodel.UserType", UserType_name, UserType_value)
	proto.RegisterEnum("dbmodel.FileType", FileType_name, FileType_value)
	proto.RegisterType((*SysUser)(nil), "dbmodel.SysUser")
	proto.RegisterType((*SysFile)(nil), "dbmodel.SysFile")
	proto.RegisterType((*SysTree)(nil), "dbmodel.SysTree")
	proto.RegisterType((*SysGroup)(nil), "dbmodel.SysGroup")
	proto.RegisterType((*SysRole)(nil), "dbmodel.SysRole")
	proto.RegisterType((*SysMenu)(nil), "dbmodel.SysMenu")
	proto.RegisterType((*SysApi)(nil), "dbmodel.SysApi")
	proto.RegisterType((*SysSrv)(nil), "dbmodel.SysSrv")
	proto.RegisterType((*LogisticsAddress)(nil), "dbmodel.LogisticsAddress")
	proto.RegisterType((*Qualification)(nil), "dbmodel.Qualification")
	proto.RegisterType((*SysShop)(nil), "dbmodel.SysShop")
	proto.RegisterType((*Product)(nil), "dbmodel.Product")
	proto.RegisterType((*ProductSku)(nil), "dbmodel.ProductSku")
	proto.RegisterType((*Orders)(nil), "dbmodel.Orders")
	proto.RegisterType((*OrderItem)(nil), "dbmodel.OrderItem")
}

func init() { proto.RegisterFile("proto/dbmodel/dbmodel.proto", fileDescriptor_e330dd2b497970ae) }

var fileDescriptor_e330dd2b497970ae = []byte{
	// 2315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x58, 0xcd, 0x6e, 0x1b, 0xc9,
	0x11, 0x36, 0xc5, 0xbf, 0x61, 0x91, 0x96, 0xa8, 0xb1, 0x77, 0x77, 0x2c, 0xaf, 0xd7, 0x92, 0xd7,
	0xd8, 0x38, 0xde, 0x40, 0x46, 0xbc, 0x40, 0x12, 0x60, 0x81, 0x00, 0xb2, 0x2d, 0xdb, 0x02, 0xf4,
	0xe7, 0xa6, 0x84, 0xcd, 0x6d, 0xd0, 0x9c, 0x69, 0x89, 0x0d, 0x0e, 0x67, 0x46, 0xd3, 0x3d, 0xb2,
	0x94, 0x5b, 0x8e, 0x39, 0xe6, 0x9c, 0x43, 0x2e, 0x79, 0x99, 0xe4, 0x19, 0x72, 0xca, 0x29, 0x97,
	0x5c, 0x92, 0x17, 0x08, 0xaa, 0xba, 0x7b, 0x48, 0x89, 0x52, 0x02, 0xd0, 0x41, 0x2e, 0x39, 0xb1,
	0xeb, 0xab, 0xea, 0x66, 0x77, 0xfd, 0xd7, 0xc0, 0xc3, 0xbc, 0xc8, 0x74, 0xf6, 0x22, 0x1e, 0x4e,
	0xb2, 0x58, 0x24, 0xee, 0x77, 0x93, 0x50, 0xbf, 0x6d, 0xc9, 0xb5, 0xc7, 0xa7, 0x59, 0x76, 0x9a,
	0x88, 0x17, 0x04, 0x0f, 0xcb, 0x93, 0x17, 0x5a, 0x4e, 0x84, 0xd2, 0x7c, 0x92, 0x1b, 0xc9, 0x27,
	0x7f, 0xf4, 0xa0, 0x3d, 0xb8, 0x54, 0xc7, 0x4a, 0x14, 0xfe, 0x32, 0x2c, 0xc9, 0x38, 0xa8, 0xad,
	0xd7, 0x9e, 0xd5, 0xd9, 0x92, 0x8c, 0xfd, 0x87, 0xd0, 0x29, 0x95, 0x28, 0xc2, 0x94, 0x4f, 0x44,
	0xb0, 0xb4, 0x5e, 0x7b, 0xd6, 0x61, 0x1e, 0x02, 0xfb, 0x7c, 0x22, 0x90, 0xa9, 0x8b, 0x52, 0x18,
	0x66, 0xdd, 0x30, 0x11, 0x20, 0xe6, 0x23, 0x00, 0xda, 0x99, 0x8f, 0xb2, 0x54, 0x04, 0x0d, 0xe2,
	0xd2, 0x59, 0x87, 0x08, 0xf8, 0x5f, 0x40, 0x9b, 0xd8, 0x1f, 0x2f, 0x82, 0x26, 0xf1, 0x5a, 0x48,
	0xfe, 0x70, 0x51, 0xed, 0x13, 0x13, 0x2e, 0x93, 0xa0, 0x35, 0xdd, 0xb7, 0x8d, 0x40, 0xb5, 0xef,
	0xec, 0x2c, 0x68, 0x4f, 0xf7, 0x7d, 0x38, 0xf3, 0x1f, 0x00, 0x5d, 0x2c, 0xd4, 0x22, 0x09, 0x3c,
	0xe2, 0x90, 0xe0, 0x91, 0x48, 0xfc, 0x00, 0xda, 0x43, 0x9e, 0xf0, 0x34, 0x12, 0x41, 0xc7, 0x70,
	0x2c, 0x89, 0xa7, 0xc9, 0x38, 0x8c, 0x78, 0x11, 0x07, 0x60, 0x4e, 0x93, 0xf1, 0x6b, 0x5e, 0xc4,
	0xfe, 0x7d, 0x68, 0xe6, 0x99, 0x4c, 0x75, 0xd0, 0x25, 0x55, 0x18, 0xc2, 0x7f, 0x0c, 0xdd, 0xbc,
	0xc8, 0xce, 0x65, 0x1a, 0x89, 0x50, 0xc6, 0x41, 0x8f, 0x78, 0xe0, 0xa0, 0x9d, 0xd8, 0xff, 0x09,
	0x78, 0x8e, 0x0a, 0xee, 0xae, 0xd7, 0x9e, 0x75, 0x5f, 0xf6, 0x37, 0x9d, 0x59, 0x06, 0x97, 0xea,
	0xa8, 0x10, 0x82, 0x55, 0x12, 0xf8, 0xef, 0x91, 0xd4, 0x97, 0x78, 0xd4, 0x32, 0x1d, 0xd5, 0x42,
	0x72, 0x27, 0xf6, 0x9f, 0x42, 0x03, 0x57, 0xc1, 0xca, 0x2d, 0x47, 0x10, 0x17, 0xb7, 0xf3, 0x42,
	0x70, 0xdc, 0xde, 0x37, 0xdb, 0x91, 0x34, 0xdb, 0x71, 0x15, 0xac, 0xde, 0xb6, 0x1d, 0xb9, 0xa8,
	0x15, 0x1e, 0xc7, 0x85, 0x50, 0x2a, 0xf0, 0x8d, 0x56, 0x2c, 0xe9, 0xf7, 0xa1, 0x7e, 0x2e, 0xf3,
	0xe0, 0xde, 0x7a, 0xed, 0x59, 0x93, 0xe1, 0x12, 0x2d, 0x3d, 0xe4, 0xe9, 0xd8, 0x58, 0xfa, 0xbe,
	0xb1, 0x34, 0x02, 0x64, 0xe9, 0xc7, 0xd0, 0x1d, 0x16, 0x3c, 0x8d, 0x46, 0x86, 0xfd, 0x19, 0xb1,
	0xc1, 0x40, 0x24, 0xb0, 0x06, 0x24, 0x4c, 0x6a, 0xfe, 0x7c, 0xba, 0x19, 0x69, 0xff, 0x29, 0x2c,
	0xd3, 0xc9, 0x48, 0x98, 0xfd, 0x5f, 0x90, 0x44, 0x0f, 0x51, 0x34, 0x85, 0xf3, 0x34, 0x32, 0xae,
	0x8c, 0xb2, 0x34, 0x08, 0xe8, 0xb1, 0x64, 0xed, 0x9d, 0x28, 0x4b, 0xf1, 0xb9, 0x84, 0x3f, 0x98,
	0x7f, 0xee, 0x5b, 0x99, 0x08, 0x46, 0x5c, 0xff, 0x1b, 0x68, 0x16, 0x59, 0x22, 0x54, 0xb0, 0xb6,
	0x5e, 0xbf, 0x2e, 0xc6, 0xb2, 0x44, 0x30, 0xc3, 0xf6, 0x7f, 0x0c, 0xad, 0xd3, 0x22, 0x2b, 0x73,
	0x15, 0x3c, 0x24, 0xc1, 0xd5, 0x59, 0xc1, 0x77, 0xc8, 0x61, 0x56, 0xc0, 0x7f, 0x0f, 0x7e, 0x92,
	0x9d, 0x4a, 0xa5, 0x65, 0xa4, 0x42, 0xab, 0x3c, 0x15, 0x7c, 0x49, 0xdb, 0x1e, 0x54, 0xdb, 0x76,
	0x9d, 0xc8, 0x96, 0x91, 0x60, 0xab, 0xc9, 0x35, 0x44, 0xf9, 0xbf, 0x84, 0xe5, 0xb3, 0x92, 0x27,
	0xf2, 0x44, 0x46, 0x5c, 0xcb, 0x2c, 0x55, 0xc1, 0x23, 0x3a, 0xe5, 0xf3, 0xea, 0x94, 0x0f, 0xb3,
	0x6c, 0x76, 0x4d, 0xda, 0xdf, 0xb4, 0xfa, 0xd1, 0x97, 0xb9, 0x08, 0xbe, 0x5a, 0xaf, 0x3d, 0x5b,
	0x9e, 0xb9, 0x37, 0x06, 0xf6, 0xd1, 0x65, 0x2e, 0x8c, 0xca, 0x70, 0x85, 0xb6, 0x8f, 0x0a, 0xc1,
	0xb5, 0x88, 0x83, 0x21, 0x69, 0xd3, 0x91, 0xc8, 0x29, 0xf3, 0x98, 0x38, 0x91, 0xe1, 0x58, 0xf2,
	0xc9, 0xef, 0x96, 0x28, 0x4d, 0xa0, 0x4a, 0xe7, 0xd2, 0x84, 0x0f, 0x8d, 0x99, 0x0c, 0x41, 0x6b,
	0xc4, 0x72, 0xae, 0x47, 0x36, 0x31, 0xd0, 0x1a, 0x31, 0x25, 0x7f, 0x6d, 0xd2, 0x41, 0x9d, 0xd1,
	0xda, 0xdf, 0x80, 0xde, 0x89, 0x4c, 0x44, 0x28, 0x2e, 0xf2, 0x84, 0xcb, 0xd4, 0xa6, 0x83, 0x2e,
	0x62, 0xdb, 0x06, 0xa2, 0x6d, 0x59, 0xa1, 0x29, 0x1b, 0x34, 0x19, 0xad, 0xf1, 0xc9, 0xb4, 0x8d,
	0x9e, 0xdc, 0xbe, 0xf6, 0x64, 0xbc, 0xa4, 0x79, 0xf2, 0x89, 0x5d, 0xa1, 0x97, 0x92, 0xbc, 0x2a,
	0x4f, 0x4e, 0xe4, 0x85, 0x4d, 0x11, 0x80, 0xd0, 0x80, 0x90, 0x85, 0x74, 0xf2, 0xe7, 0x1a, 0xe9,
	0x04, 0xa3, 0xea, 0x26, 0x9d, 0x44, 0x59, 0x5c, 0xe9, 0x04, 0xd7, 0x88, 0x69, 0x71, 0xa1, 0x9d,
	0x4e, 0x70, 0x5d, 0x3d, 0xae, 0x31, 0xf3, 0xb8, 0x55, 0x68, 0xe4, 0x18, 0xd7, 0x4d, 0x3a, 0xad,
	0x9e, 0x9b, 0xd4, 0x12, 0x8d, 0x64, 0x12, 0x17, 0x22, 0x0d, 0x5a, 0xf3, 0x2e, 0x6c, 0x52, 0x8b,
	0x93, 0x58, 0xe8, 0x31, 0x7f, 0xad, 0x81, 0xe7, 0x7c, 0x7c, 0xee, 0x35, 0x8f, 0x00, 0xc8, 0xeb,
	0x67, 0x2b, 0x41, 0x87, 0x10, 0x0a, 0xd0, 0xaf, 0xe1, 0xae, 0x61, 0x3b, 0x2b, 0x9a, 0x17, 0xf6,
	0x08, 0x74, 0x66, 0xac, 0x42, 0xb0, 0xf1, 0xef, 0x43, 0xf0, 0x1b, 0x68, 0xa2, 0xa7, 0xaa, 0xa0,
	0x79, 0x9b, 0x1c, 0xb1, 0x17, 0x7a, 0xe4, 0xdf, 0x8c, 0x17, 0xe3, 0x31, 0x37, 0x15, 0x3b, 0xbc,
	0xc0, 0x95, 0x62, 0x87, 0x00, 0xbd, 0x70, 0x03, 0x7a, 0xc4, 0xbc, 0xfa, 0xc0, 0x2e, 0x62, 0x33,
	0xef, 0x9b, 0x88, 0xb4, 0xbc, 0xf1, 0x7d, 0x7b, 0x22, 0x2d, 0x99, 0x61, 0xfb, 0x5f, 0x43, 0x43,
	0x15, 0xe7, 0xee, 0x79, 0x2b, 0xb3, 0x62, 0x83, 0xe2, 0x9c, 0x11, 0x13, 0x85, 0x78, 0x2e, 0x95,
	0xb5, 0xf5, 0x15, 0xa1, 0xad, 0x5c, 0x32, 0x62, 0x4e, 0x35, 0xd5, 0x9e, 0xff, 0x47, 0x0c, 0x7b,
	0xa7, 0x29, 0xe7, 0x4f, 0xde, 0xcd, 0xfe, 0xd4, 0xb9, 0x45, 0xcf, 0x9f, 0xe6, 0x4f, 0xff, 0x68,
	0x90, 0xaa, 0xf1, 0xe5, 0x73, 0xaa, 0xee, 0x43, 0x7d, 0x2c, 0x2e, 0xad, 0x92, 0x71, 0x79, 0x5b,
	0x68, 0xc8, 0x9f, 0xfe, 0x22, 0xb5, 0xdd, 0x03, 0xad, 0x11, 0x4b, 0x64, 0x3a, 0xb6, 0x69, 0x82,
	0xd6, 0xe8, 0x7d, 0xe2, 0x42, 0x8b, 0x22, 0xe5, 0x49, 0x48, 0x4c, 0xd3, 0x36, 0xf4, 0x1c, 0xb8,
	0x8b, 0x42, 0x9f, 0x43, 0x4b, 0xf3, 0xe2, 0x54, 0x68, 0xd7, 0x38, 0x18, 0xaa, 0x8a, 0x3f, 0x93,
	0x11, 0x4c, 0xfc, 0xdd, 0x87, 0xe6, 0x90, 0xc7, 0xa7, 0xa6, 0x5f, 0x68, 0x32, 0x43, 0x98, 0x2a,
	0x18, 0x9f, 0x8a, 0x30, 0xce, 0x22, 0xdb, 0x2f, 0x78, 0x04, 0xbc, 0xc9, 0x22, 0xf4, 0x0f, 0xc3,
	0x54, 0x9a, 0xeb, 0x52, 0x51, 0xe3, 0xd0, 0x61, 0x5d, 0xc2, 0x06, 0x04, 0xe1, 0xa3, 0x79, 0x94,
	0x50, 0xdb, 0xd0, 0x61, 0xb8, 0xc4, 0xff, 0x1e, 0xc9, 0xd8, 0xf4, 0x0a, 0x1e, 0xa3, 0x35, 0x56,
	0xcb, 0x58, 0x2a, 0x3e, 0x4c, 0x84, 0x69, 0x0b, 0x3c, 0x56, 0xd1, 0xfe, 0x73, 0xe8, 0xa3, 0xcc,
	0x4e, 0xfa, 0xaa, 0x10, 0x3c, 0x8e, 0x8a, 0x72, 0x32, 0xa4, 0x26, 0xc1, 0x63, 0x73, 0x38, 0x9e,
	0xa3, 0x46, 0x59, 0xa1, 0xa3, 0x52, 0x53, 0x7f, 0xe0, 0xb1, 0x8a, 0x46, 0x85, 0xb9, 0x75, 0x58,
	0x64, 0x99, 0xa6, 0x56, 0xc1, 0x63, 0x3d, 0x07, 0xb2, 0x2c, 0x23, 0x25, 0x14, 0xa2, 0x54, 0x82,
	0xda, 0x03, 0x8f, 0x19, 0x82, 0x6c, 0x82, 0xd5, 0xf6, 0x9e, 0xb5, 0x09, 0xd6, 0x56, 0xe7, 0x5e,
	0xf7, 0x6f, 0x76, 0xaf, 0xcf, 0x6e, 0x09, 0x87, 0xa9, 0x7b, 0xdd, 0x87, 0x26, 0x65, 0x0a, 0x6a,
	0x0f, 0x3c, 0x66, 0x88, 0x85, 0x9c, 0xee, 0x0f, 0x35, 0x68, 0x99, 0x10, 0x99, 0xf3, 0xb9, 0x00,
	0xda, 0x4a, 0x14, 0xe7, 0x32, 0x72, 0xc1, 0xed, 0x48, 0x74, 0x8d, 0x89, 0xd0, 0xa3, 0x2c, 0xb6,
	0xde, 0x67, 0x29, 0xac, 0x19, 0x3c, 0x97, 0x55, 0xc8, 0x1b, 0x37, 0x04, 0x9e, 0x4b, 0x17, 0xf1,
	0x9f, 0x70, 0xc3, 0x41, 0x71, 0xfe, 0xdf, 0xb9, 0xa1, 0x2a, 0xce, 0xaf, 0xdf, 0x50, 0x15, 0xe7,
	0x9f, 0x72, 0xc3, 0xdf, 0xd7, 0xa1, 0x7f, 0xbd, 0x6b, 0xb9, 0xa9, 0x20, 0x48, 0x15, 0xc6, 0xe2,
	0x84, 0x97, 0x89, 0xa6, 0xeb, 0x7a, 0xac, 0x23, 0xd5, 0x1b, 0x03, 0x54, 0x7d, 0xba, 0x34, 0x37,
	0xae, 0x9b, 0x3e, 0xdd, 0x34, 0xa7, 0xb8, 0xa2, 0xab, 0xde, 0x94, 0xb1, 0x88, 0xfb, 0xff, 0xd2,
	0x69, 0x2f, 0x62, 0x9d, 0xdf, 0x34, 0xe0, 0xee, 0x95, 0x6e, 0xf0, 0x7f, 0x6c, 0x9a, 0xaf, 0xa0,
	0x7b, 0x56, 0x72, 0xea, 0xbb, 0xa6, 0x2d, 0x4a, 0xe7, 0xac, 0xe4, 0xd8, 0x66, 0xed, 0xc4, 0xfe,
	0xb7, 0xe0, 0x39, 0x3e, 0xe5, 0xe1, 0x9b, 0xf4, 0xd2, 0xb6, 0xe2, 0xee, 0x30, 0xea, 0xcc, 0x64,
	0x4c, 0x99, 0xd9, 0x1c, 0x86, 0x1d, 0xdc, 0xf4, 0x30, 0xe4, 0x53, 0x82, 0xbe, 0xed, 0x30, 0xea,
	0x4a, 0x1f, 0x9b, 0xc3, 0x5c, 0x30, 0x98, 0x59, 0x0f, 0xce, 0x4a, 0xee, 0x82, 0xe1, 0x11, 0x20,
	0x15, 0xa6, 0xe5, 0x64, 0x28, 0x0a, 0x9b, 0xc1, 0xf1, 0xcf, 0xf6, 0x09, 0xf0, 0xbf, 0x87, 0xae,
	0xd2, 0xbc, 0xd0, 0x21, 0x4d, 0xc8, 0x94, 0xc1, 0xbb, 0x2f, 0xd7, 0x36, 0xcd, 0xfc, 0xbc, 0xe9,
	0xe6, 0xe7, 0xcd, 0x23, 0x37, 0x3f, 0x33, 0x20, 0x71, 0xa2, 0xfd, 0x9f, 0x43, 0x47, 0xa4, 0xb1,
	0xdd, 0xda, 0xfb, 0x8f, 0x5b, 0x3d, 0x91, 0xc6, 0x66, 0xe3, 0x22, 0x3e, 0xf0, 0x77, 0x53, 0x5a,
	0x07, 0xa3, 0xcc, 0x75, 0x6a, 0xf1, 0x6c, 0x17, 0xa3, 0x46, 0x99, 0x6d, 0xd4, 0x6a, 0xa6, 0x4a,
	0x21, 0xe0, 0xba, 0x18, 0x62, 0x3a, 0x1d, 0x99, 0x34, 0xd3, 0x45, 0xcc, 0x29, 0xe9, 0x33, 0x68,
	0x49, 0x15, 0xaa, 0x91, 0x29, 0xc5, 0x1e, 0x6b, 0x4a, 0x35, 0x18, 0xd1, 0xec, 0xab, 0x46, 0x7a,
	0x2e, 0xd3, 0x8c, 0xf4, 0xcc, 0x3e, 0x9e, 0x57, 0x5d, 0x6b, 0x87, 0x35, 0x79, 0x8e, 0x85, 0xe0,
	0x4b, 0xe8, 0xf0, 0x3c, 0x57, 0x22, 0x2a, 0x84, 0x76, 0xe3, 0x7c, 0x05, 0x98, 0xc4, 0xcf, 0x63,
	0xd3, 0xc1, 0x2f, 0x31, 0x43, 0xe0, 0x2c, 0x4f, 0x8b, 0xf0, 0xa3, 0x99, 0xe5, 0x97, 0x58, 0x9b,
	0xe8, 0x1f, 0x92, 0x29, 0xeb, 0xe4, 0x23, 0x19, 0xd8, 0xb1, 0xde, 0x7e, 0x9c, 0xb2, 0x26, 0x8a,
	0x6c, 0xeb, 0x58, 0x7b, 0x8a, 0x7a, 0x71, 0xae, 0x46, 0x64, 0xd2, 0x26, 0xa3, 0x75, 0x55, 0xf7,
	0x7b, 0x33, 0x7d, 0xf7, 0x1a, 0x78, 0x51, 0x36, 0x99, 0x88, 0x54, 0x2b, 0xca, 0x2a, 0x4d, 0x56,
	0xd1, 0x6e, 0x2a, 0x5e, 0x9e, 0x4e, 0xc5, 0xd5, 0x47, 0x82, 0x15, 0x73, 0x79, 0xf3, 0x91, 0xe0,
	0x29, 0x34, 0x92, 0xec, 0x34, 0xa3, 0x4c, 0x71, 0xe3, 0x38, 0x8a, 0x5c, 0xaa, 0x8f, 0x09, 0x57,
	0x4a, 0x9e, 0x5c, 0x06, 0xab, 0xf3, 0xf5, 0x91, 0x24, 0x2b, 0x89, 0x2a, 0x32, 0xfd, 0x5b, 0xda,
	0x3c, 0x13, 0x99, 0x38, 0x08, 0x4f, 0x4e, 0x55, 0x70, 0xef, 0x96, 0xf3, 0x88, 0xbb, 0x90, 0xbf,
	0xfd, 0xb3, 0x01, 0xed, 0xc3, 0x22, 0x8b, 0xcb, 0x48, 0xdf, 0x38, 0x19, 0x64, 0x59, 0xac, 0xc2,
	0x99, 0x69, 0xa7, 0x43, 0xc8, 0x6b, 0x1c, 0x79, 0x36, 0xa0, 0x67, 0xd8, 0xc3, 0xcb, 0x99, 0xef,
	0x44, 0x5d, 0xc2, 0x5e, 0x11, 0x84, 0xff, 0x7b, 0xc2, 0x23, 0x9d, 0x15, 0x97, 0xd6, 0xad, 0x1c,
	0x69, 0xcb, 0x80, 0x9b, 0xad, 0xad, 0x63, 0x61, 0x19, 0x70, 0x55, 0x69, 0x03, 0x7a, 0x3c, 0xc7,
	0x34, 0xcf, 0x13, 0x0c, 0x6b, 0xeb, 0x60, 0x5d, 0x87, 0xed, 0x97, 0x13, 0xb2, 0x73, 0x2e, 0x22,
	0xdb, 0xf5, 0xd1, 0x1a, 0xcf, 0x8d, 0x33, 0xc5, 0x4f, 0x45, 0x78, 0x92, 0x15, 0x13, 0x37, 0x0c,
	0x1a, 0xe8, 0x6d, 0x56, 0xd0, 0xa6, 0x32, 0x95, 0xda, 0xe6, 0x10, 0x5a, 0x63, 0x0d, 0xce, 0x72,
	0x7a, 0xa4, 0xfd, 0x56, 0x64, 0x28, 0x3c, 0x6c, 0x92, 0xf3, 0x68, 0x1c, 0xea, 0x4c, 0xf3, 0x84,
	0x7c, 0x6c, 0x89, 0x01, 0x41, 0x47, 0x88, 0xa0, 0x86, 0x66, 0xf8, 0x3d, 0xe2, 0x77, 0xa6, 0xec,
	0x0d, 0xe8, 0x49, 0x15, 0x96, 0xe9, 0xb0, 0x4c, 0x63, 0x6c, 0xfa, 0x4c, 0x33, 0xd8, 0x95, 0xea,
	0xd8, 0x41, 0xf4, 0x9d, 0x4a, 0x85, 0x4a, 0x67, 0xb9, 0x6d, 0x09, 0x5b, 0x52, 0x0d, 0x74, 0x96,
	0xd3, 0xdc, 0x45, 0xda, 0x75, 0x71, 0xb9, 0x62, 0xe7, 0x2e, 0x04, 0x5d, 0x64, 0x3e, 0x85, 0x06,
	0x06, 0xf8, 0x4d, 0x1e, 0x89, 0x19, 0x84, 0x11, 0xb7, 0xf2, 0x9e, 0xd5, 0x5b, 0x3f, 0xa3, 0xa0,
	0xf7, 0xfc, 0x0c, 0x7a, 0xb9, 0x71, 0x84, 0x50, 0x8d, 0x4b, 0x53, 0xd0, 0xba, 0x2f, 0xef, 0x55,
	0xd2, 0xd6, 0x4b, 0x06, 0xe3, 0x92, 0x75, 0xf3, 0x6a, 0xbd, 0x98, 0xd7, 0xfd, 0xb6, 0x0e, 0x30,
	0x3d, 0x6f, 0xce, 0xf1, 0x1e, 0x80, 0xa7, 0xc6, 0xe5, 0xec, 0xb4, 0xd6, 0x56, 0xe3, 0x92, 0xd2,
	0xdc, 0x13, 0xb8, 0xcb, 0xb5, 0x2e, 0x64, 0x98, 0x48, 0xa5, 0xc3, 0xa1, 0x49, 0x65, 0x3d, 0xd6,
	0x25, 0x70, 0x57, 0x2a, 0xfd, 0x4a, 0x4f, 0xa3, 0xb7, 0x31, 0x1b, 0xbd, 0x8f, 0x00, 0x94, 0x48,
	0x92, 0x30, 0x2f, 0xb0, 0x0b, 0x6b, 0x1a, 0x5b, 0x21, 0x72, 0x88, 0x00, 0xda, 0x6a, 0xc2, 0x8b,
	0xb1, 0xd0, 0x56, 0xa0, 0x45, 0x02, 0x5d, 0x83, 0x19, 0x11, 0x3c, 0x81, 0x27, 0xc2, 0x0a, 0xb4,
	0xed, 0x09, 0x3c, 0x11, 0x86, 0xfd, 0x14, 0x96, 0xa7, 0xec, 0x50, 0x14, 0xb9, 0xcd, 0x70, 0xbd,
	0x4a, 0x64, 0xbb, 0xa0, 0xd4, 0xa2, 0x74, 0x16, 0x8d, 0x6d, 0x8e, 0x33, 0x84, 0x2d, 0xec, 0xd1,
	0x48, 0x44, 0x63, 0x61, 0xbe, 0x58, 0x52, 0x61, 0x7f, 0x6d, 0x00, 0x9c, 0x06, 0xc9, 0xee, 0xb6,
	0x72, 0xf5, 0xaf, 0x1b, 0x85, 0x19, 0xf6, 0x42, 0xb6, 0xf8, 0x53, 0x0d, 0x5a, 0x07, 0x45, 0x8c,
	0xc3, 0xe4, 0x75, 0x3b, 0x6c, 0x40, 0x2f, 0x43, 0x8e, 0xab, 0xab, 0xb6, 0xa6, 0x10, 0x66, 0x2b,
	0x2b, 0xce, 0x1b, 0xa2, 0x90, 0x26, 0x48, 0x51, 0xc6, 0x7e, 0x1e, 0x30, 0xa0, 0x15, 0xfa, 0x0e,
	0xcc, 0x9e, 0x50, 0x6a, 0x31, 0x71, 0x43, 0xb4, 0x5f, 0x3d, 0x82, 0xfe, 0x7d, 0x47, 0x8b, 0x09,
	0x83, 0xcc, 0x2d, 0x17, 0x7b, 0xcb, 0x5f, 0x96, 0xa0, 0x53, 0x9d, 0x36, 0xf7, 0x9c, 0x75, 0x97,
	0xb0, 0xd0, 0xb9, 0x64, 0x4c, 0xcf, 0xa9, 0x33, 0x93, 0xe3, 0x06, 0xe3, 0x72, 0x87, 0x1c, 0xcf,
	0x5e, 0xd4, 0x75, 0x50, 0x6d, 0x73, 0xa3, 0xd8, 0xff, 0x11, 0xb4, 0x68, 0xa9, 0x6c, 0x13, 0xb5,
	0x72, 0xf5, 0xfa, 0x8a, 0x59, 0x36, 0x7d, 0xe6, 0x4e, 0xa5, 0xbe, 0xea, 0x67, 0x88, 0x54, 0x5e,
	0x92, 0xf3, 0xcb, 0x70, 0x46, 0xc4, 0x78, 0x5a, 0x2f, 0xe7, 0x97, 0xc7, 0x95, 0xd4, 0x1a, 0x75,
	0x47, 0xa9, 0xc6, 0x0e, 0xd6, 0x38, 0x5a, 0x45, 0x1b, 0x95, 0xa7, 0x71, 0x58, 0x09, 0x38, 0x37,
	0x13, 0x69, 0xfc, 0xc1, 0x09, 0x3d, 0x86, 0x2e, 0x25, 0x25, 0xfb, 0x1f, 0xc6, 0xd9, 0x80, 0x20,
	0xf3, 0x0f, 0x0b, 0xa8, 0xf7, 0xf9, 0xb7, 0xd0, 0xc1, 0xe9, 0x21, 0xa5, 0x06, 0xcf, 0x83, 0xc6,
	0xfe, 0xd6, 0xde, 0x76, 0xff, 0x8e, 0xdf, 0x81, 0xe6, 0xe1, 0xfb, 0x83, 0xfd, 0xed, 0x7e, 0x0d,
	0x97, 0xdb, 0x7b, 0x5b, 0x3b, 0xbb, 0xfd, 0xa5, 0xe7, 0xdf, 0x83, 0xe7, 0xbe, 0x4f, 0x22, 0xbc,
	0xf5, 0x66, 0x6f, 0x67, 0xbf, 0x7f, 0xc7, 0xef, 0x81, 0x77, 0xb8, 0xbb, 0x75, 0xf4, 0xf6, 0x80,
	0xed, 0xf5, 0x6b, 0x78, 0xc8, 0xe0, 0xfd, 0xc1, 0x61, 0x7f, 0x09, 0xf1, 0xd7, 0xc7, 0x83, 0xa3,
	0x83, 0xbd, 0x6d, 0xd6, 0xaf, 0x3f, 0x8f, 0xc1, 0x73, 0x5f, 0xfa, 0xfc, 0x2e, 0xb4, 0x8f, 0x07,
	0xdb, 0x6c, 0xf7, 0xe0, 0x5d, 0xff, 0x0e, 0x12, 0xb8, 0x01, 0x89, 0x9a, 0xbf, 0x02, 0x5d, 0x77,
	0xd6, 0xce, 0xde, 0xbb, 0xfe, 0x12, 0x02, 0x3b, 0xfb, 0x6f, 0xb6, 0x7f, 0xb5, 0xfb, 0xea, 0x08,
	0x81, 0xba, 0xbf, 0x0c, 0x70, 0xc8, 0x0e, 0xde, 0x1c, 0xbf, 0x26, 0xba, 0x81, 0xff, 0x72, 0x70,
	0xf4, 0x7e, 0x9b, 0x21, 0xd5, 0x3c, 0xbc, 0x33, 0x6c, 0x51, 0x03, 0xf7, 0xdd, 0xbf, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xd8, 0x7e, 0xcc, 0x90, 0x71, 0x19, 0x00, 0x00,
}
