// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/dbmodel/dbmodel.proto

package dbmodel

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Timestamp from public import google/protobuf/timestamp.proto
type Timestamp = timestamp.Timestamp

type LoginType int32

const (
	LoginType_NAME  LoginType = 0
	LoginType_PHONE LoginType = 1
	LoginType_EMAIL LoginType = 2
)

var LoginType_name = map[int32]string{
	0: "NAME",
	1: "PHONE",
	2: "EMAIL",
}

var LoginType_value = map[string]int32{
	"NAME":  0,
	"PHONE": 1,
	"EMAIL": 2,
}

func (x LoginType) String() string {
	return proto.EnumName(LoginType_name, int32(x))
}

func (LoginType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{0}
}

type UserType int32

const (
	UserType_PLATFORM UserType = 0
	UserType_SHOP     UserType = 1
	UserType_CUSTOMER UserType = 2
	UserType_ADMIN    UserType = 9527
)

var UserType_name = map[int32]string{
	0:    "PLATFORM",
	1:    "SHOP",
	2:    "CUSTOMER",
	9527: "ADMIN",
}

var UserType_value = map[string]int32{
	"PLATFORM": 0,
	"SHOP":     1,
	"CUSTOMER": 2,
	"ADMIN":    9527,
}

func (x UserType) String() string {
	return proto.EnumName(UserType_name, int32(x))
}

func (UserType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{1}
}

type FileType int32

const (
	FileType_USERLOG     FileType = 0
	FileType_SHOPLOG     FileType = 1
	FileType_PLATFORMIMG FileType = 2
	FileType_INDEXLBTIMG FileType = 3
	FileType_PRODUCTIMG  FileType = 4
	FileType_OTHERIMG    FileType = 5
)

var FileType_name = map[int32]string{
	0: "USERLOG",
	1: "SHOPLOG",
	2: "PLATFORMIMG",
	3: "INDEXLBTIMG",
	4: "PRODUCTIMG",
	5: "OTHERIMG",
}

var FileType_value = map[string]int32{
	"USERLOG":     0,
	"SHOPLOG":     1,
	"PLATFORMIMG": 2,
	"INDEXLBTIMG": 3,
	"PRODUCTIMG":  4,
	"OTHERIMG":    5,
}

func (x FileType) String() string {
	return proto.EnumName(FileType_name, int32(x))
}

func (FileType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{2}
}

type QuaType int32

const (
	QuaType_IDCARD           QuaType = 0
	QuaType_BANCKCARD        QuaType = 1
	QuaType_BIZLICENSE       QuaType = 2
	QuaType_DMC              QuaType = 3
	QuaType_DSC              QuaType = 4
	QuaType_GSP              QuaType = 5
	QuaType_GMP              QuaType = 6
	QuaType_PPC              QuaType = 7
	QuaType_IDL              QuaType = 8
	QuaType_CT               QuaType = 9
	QuaType_NDC              QuaType = 10
	QuaType_ATTORNEY         QuaType = 11
	QuaType_GTQ              QuaType = 12
	QuaType_SQC              QuaType = 13
	QuaType_QS               QuaType = 14
	QuaType_OIML             QuaType = 15
	QuaType_HZP              QuaType = 16
	QuaType_GMPC             QuaType = 17
	QuaType_THREEC           QuaType = 18
	QuaType_KHXKZ            QuaType = 19
	QuaType_SHOPURL          QuaType = 20
	QuaType_BIZLICENSEADREES QuaType = 21
	QuaType_OTHER            QuaType = 22
)

var QuaType_name = map[int32]string{
	0:  "IDCARD",
	1:  "BANCKCARD",
	2:  "BIZLICENSE",
	3:  "DMC",
	4:  "DSC",
	5:  "GSP",
	6:  "GMP",
	7:  "PPC",
	8:  "IDL",
	9:  "CT",
	10: "NDC",
	11: "ATTORNEY",
	12: "GTQ",
	13: "SQC",
	14: "QS",
	15: "OIML",
	16: "HZP",
	17: "GMPC",
	18: "THREEC",
	19: "KHXKZ",
	20: "SHOPURL",
	21: "BIZLICENSEADREES",
	22: "OTHER",
}

var QuaType_value = map[string]int32{
	"IDCARD":           0,
	"BANCKCARD":        1,
	"BIZLICENSE":       2,
	"DMC":              3,
	"DSC":              4,
	"GSP":              5,
	"GMP":              6,
	"PPC":              7,
	"IDL":              8,
	"CT":               9,
	"NDC":              10,
	"ATTORNEY":         11,
	"GTQ":              12,
	"SQC":              13,
	"QS":               14,
	"OIML":             15,
	"HZP":              16,
	"GMPC":             17,
	"THREEC":           18,
	"KHXKZ":            19,
	"SHOPURL":          20,
	"BIZLICENSEADREES": 21,
	"OTHER":            22,
}

func (x QuaType) String() string {
	return proto.EnumName(QuaType_name, int32(x))
}

func (QuaType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{3}
}

type SysUser struct {
	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName  string `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	TrueName  string `protobuf:"bytes,3,opt,name=true_name,json=trueName,proto3" json:"true_name,omitempty"`
	UserPhone string `protobuf:"bytes,4,opt,name=user_phone,json=userPhone,proto3" json:"user_phone,omitempty"`
	//string user_password=22;
	//string wx_open_id=23;
	UserWx               string              `protobuf:"bytes,5,opt,name=user_wx,json=userWx,proto3" json:"user_wx,omitempty"`
	UserEmail            string              `protobuf:"bytes,6,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	UserQq               string              `protobuf:"bytes,7,opt,name=user_qq,json=userQq,proto3" json:"user_qq,omitempty"`
	UserTel              string              `protobuf:"bytes,8,opt,name=user_tel,json=userTel,proto3" json:"user_tel,omitempty"`
	Balance              string              `protobuf:"bytes,9,opt,name=balance,proto3" json:"balance,omitempty"`
	IdCard               string              `protobuf:"bytes,10,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`
	Point                string              `protobuf:"bytes,11,opt,name=point,proto3" json:"point,omitempty"`
	ProvinceId           string              `protobuf:"bytes,12,opt,name=province_id,json=provinceId,proto3" json:"province_id,omitempty"`
	Province             *SysTree            `protobuf:"bytes,13,opt,name=province,proto3" json:"province,omitempty"`
	CityId               string              `protobuf:"bytes,14,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	City                 *SysTree            `protobuf:"bytes,15,opt,name=city,proto3" json:"city,omitempty"`
	AreaId               string              `protobuf:"bytes,16,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	Area                 *SysTree            `protobuf:"bytes,17,opt,name=area,proto3" json:"area,omitempty"`
	Address              string              `protobuf:"bytes,18,opt,name=address,proto3" json:"address,omitempty"`
	Vip                  int32               `protobuf:"varint,19,opt,name=vip,proto3" json:"vip,omitempty"`
	BankName             string              `protobuf:"bytes,20,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	BranchName           string              `protobuf:"bytes,21,opt,name=branch_name,json=branchName,proto3" json:"branch_name,omitempty"`
	Bankcard             string              `protobuf:"bytes,22,opt,name=bankcard,proto3" json:"bankcard,omitempty"`
	BankCardName         string              `protobuf:"bytes,23,opt,name=bank_card_name,json=bankCardName,proto3" json:"bank_card_name,omitempty"`
	UserIcon             string              `protobuf:"bytes,24,opt,name=user_icon,json=userIcon,proto3" json:"user_icon,omitempty"`
	Icon                 *SysFile            `protobuf:"bytes,25,opt,name=icon,proto3" json:"icon,omitempty"`
	Roles                []*SysRole          `protobuf:"bytes,26,rep,name=roles,proto3" json:"roles,omitempty"`
	Groups               []*SysGroup         `protobuf:"bytes,27,rep,name=groups,proto3" json:"groups,omitempty"`
	LogisticsAddresss    []*LogisticsAddress `protobuf:"bytes,28,rep,name=logistics_addresss,json=logisticsAddresss,proto3" json:"logistics_addresss,omitempty"`
	Qualifications       []*Qualification    `protobuf:"bytes,29,rep,name=qualifications,proto3" json:"qualifications,omitempty"`
	UserType             UserType            `protobuf:"varint,30,opt,name=user_type,json=userType,proto3,enum=dbmodel.UserType" json:"user_type,omitempty"`
	Created              string              `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string              `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SysUser) Reset()         { *m = SysUser{} }
func (m *SysUser) String() string { return proto.CompactTextString(m) }
func (*SysUser) ProtoMessage()    {}
func (*SysUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{0}
}

func (m *SysUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysUser.Unmarshal(m, b)
}
func (m *SysUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysUser.Marshal(b, m, deterministic)
}
func (m *SysUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysUser.Merge(m, src)
}
func (m *SysUser) XXX_Size() int {
	return xxx_messageInfo_SysUser.Size(m)
}
func (m *SysUser) XXX_DiscardUnknown() {
	xxx_messageInfo_SysUser.DiscardUnknown(m)
}

var xxx_messageInfo_SysUser proto.InternalMessageInfo

func (m *SysUser) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SysUser) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *SysUser) GetTrueName() string {
	if m != nil {
		return m.TrueName
	}
	return ""
}

func (m *SysUser) GetUserPhone() string {
	if m != nil {
		return m.UserPhone
	}
	return ""
}

func (m *SysUser) GetUserWx() string {
	if m != nil {
		return m.UserWx
	}
	return ""
}

func (m *SysUser) GetUserEmail() string {
	if m != nil {
		return m.UserEmail
	}
	return ""
}

func (m *SysUser) GetUserQq() string {
	if m != nil {
		return m.UserQq
	}
	return ""
}

func (m *SysUser) GetUserTel() string {
	if m != nil {
		return m.UserTel
	}
	return ""
}

func (m *SysUser) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *SysUser) GetIdCard() string {
	if m != nil {
		return m.IdCard
	}
	return ""
}

func (m *SysUser) GetPoint() string {
	if m != nil {
		return m.Point
	}
	return ""
}

func (m *SysUser) GetProvinceId() string {
	if m != nil {
		return m.ProvinceId
	}
	return ""
}

func (m *SysUser) GetProvince() *SysTree {
	if m != nil {
		return m.Province
	}
	return nil
}

func (m *SysUser) GetCityId() string {
	if m != nil {
		return m.CityId
	}
	return ""
}

func (m *SysUser) GetCity() *SysTree {
	if m != nil {
		return m.City
	}
	return nil
}

func (m *SysUser) GetAreaId() string {
	if m != nil {
		return m.AreaId
	}
	return ""
}

func (m *SysUser) GetArea() *SysTree {
	if m != nil {
		return m.Area
	}
	return nil
}

func (m *SysUser) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SysUser) GetVip() int32 {
	if m != nil {
		return m.Vip
	}
	return 0
}

func (m *SysUser) GetBankName() string {
	if m != nil {
		return m.BankName
	}
	return ""
}

func (m *SysUser) GetBranchName() string {
	if m != nil {
		return m.BranchName
	}
	return ""
}

func (m *SysUser) GetBankcard() string {
	if m != nil {
		return m.Bankcard
	}
	return ""
}

func (m *SysUser) GetBankCardName() string {
	if m != nil {
		return m.BankCardName
	}
	return ""
}

func (m *SysUser) GetUserIcon() string {
	if m != nil {
		return m.UserIcon
	}
	return ""
}

func (m *SysUser) GetIcon() *SysFile {
	if m != nil {
		return m.Icon
	}
	return nil
}

func (m *SysUser) GetRoles() []*SysRole {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *SysUser) GetGroups() []*SysGroup {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *SysUser) GetLogisticsAddresss() []*LogisticsAddress {
	if m != nil {
		return m.LogisticsAddresss
	}
	return nil
}

func (m *SysUser) GetQualifications() []*Qualification {
	if m != nil {
		return m.Qualifications
	}
	return nil
}

func (m *SysUser) GetUserType() UserType {
	if m != nil {
		return m.UserType
	}
	return UserType_PLATFORM
}

func (m *SysUser) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *SysUser) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

type OnlyMenu struct {
	Menus                []*SysMenu `protobuf:"bytes,31,rep,name=menus,proto3" json:"menus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *OnlyMenu) Reset()         { *m = OnlyMenu{} }
func (m *OnlyMenu) String() string { return proto.CompactTextString(m) }
func (*OnlyMenu) ProtoMessage()    {}
func (*OnlyMenu) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{1}
}

func (m *OnlyMenu) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlyMenu.Unmarshal(m, b)
}
func (m *OnlyMenu) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlyMenu.Marshal(b, m, deterministic)
}
func (m *OnlyMenu) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlyMenu.Merge(m, src)
}
func (m *OnlyMenu) XXX_Size() int {
	return xxx_messageInfo_OnlyMenu.Size(m)
}
func (m *OnlyMenu) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlyMenu.DiscardUnknown(m)
}

var xxx_messageInfo_OnlyMenu proto.InternalMessageInfo

func (m *OnlyMenu) GetMenus() []*SysMenu {
	if m != nil {
		return m.Menus
	}
	return nil
}

type OnlySrv struct {
	Srvs                 []*SysSrv `protobuf:"bytes,1,rep,name=srvs,proto3" json:"srvs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *OnlySrv) Reset()         { *m = OnlySrv{} }
func (m *OnlySrv) String() string { return proto.CompactTextString(m) }
func (*OnlySrv) ProtoMessage()    {}
func (*OnlySrv) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{2}
}

func (m *OnlySrv) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlySrv.Unmarshal(m, b)
}
func (m *OnlySrv) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlySrv.Marshal(b, m, deterministic)
}
func (m *OnlySrv) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlySrv.Merge(m, src)
}
func (m *OnlySrv) XXX_Size() int {
	return xxx_messageInfo_OnlySrv.Size(m)
}
func (m *OnlySrv) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlySrv.DiscardUnknown(m)
}

var xxx_messageInfo_OnlySrv proto.InternalMessageInfo

func (m *OnlySrv) GetSrvs() []*SysSrv {
	if m != nil {
		return m.Srvs
	}
	return nil
}

type OnlyApi struct {
	Apis                 []*SysApi `protobuf:"bytes,1,rep,name=apis,proto3" json:"apis,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *OnlyApi) Reset()         { *m = OnlyApi{} }
func (m *OnlyApi) String() string { return proto.CompactTextString(m) }
func (*OnlyApi) ProtoMessage()    {}
func (*OnlyApi) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{3}
}

func (m *OnlyApi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlyApi.Unmarshal(m, b)
}
func (m *OnlyApi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlyApi.Marshal(b, m, deterministic)
}
func (m *OnlyApi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlyApi.Merge(m, src)
}
func (m *OnlyApi) XXX_Size() int {
	return xxx_messageInfo_OnlyApi.Size(m)
}
func (m *OnlyApi) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlyApi.DiscardUnknown(m)
}

var xxx_messageInfo_OnlyApi proto.InternalMessageInfo

func (m *OnlyApi) GetApis() []*SysApi {
	if m != nil {
		return m.Apis
	}
	return nil
}

type SysFile struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Size                 string   `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`
	FileExplain          string   `protobuf:"bytes,5,opt,name=file_explain,json=fileExplain,proto3" json:"file_explain,omitempty"`
	Sort                 int32    `protobuf:"varint,6,opt,name=sort,proto3" json:"sort,omitempty"`
	FileType             FileType `protobuf:"varint,7,opt,name=file_type,json=fileType,proto3,enum=dbmodel.FileType" json:"file_type,omitempty"`
	FileSuffix           string   `protobuf:"bytes,8,opt,name=file_suffix,json=fileSuffix,proto3" json:"file_suffix,omitempty"`
	Created              string   `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string   `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SysFile) Reset()         { *m = SysFile{} }
func (m *SysFile) String() string { return proto.CompactTextString(m) }
func (*SysFile) ProtoMessage()    {}
func (*SysFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{4}
}

func (m *SysFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysFile.Unmarshal(m, b)
}
func (m *SysFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysFile.Marshal(b, m, deterministic)
}
func (m *SysFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysFile.Merge(m, src)
}
func (m *SysFile) XXX_Size() int {
	return xxx_messageInfo_SysFile.Size(m)
}
func (m *SysFile) XXX_DiscardUnknown() {
	xxx_messageInfo_SysFile.DiscardUnknown(m)
}

var xxx_messageInfo_SysFile proto.InternalMessageInfo

func (m *SysFile) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SysFile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SysFile) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *SysFile) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *SysFile) GetFileExplain() string {
	if m != nil {
		return m.FileExplain
	}
	return ""
}

func (m *SysFile) GetSort() int32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *SysFile) GetFileType() FileType {
	if m != nil {
		return m.FileType
	}
	return FileType_USERLOG
}

func (m *SysFile) GetFileSuffix() string {
	if m != nil {
		return m.FileSuffix
	}
	return ""
}

func (m *SysFile) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *SysFile) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

type SysTree struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 string     `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Text                 string     `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Sort                 int32      `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	PId                  string     `protobuf:"bytes,5,opt,name=p_id,json=pId,proto3" json:"p_id,omitempty"`
	Children             []*SysTree `protobuf:"bytes,6,rep,name=children,proto3" json:"children,omitempty"`
	Key                  string     `protobuf:"bytes,100,opt,name=key,proto3" json:"key,omitempty"`
	Title                string     `protobuf:"bytes,101,opt,name=title,proto3" json:"title,omitempty"`
	Created              string     `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string     `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SysTree) Reset()         { *m = SysTree{} }
func (m *SysTree) String() string { return proto.CompactTextString(m) }
func (*SysTree) ProtoMessage()    {}
func (*SysTree) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{5}
}

func (m *SysTree) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysTree.Unmarshal(m, b)
}
func (m *SysTree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysTree.Marshal(b, m, deterministic)
}
func (m *SysTree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysTree.Merge(m, src)
}
func (m *SysTree) XXX_Size() int {
	return xxx_messageInfo_SysTree.Size(m)
}
func (m *SysTree) XXX_DiscardUnknown() {
	xxx_messageInfo_SysTree.DiscardUnknown(m)
}

var xxx_messageInfo_SysTree proto.InternalMessageInfo

func (m *SysTree) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SysTree) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *SysTree) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *SysTree) GetSort() int32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *SysTree) GetPId() string {
	if m != nil {
		return m.PId
	}
	return ""
}

func (m *SysTree) GetChildren() []*SysTree {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *SysTree) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SysTree) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SysTree) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *SysTree) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

//用户组请求
type SysGroup struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupName            string     `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	GroupExplain         string     `protobuf:"bytes,3,opt,name=group_explain,json=groupExplain,proto3" json:"group_explain,omitempty"`
	Roles                []*SysRole `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	Users                []*SysRole `protobuf:"bytes,5,rep,name=users,proto3" json:"users,omitempty"`
	Created              string     `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string     `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SysGroup) Reset()         { *m = SysGroup{} }
func (m *SysGroup) String() string { return proto.CompactTextString(m) }
func (*SysGroup) ProtoMessage()    {}
func (*SysGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{6}
}

func (m *SysGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysGroup.Unmarshal(m, b)
}
func (m *SysGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysGroup.Marshal(b, m, deterministic)
}
func (m *SysGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysGroup.Merge(m, src)
}
func (m *SysGroup) XXX_Size() int {
	return xxx_messageInfo_SysGroup.Size(m)
}
func (m *SysGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_SysGroup.DiscardUnknown(m)
}

var xxx_messageInfo_SysGroup proto.InternalMessageInfo

func (m *SysGroup) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SysGroup) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *SysGroup) GetGroupExplain() string {
	if m != nil {
		return m.GroupExplain
	}
	return ""
}

func (m *SysGroup) GetRoles() []*SysRole {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *SysGroup) GetUsers() []*SysRole {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *SysGroup) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *SysGroup) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

//角色请求
type SysRole struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoleName             string     `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	RoleExplain          string     `protobuf:"bytes,3,opt,name=role_explain,json=roleExplain,proto3" json:"role_explain,omitempty"`
	Menus                []*SysMenu `protobuf:"bytes,4,rep,name=menus,proto3" json:"menus,omitempty"`
	Srvs                 []*SysSrv  `protobuf:"bytes,5,rep,name=srvs,proto3" json:"srvs,omitempty"`
	Apis                 []*SysApi  `protobuf:"bytes,6,rep,name=apis,proto3" json:"apis,omitempty"`
	Users                []*SysUser `protobuf:"bytes,7,rep,name=users,proto3" json:"users,omitempty"`
	PId                  string     `protobuf:"bytes,8,opt,name=p_id,json=pId,proto3" json:"p_id,omitempty"`
	Children             []*SysRole `protobuf:"bytes,9,rep,name=children,proto3" json:"children,omitempty"`
	Key                  string     `protobuf:"bytes,100,opt,name=key,proto3" json:"key,omitempty"`
	Title                string     `protobuf:"bytes,101,opt,name=title,proto3" json:"title,omitempty"`
	Created              string     `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string     `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SysRole) Reset()         { *m = SysRole{} }
func (m *SysRole) String() string { return proto.CompactTextString(m) }
func (*SysRole) ProtoMessage()    {}
func (*SysRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{7}
}

func (m *SysRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysRole.Unmarshal(m, b)
}
func (m *SysRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysRole.Marshal(b, m, deterministic)
}
func (m *SysRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysRole.Merge(m, src)
}
func (m *SysRole) XXX_Size() int {
	return xxx_messageInfo_SysRole.Size(m)
}
func (m *SysRole) XXX_DiscardUnknown() {
	xxx_messageInfo_SysRole.DiscardUnknown(m)
}

var xxx_messageInfo_SysRole proto.InternalMessageInfo

func (m *SysRole) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SysRole) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *SysRole) GetRoleExplain() string {
	if m != nil {
		return m.RoleExplain
	}
	return ""
}

func (m *SysRole) GetMenus() []*SysMenu {
	if m != nil {
		return m.Menus
	}
	return nil
}

func (m *SysRole) GetSrvs() []*SysSrv {
	if m != nil {
		return m.Srvs
	}
	return nil
}

func (m *SysRole) GetApis() []*SysApi {
	if m != nil {
		return m.Apis
	}
	return nil
}

func (m *SysRole) GetUsers() []*SysUser {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *SysRole) GetPId() string {
	if m != nil {
		return m.PId
	}
	return ""
}

func (m *SysRole) GetChildren() []*SysRole {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *SysRole) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SysRole) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SysRole) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *SysRole) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

type SysMenu struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key                  string     `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Text                 string     `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	I_18N                string     `protobuf:"bytes,4,opt,name=i_18_n,json=i18N,proto3" json:"i_18_n,omitempty"`
	Link                 string     `protobuf:"bytes,5,opt,name=link,proto3" json:"link,omitempty"`
	ExternalLink         string     `protobuf:"bytes,6,opt,name=external_link,json=externalLink,proto3" json:"external_link,omitempty"`
	Target               string     `protobuf:"bytes,7,opt,name=target,proto3" json:"target,omitempty"`
	Sort                 string     `protobuf:"bytes,8,opt,name=sort,proto3" json:"sort,omitempty"`
	Badge                int32      `protobuf:"varint,9,opt,name=badge,proto3" json:"badge,omitempty"`
	BadgeDoc             string     `protobuf:"bytes,10,opt,name=badge_doc,json=badgeDoc,proto3" json:"badge_doc,omitempty"`
	BadgeStatus          string     `protobuf:"bytes,11,opt,name=badge_status,json=badgeStatus,proto3" json:"badge_status,omitempty"`
	Acl                  string     `protobuf:"bytes,12,opt,name=acl,proto3" json:"acl,omitempty"`
	Hide                 bool       `protobuf:"varint,13,opt,name=hide,proto3" json:"hide,omitempty"`
	Disabled             bool       `protobuf:"varint,14,opt,name=disabled,proto3" json:"disabled,omitempty"`
	HideInBreadcrumb     bool       `protobuf:"varint,15,opt,name=hideInBreadcrumb,proto3" json:"hideInBreadcrumb,omitempty"`
	Shortcut             bool       `protobuf:"varint,16,opt,name=shortcut,proto3" json:"shortcut,omitempty"`
	ShortcutRoot         bool       `protobuf:"varint,17,opt,name=shortcut_root,json=shortcutRoot,proto3" json:"shortcut_root,omitempty"`
	Reuse                bool       `protobuf:"varint,18,opt,name=reuse,proto3" json:"reuse,omitempty"`
	Icon                 string     `protobuf:"bytes,19,opt,name=icon,proto3" json:"icon,omitempty"`
	PId                  string     `protobuf:"bytes,20,opt,name=p_id,json=pId,proto3" json:"p_id,omitempty"`
	Children             []*SysMenu `protobuf:"bytes,21,rep,name=children,proto3" json:"children,omitempty"`
	Group                bool       `protobuf:"varint,22,opt,name=group,proto3" json:"group,omitempty"`
	Title                string     `protobuf:"bytes,101,opt,name=title,proto3" json:"title,omitempty"`
	Created              string     `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string     `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SysMenu) Reset()         { *m = SysMenu{} }
func (m *SysMenu) String() string { return proto.CompactTextString(m) }
func (*SysMenu) ProtoMessage()    {}
func (*SysMenu) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{8}
}

func (m *SysMenu) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysMenu.Unmarshal(m, b)
}
func (m *SysMenu) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysMenu.Marshal(b, m, deterministic)
}
func (m *SysMenu) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysMenu.Merge(m, src)
}
func (m *SysMenu) XXX_Size() int {
	return xxx_messageInfo_SysMenu.Size(m)
}
func (m *SysMenu) XXX_DiscardUnknown() {
	xxx_messageInfo_SysMenu.DiscardUnknown(m)
}

var xxx_messageInfo_SysMenu proto.InternalMessageInfo

func (m *SysMenu) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SysMenu) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SysMenu) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *SysMenu) GetI_18N() string {
	if m != nil {
		return m.I_18N
	}
	return ""
}

func (m *SysMenu) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *SysMenu) GetExternalLink() string {
	if m != nil {
		return m.ExternalLink
	}
	return ""
}

func (m *SysMenu) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *SysMenu) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *SysMenu) GetBadge() int32 {
	if m != nil {
		return m.Badge
	}
	return 0
}

func (m *SysMenu) GetBadgeDoc() string {
	if m != nil {
		return m.BadgeDoc
	}
	return ""
}

func (m *SysMenu) GetBadgeStatus() string {
	if m != nil {
		return m.BadgeStatus
	}
	return ""
}

func (m *SysMenu) GetAcl() string {
	if m != nil {
		return m.Acl
	}
	return ""
}

func (m *SysMenu) GetHide() bool {
	if m != nil {
		return m.Hide
	}
	return false
}

func (m *SysMenu) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *SysMenu) GetHideInBreadcrumb() bool {
	if m != nil {
		return m.HideInBreadcrumb
	}
	return false
}

func (m *SysMenu) GetShortcut() bool {
	if m != nil {
		return m.Shortcut
	}
	return false
}

func (m *SysMenu) GetShortcutRoot() bool {
	if m != nil {
		return m.ShortcutRoot
	}
	return false
}

func (m *SysMenu) GetReuse() bool {
	if m != nil {
		return m.Reuse
	}
	return false
}

func (m *SysMenu) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *SysMenu) GetPId() string {
	if m != nil {
		return m.PId
	}
	return ""
}

func (m *SysMenu) GetChildren() []*SysMenu {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *SysMenu) GetGroup() bool {
	if m != nil {
		return m.Group
	}
	return false
}

func (m *SysMenu) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SysMenu) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *SysMenu) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

type SysApi struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Service              string   `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	ApiExplain           string   `protobuf:"bytes,4,opt,name=api_explain,json=apiExplain,proto3" json:"api_explain,omitempty"`
	Created              string   `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string   `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SysApi) Reset()         { *m = SysApi{} }
func (m *SysApi) String() string { return proto.CompactTextString(m) }
func (*SysApi) ProtoMessage()    {}
func (*SysApi) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{9}
}

func (m *SysApi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysApi.Unmarshal(m, b)
}
func (m *SysApi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysApi.Marshal(b, m, deterministic)
}
func (m *SysApi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysApi.Merge(m, src)
}
func (m *SysApi) XXX_Size() int {
	return xxx_messageInfo_SysApi.Size(m)
}
func (m *SysApi) XXX_DiscardUnknown() {
	xxx_messageInfo_SysApi.DiscardUnknown(m)
}

var xxx_messageInfo_SysApi proto.InternalMessageInfo

func (m *SysApi) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SysApi) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *SysApi) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *SysApi) GetApiExplain() string {
	if m != nil {
		return m.ApiExplain
	}
	return ""
}

func (m *SysApi) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *SysApi) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

type SysSrv struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Service              string   `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	SrvExplain           string   `protobuf:"bytes,4,opt,name=srv_explain,json=srvExplain,proto3" json:"srv_explain,omitempty"`
	Created              string   `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string   `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SysSrv) Reset()         { *m = SysSrv{} }
func (m *SysSrv) String() string { return proto.CompactTextString(m) }
func (*SysSrv) ProtoMessage()    {}
func (*SysSrv) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{10}
}

func (m *SysSrv) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysSrv.Unmarshal(m, b)
}
func (m *SysSrv) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysSrv.Marshal(b, m, deterministic)
}
func (m *SysSrv) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysSrv.Merge(m, src)
}
func (m *SysSrv) XXX_Size() int {
	return xxx_messageInfo_SysSrv.Size(m)
}
func (m *SysSrv) XXX_DiscardUnknown() {
	xxx_messageInfo_SysSrv.DiscardUnknown(m)
}

var xxx_messageInfo_SysSrv proto.InternalMessageInfo

func (m *SysSrv) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SysSrv) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *SysSrv) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *SysSrv) GetSrvExplain() string {
	if m != nil {
		return m.SrvExplain
	}
	return ""
}

func (m *SysSrv) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *SysSrv) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

type LogisticsAddress struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsDefault            bool     `protobuf:"varint,2,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	User                 *SysUser `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	ProvinceId           string   `protobuf:"bytes,12,opt,name=province_id,json=provinceId,proto3" json:"province_id,omitempty"`
	Province             *SysTree `protobuf:"bytes,13,opt,name=province,proto3" json:"province,omitempty"`
	CityId               string   `protobuf:"bytes,14,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	City                 *SysTree `protobuf:"bytes,15,opt,name=city,proto3" json:"city,omitempty"`
	AreaId               string   `protobuf:"bytes,16,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	Area                 *SysTree `protobuf:"bytes,17,opt,name=area,proto3" json:"area,omitempty"`
	Address              string   `protobuf:"bytes,18,opt,name=address,proto3" json:"address,omitempty"`
	Created              string   `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string   `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogisticsAddress) Reset()         { *m = LogisticsAddress{} }
func (m *LogisticsAddress) String() string { return proto.CompactTextString(m) }
func (*LogisticsAddress) ProtoMessage()    {}
func (*LogisticsAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{11}
}

func (m *LogisticsAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogisticsAddress.Unmarshal(m, b)
}
func (m *LogisticsAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogisticsAddress.Marshal(b, m, deterministic)
}
func (m *LogisticsAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogisticsAddress.Merge(m, src)
}
func (m *LogisticsAddress) XXX_Size() int {
	return xxx_messageInfo_LogisticsAddress.Size(m)
}
func (m *LogisticsAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_LogisticsAddress.DiscardUnknown(m)
}

var xxx_messageInfo_LogisticsAddress proto.InternalMessageInfo

func (m *LogisticsAddress) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LogisticsAddress) GetIsDefault() bool {
	if m != nil {
		return m.IsDefault
	}
	return false
}

func (m *LogisticsAddress) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *LogisticsAddress) GetUser() *SysUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *LogisticsAddress) GetProvinceId() string {
	if m != nil {
		return m.ProvinceId
	}
	return ""
}

func (m *LogisticsAddress) GetProvince() *SysTree {
	if m != nil {
		return m.Province
	}
	return nil
}

func (m *LogisticsAddress) GetCityId() string {
	if m != nil {
		return m.CityId
	}
	return ""
}

func (m *LogisticsAddress) GetCity() *SysTree {
	if m != nil {
		return m.City
	}
	return nil
}

func (m *LogisticsAddress) GetAreaId() string {
	if m != nil {
		return m.AreaId
	}
	return ""
}

func (m *LogisticsAddress) GetArea() *SysTree {
	if m != nil {
		return m.Area
	}
	return nil
}

func (m *LogisticsAddress) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *LogisticsAddress) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *LogisticsAddress) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

type Qualification struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsDefault            bool       `protobuf:"varint,2,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	UserId               string     `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ShopId               string     `protobuf:"bytes,4,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	QuaType              QuaType    `protobuf:"varint,5,opt,name=qua_type,json=quaType,proto3,enum=dbmodel.QuaType" json:"qua_type,omitempty"`
	QuaFiles             []*SysFile `protobuf:"bytes,6,rep,name=qua_files,json=quaFiles,proto3" json:"qua_files,omitempty"`
	QuaExplain           string     `protobuf:"bytes,7,opt,name=qua_explain,json=quaExplain,proto3" json:"qua_explain,omitempty"`
	QuaNumber            string     `protobuf:"bytes,8,opt,name=qua_number,json=quaNumber,proto3" json:"qua_number,omitempty"`
	StartTime            string     `protobuf:"bytes,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              string     `protobuf:"bytes,10,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Created              string     `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string     `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Qualification) Reset()         { *m = Qualification{} }
func (m *Qualification) String() string { return proto.CompactTextString(m) }
func (*Qualification) ProtoMessage()    {}
func (*Qualification) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{12}
}

func (m *Qualification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Qualification.Unmarshal(m, b)
}
func (m *Qualification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Qualification.Marshal(b, m, deterministic)
}
func (m *Qualification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Qualification.Merge(m, src)
}
func (m *Qualification) XXX_Size() int {
	return xxx_messageInfo_Qualification.Size(m)
}
func (m *Qualification) XXX_DiscardUnknown() {
	xxx_messageInfo_Qualification.DiscardUnknown(m)
}

var xxx_messageInfo_Qualification proto.InternalMessageInfo

func (m *Qualification) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Qualification) GetIsDefault() bool {
	if m != nil {
		return m.IsDefault
	}
	return false
}

func (m *Qualification) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Qualification) GetShopId() string {
	if m != nil {
		return m.ShopId
	}
	return ""
}

func (m *Qualification) GetQuaType() QuaType {
	if m != nil {
		return m.QuaType
	}
	return QuaType_IDCARD
}

func (m *Qualification) GetQuaFiles() []*SysFile {
	if m != nil {
		return m.QuaFiles
	}
	return nil
}

func (m *Qualification) GetQuaExplain() string {
	if m != nil {
		return m.QuaExplain
	}
	return ""
}

func (m *Qualification) GetQuaNumber() string {
	if m != nil {
		return m.QuaNumber
	}
	return ""
}

func (m *Qualification) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *Qualification) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *Qualification) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Qualification) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

type SysShop struct {
	Id                   string           `protobuf:"bytes,100,opt,name=id,proto3" json:"id,omitempty"`
	ShopName             string           `protobuf:"bytes,1,opt,name=shop_name,json=shopName,proto3" json:"shop_name,omitempty"`
	ShopExplain          string           `protobuf:"bytes,2,opt,name=shop_explain,json=shopExplain,proto3" json:"shop_explain,omitempty"`
	IsSht                bool             `protobuf:"varint,3,opt,name=is_sht,json=isSht,proto3" json:"is_sht,omitempty"`
	ShtExplain           string           `protobuf:"bytes,4,opt,name=sht_explain,json=shtExplain,proto3" json:"sht_explain,omitempty"`
	AppId                string           `protobuf:"bytes,5,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Appsecret            string           `protobuf:"bytes,6,opt,name=appsecret,proto3" json:"appsecret,omitempty"`
	Grade                float32          `protobuf:"fixed32,7,opt,name=grade,proto3" json:"grade,omitempty"`
	GradeWl              float32          `protobuf:"fixed32,8,opt,name=grade_wl,json=gradeWl,proto3" json:"grade_wl,omitempty"`
	GradeFw              float32          `protobuf:"fixed32,9,opt,name=grade_fw,json=gradeFw,proto3" json:"grade_fw,omitempty"`
	GradeMs              float32          `protobuf:"fixed32,10,opt,name=grade_ms,json=gradeMs,proto3" json:"grade_ms,omitempty"`
	Cash                 int32            `protobuf:"varint,11,opt,name=cash,proto3" json:"cash,omitempty"`
	Sort                 int32            `protobuf:"varint,12,opt,name=sort,proto3" json:"sort,omitempty"`
	Comments             int32            `protobuf:"varint,13,opt,name=comments,proto3" json:"comments,omitempty"`
	Vip                  int32            `protobuf:"varint,14,opt,name=vip,proto3" json:"vip,omitempty"`
	Point                float32          `protobuf:"fixed32,15,opt,name=point,proto3" json:"point,omitempty"`
	Logo                 *SysFile         `protobuf:"bytes,16,opt,name=logo,proto3" json:"logo,omitempty"`
	Classify             []*SysFile       `protobuf:"bytes,17,rep,name=classify,proto3" json:"classify,omitempty"`
	User                 []*SysUser       `protobuf:"bytes,18,rep,name=user,proto3" json:"user,omitempty"`
	Imgs                 []*SysFile       `protobuf:"bytes,19,rep,name=imgs,proto3" json:"imgs,omitempty"`
	Qualifications       []*Qualification `protobuf:"bytes,20,rep,name=qualifications,proto3" json:"qualifications,omitempty"`
	Created              string           `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string           `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SysShop) Reset()         { *m = SysShop{} }
func (m *SysShop) String() string { return proto.CompactTextString(m) }
func (*SysShop) ProtoMessage()    {}
func (*SysShop) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{13}
}

func (m *SysShop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysShop.Unmarshal(m, b)
}
func (m *SysShop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysShop.Marshal(b, m, deterministic)
}
func (m *SysShop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysShop.Merge(m, src)
}
func (m *SysShop) XXX_Size() int {
	return xxx_messageInfo_SysShop.Size(m)
}
func (m *SysShop) XXX_DiscardUnknown() {
	xxx_messageInfo_SysShop.DiscardUnknown(m)
}

var xxx_messageInfo_SysShop proto.InternalMessageInfo

func (m *SysShop) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SysShop) GetShopName() string {
	if m != nil {
		return m.ShopName
	}
	return ""
}

func (m *SysShop) GetShopExplain() string {
	if m != nil {
		return m.ShopExplain
	}
	return ""
}

func (m *SysShop) GetIsSht() bool {
	if m != nil {
		return m.IsSht
	}
	return false
}

func (m *SysShop) GetShtExplain() string {
	if m != nil {
		return m.ShtExplain
	}
	return ""
}

func (m *SysShop) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *SysShop) GetAppsecret() string {
	if m != nil {
		return m.Appsecret
	}
	return ""
}

func (m *SysShop) GetGrade() float32 {
	if m != nil {
		return m.Grade
	}
	return 0
}

func (m *SysShop) GetGradeWl() float32 {
	if m != nil {
		return m.GradeWl
	}
	return 0
}

func (m *SysShop) GetGradeFw() float32 {
	if m != nil {
		return m.GradeFw
	}
	return 0
}

func (m *SysShop) GetGradeMs() float32 {
	if m != nil {
		return m.GradeMs
	}
	return 0
}

func (m *SysShop) GetCash() int32 {
	if m != nil {
		return m.Cash
	}
	return 0
}

func (m *SysShop) GetSort() int32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *SysShop) GetComments() int32 {
	if m != nil {
		return m.Comments
	}
	return 0
}

func (m *SysShop) GetVip() int32 {
	if m != nil {
		return m.Vip
	}
	return 0
}

func (m *SysShop) GetPoint() float32 {
	if m != nil {
		return m.Point
	}
	return 0
}

func (m *SysShop) GetLogo() *SysFile {
	if m != nil {
		return m.Logo
	}
	return nil
}

func (m *SysShop) GetClassify() []*SysFile {
	if m != nil {
		return m.Classify
	}
	return nil
}

func (m *SysShop) GetUser() []*SysUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *SysShop) GetImgs() []*SysFile {
	if m != nil {
		return m.Imgs
	}
	return nil
}

func (m *SysShop) GetQualifications() []*Qualification {
	if m != nil {
		return m.Qualifications
	}
	return nil
}

func (m *SysShop) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *SysShop) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

type Product struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GoodsCode            string      `protobuf:"bytes,2,opt,name=goods_code,json=goodsCode,proto3" json:"goods_code,omitempty"`
	GoodsByname          string      `protobuf:"bytes,3,opt,name=goods_byname,json=goodsByname,proto3" json:"goods_byname,omitempty"`
	Factory              string      `protobuf:"bytes,4,opt,name=factory,proto3" json:"factory,omitempty"`
	ProAddress           string      `protobuf:"bytes,5,opt,name=pro_address,json=proAddress,proto3" json:"pro_address,omitempty"`
	ApprovalNum          string      `protobuf:"bytes,6,opt,name=approval_num,json=approvalNum,proto3" json:"approval_num,omitempty"`
	Spec                 string      `protobuf:"bytes,7,opt,name=spec,proto3" json:"spec,omitempty"`
	DosageForm           string      `protobuf:"bytes,8,opt,name=dosage_form,json=dosageForm,proto3" json:"dosage_form,omitempty"`
	Unit                 string      `protobuf:"bytes,9,opt,name=unit,proto3" json:"unit,omitempty"`
	Opcode               string      `protobuf:"bytes,10,opt,name=opcode,proto3" json:"opcode,omitempty"`
	MpackTotal           float32     `protobuf:"fixed32,11,opt,name=mpack_total,json=mpackTotal,proto3" json:"mpack_total,omitempty"`
	PackTotal            float32     `protobuf:"fixed32,12,opt,name=pack_total,json=packTotal,proto3" json:"pack_total,omitempty"`
	IsUnbundled          bool        `protobuf:"varint,13,opt,name=is_unbundled,json=isUnbundled,proto3" json:"is_unbundled,omitempty"`
	IsStop               bool        `protobuf:"varint,14,opt,name=is_stop,json=isStop,proto3" json:"is_stop,omitempty"`
	GoodsExplain         string      `protobuf:"bytes,15,opt,name=goods_explain,json=goodsExplain,proto3" json:"goods_explain,omitempty"`
	Shop                 *SysShop    `protobuf:"bytes,16,opt,name=shop,proto3" json:"shop,omitempty"`
	Imgs                 *SysFile    `protobuf:"bytes,17,opt,name=imgs,proto3" json:"imgs,omitempty"`
	ProductSkus          *ProductSku `protobuf:"bytes,18,opt,name=product_skus,json=productSkus,proto3" json:"product_skus,omitempty"`
	Created              string      `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string      `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{14}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetGoodsCode() string {
	if m != nil {
		return m.GoodsCode
	}
	return ""
}

func (m *Product) GetGoodsByname() string {
	if m != nil {
		return m.GoodsByname
	}
	return ""
}

func (m *Product) GetFactory() string {
	if m != nil {
		return m.Factory
	}
	return ""
}

func (m *Product) GetProAddress() string {
	if m != nil {
		return m.ProAddress
	}
	return ""
}

func (m *Product) GetApprovalNum() string {
	if m != nil {
		return m.ApprovalNum
	}
	return ""
}

func (m *Product) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

func (m *Product) GetDosageForm() string {
	if m != nil {
		return m.DosageForm
	}
	return ""
}

func (m *Product) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *Product) GetOpcode() string {
	if m != nil {
		return m.Opcode
	}
	return ""
}

func (m *Product) GetMpackTotal() float32 {
	if m != nil {
		return m.MpackTotal
	}
	return 0
}

func (m *Product) GetPackTotal() float32 {
	if m != nil {
		return m.PackTotal
	}
	return 0
}

func (m *Product) GetIsUnbundled() bool {
	if m != nil {
		return m.IsUnbundled
	}
	return false
}

func (m *Product) GetIsStop() bool {
	if m != nil {
		return m.IsStop
	}
	return false
}

func (m *Product) GetGoodsExplain() string {
	if m != nil {
		return m.GoodsExplain
	}
	return ""
}

func (m *Product) GetShop() *SysShop {
	if m != nil {
		return m.Shop
	}
	return nil
}

func (m *Product) GetImgs() *SysFile {
	if m != nil {
		return m.Imgs
	}
	return nil
}

func (m *Product) GetProductSkus() *ProductSku {
	if m != nil {
		return m.ProductSkus
	}
	return nil
}

func (m *Product) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Product) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

type ProductSku struct {
	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SkuName string `protobuf:"bytes,2,opt,name=sku_name,json=skuName,proto3" json:"sku_name,omitempty"`
	//Attributes: datatypes.JSON([]byte(`{"name": "jinzhu", "age": 18, "tags": ["tag1", "tag2"], "orgs": {"orga": "orga"}}`)),
	AttriListBt          []byte   `protobuf:"bytes,3,opt,name=attri_list_bt,json=attriListBt,proto3" json:"attri_list_bt,omitempty"`
	Point                float32  `protobuf:"fixed32,4,opt,name=point,proto3" json:"point,omitempty"`
	SellPrice            float32  `protobuf:"fixed32,5,opt,name=sell_price,json=sellPrice,proto3" json:"sell_price,omitempty"`
	MarketPrice          float32  `protobuf:"fixed32,6,opt,name=market_price,json=marketPrice,proto3" json:"market_price,omitempty"`
	SalePrice            float32  `protobuf:"fixed32,7,opt,name=sale_price,json=salePrice,proto3" json:"sale_price,omitempty"`
	SalePriceErp         float32  `protobuf:"fixed32,8,opt,name=sale_price_erp,json=salePriceErp,proto3" json:"sale_price_erp,omitempty"`
	Stock                float32  `protobuf:"fixed32,9,opt,name=stock,proto3" json:"stock,omitempty"`
	IsChecked            bool     `protobuf:"varint,10,opt,name=is_checked,json=isChecked,proto3" json:"is_checked,omitempty"`
	Goods                *Product `protobuf:"bytes,11,opt,name=goods,proto3" json:"goods,omitempty"`
	Created              string   `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string   `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductSku) Reset()         { *m = ProductSku{} }
func (m *ProductSku) String() string { return proto.CompactTextString(m) }
func (*ProductSku) ProtoMessage()    {}
func (*ProductSku) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{15}
}

func (m *ProductSku) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductSku.Unmarshal(m, b)
}
func (m *ProductSku) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductSku.Marshal(b, m, deterministic)
}
func (m *ProductSku) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductSku.Merge(m, src)
}
func (m *ProductSku) XXX_Size() int {
	return xxx_messageInfo_ProductSku.Size(m)
}
func (m *ProductSku) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductSku.DiscardUnknown(m)
}

var xxx_messageInfo_ProductSku proto.InternalMessageInfo

func (m *ProductSku) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProductSku) GetSkuName() string {
	if m != nil {
		return m.SkuName
	}
	return ""
}

func (m *ProductSku) GetAttriListBt() []byte {
	if m != nil {
		return m.AttriListBt
	}
	return nil
}

func (m *ProductSku) GetPoint() float32 {
	if m != nil {
		return m.Point
	}
	return 0
}

func (m *ProductSku) GetSellPrice() float32 {
	if m != nil {
		return m.SellPrice
	}
	return 0
}

func (m *ProductSku) GetMarketPrice() float32 {
	if m != nil {
		return m.MarketPrice
	}
	return 0
}

func (m *ProductSku) GetSalePrice() float32 {
	if m != nil {
		return m.SalePrice
	}
	return 0
}

func (m *ProductSku) GetSalePriceErp() float32 {
	if m != nil {
		return m.SalePriceErp
	}
	return 0
}

func (m *ProductSku) GetStock() float32 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *ProductSku) GetIsChecked() bool {
	if m != nil {
		return m.IsChecked
	}
	return false
}

func (m *ProductSku) GetGoods() *Product {
	if m != nil {
		return m.Goods
	}
	return nil
}

func (m *ProductSku) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *ProductSku) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

type Orders struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNumber          string       `protobuf:"bytes,2,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	SerialNumber         string       `protobuf:"bytes,3,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	OrderItems           []*OrderItem `protobuf:"bytes,4,rep,name=order_items,json=orderItems,proto3" json:"order_items,omitempty"`
	Created              string       `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string       `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Orders) Reset()         { *m = Orders{} }
func (m *Orders) String() string { return proto.CompactTextString(m) }
func (*Orders) ProtoMessage()    {}
func (*Orders) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{16}
}

func (m *Orders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Orders.Unmarshal(m, b)
}
func (m *Orders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Orders.Marshal(b, m, deterministic)
}
func (m *Orders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Orders.Merge(m, src)
}
func (m *Orders) XXX_Size() int {
	return xxx_messageInfo_Orders.Size(m)
}
func (m *Orders) XXX_DiscardUnknown() {
	xxx_messageInfo_Orders.DiscardUnknown(m)
}

var xxx_messageInfo_Orders proto.InternalMessageInfo

func (m *Orders) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Orders) GetOrderNumber() string {
	if m != nil {
		return m.OrderNumber
	}
	return ""
}

func (m *Orders) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *Orders) GetOrderItems() []*OrderItem {
	if m != nil {
		return m.OrderItems
	}
	return nil
}

func (m *Orders) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Orders) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

type OrderItem struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GoodsSkuId           string   `protobuf:"bytes,2,opt,name=goods_sku_id,json=goodsSkuId,proto3" json:"goods_sku_id,omitempty"`
	OrderId              string   `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Orders               *Orders  `protobuf:"bytes,4,opt,name=orders,proto3" json:"orders,omitempty"`
	UnitPrice            float32  `protobuf:"fixed32,5,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	PayUnitPrice         float32  `protobuf:"fixed32,6,opt,name=pay_unit_price,json=payUnitPrice,proto3" json:"pay_unit_price,omitempty"`
	Quantity             float32  `protobuf:"fixed32,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	SendQuantity         float32  `protobuf:"fixed32,8,opt,name=send_quantity,json=sendQuantity,proto3" json:"send_quantity,omitempty"`
	TotalPrice           float32  `protobuf:"fixed32,9,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Created              string   `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string   `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderItem) Reset()         { *m = OrderItem{} }
func (m *OrderItem) String() string { return proto.CompactTextString(m) }
func (*OrderItem) ProtoMessage()    {}
func (*OrderItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{17}
}

func (m *OrderItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderItem.Unmarshal(m, b)
}
func (m *OrderItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderItem.Marshal(b, m, deterministic)
}
func (m *OrderItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderItem.Merge(m, src)
}
func (m *OrderItem) XXX_Size() int {
	return xxx_messageInfo_OrderItem.Size(m)
}
func (m *OrderItem) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderItem.DiscardUnknown(m)
}

var xxx_messageInfo_OrderItem proto.InternalMessageInfo

func (m *OrderItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OrderItem) GetGoodsSkuId() string {
	if m != nil {
		return m.GoodsSkuId
	}
	return ""
}

func (m *OrderItem) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *OrderItem) GetOrders() *Orders {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *OrderItem) GetUnitPrice() float32 {
	if m != nil {
		return m.UnitPrice
	}
	return 0
}

func (m *OrderItem) GetPayUnitPrice() float32 {
	if m != nil {
		return m.PayUnitPrice
	}
	return 0
}

func (m *OrderItem) GetQuantity() float32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *OrderItem) GetSendQuantity() float32 {
	if m != nil {
		return m.SendQuantity
	}
	return 0
}

func (m *OrderItem) GetTotalPrice() float32 {
	if m != nil {
		return m.TotalPrice
	}
	return 0
}

func (m *OrderItem) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *OrderItem) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

func init() {
	proto.RegisterEnum("dbmodel.LoginType", LoginType_name, LoginType_value)
	proto.RegisterEnum("dbmodel.UserType", UserType_name, UserType_value)
	proto.RegisterEnum("dbmodel.FileType", FileType_name, FileType_value)
	proto.RegisterEnum("dbmodel.QuaType", QuaType_name, QuaType_value)
	proto.RegisterType((*SysUser)(nil), "dbmodel.SysUser")
	proto.RegisterType((*OnlyMenu)(nil), "dbmodel.OnlyMenu")
	proto.RegisterType((*OnlySrv)(nil), "dbmodel.OnlySrv")
	proto.RegisterType((*OnlyApi)(nil), "dbmodel.OnlyApi")
	proto.RegisterType((*SysFile)(nil), "dbmodel.SysFile")
	proto.RegisterType((*SysTree)(nil), "dbmodel.SysTree")
	proto.RegisterType((*SysGroup)(nil), "dbmodel.SysGroup")
	proto.RegisterType((*SysRole)(nil), "dbmodel.SysRole")
	proto.RegisterType((*SysMenu)(nil), "dbmodel.SysMenu")
	proto.RegisterType((*SysApi)(nil), "dbmodel.SysApi")
	proto.RegisterType((*SysSrv)(nil), "dbmodel.SysSrv")
	proto.RegisterType((*LogisticsAddress)(nil), "dbmodel.LogisticsAddress")
	proto.RegisterType((*Qualification)(nil), "dbmodel.Qualification")
	proto.RegisterType((*SysShop)(nil), "dbmodel.SysShop")
	proto.RegisterType((*Product)(nil), "dbmodel.Product")
	proto.RegisterType((*ProductSku)(nil), "dbmodel.ProductSku")
	proto.RegisterType((*Orders)(nil), "dbmodel.Orders")
	proto.RegisterType((*OrderItem)(nil), "dbmodel.OrderItem")
}

func init() { proto.RegisterFile("proto/dbmodel/dbmodel.proto", fileDescriptor_e330dd2b497970ae) }

var fileDescriptor_e330dd2b497970ae = []byte{
	// 2549 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x59, 0xcf, 0x73, 0xdb, 0xc6,
	0xf5, 0x37, 0x29, 0xfe, 0x00, 0x97, 0x94, 0x04, 0xc1, 0xb2, 0x03, 0x3b, 0xf1, 0xd7, 0x92, 0xe3,
	0xc9, 0xd7, 0x75, 0x5a, 0x67, 0x92, 0xcc, 0x74, 0x72, 0xe8, 0x74, 0x46, 0xa2, 0x68, 0x8b, 0x8d,
	0x48, 0x51, 0x20, 0x35, 0x49, 0x73, 0xc1, 0x2c, 0x81, 0x95, 0xb8, 0x43, 0x10, 0x80, 0xb0, 0x0b,
	0x59, 0xec, 0xbd, 0x87, 0xf6, 0xd4, 0x9e, 0x7b, 0xe8, 0xa5, 0xd7, 0x9e, 0xfb, 0x37, 0xf4, 0x7f,
	0xe8, 0xa9, 0x7f, 0x42, 0x7b, 0xeb, 0xa9, 0xf3, 0xde, 0xee, 0x82, 0xb4, 0x44, 0x79, 0xa6, 0x4a,
	0xa6, 0x97, 0x9e, 0xf8, 0xde, 0xe7, 0xbd, 0x5d, 0xec, 0xbe, 0x5f, 0xfb, 0x76, 0x49, 0x3e, 0x4c,
	0xb3, 0x44, 0x26, 0x9f, 0x85, 0xe3, 0x59, 0x12, 0xb2, 0xc8, 0xfc, 0xbe, 0x42, 0xd4, 0xa9, 0x6b,
	0xf6, 0xf1, 0xd3, 0xf3, 0x24, 0x39, 0x8f, 0xd8, 0x67, 0x08, 0x8f, 0xf3, 0xb3, 0xcf, 0x24, 0x9f,
	0x31, 0x21, 0xe9, 0x2c, 0x55, 0x9a, 0xcf, 0xfe, 0x64, 0x91, 0xfa, 0x70, 0x2e, 0x4e, 0x05, 0xcb,
	0x9c, 0x0d, 0x52, 0xe6, 0xa1, 0x5b, 0xda, 0x29, 0xbd, 0x68, 0x78, 0x65, 0x1e, 0x3a, 0x1f, 0x92,
	0x46, 0x2e, 0x58, 0xe6, 0xc7, 0x74, 0xc6, 0xdc, 0x32, 0xc2, 0x16, 0x00, 0x7d, 0x3a, 0x63, 0x20,
	0x94, 0x59, 0xce, 0x94, 0x70, 0x4d, 0x09, 0x01, 0x40, 0xe1, 0x13, 0x42, 0x70, 0x64, 0x3a, 0x49,
	0x62, 0xe6, 0x56, 0x50, 0x8a, 0x73, 0x0d, 0x00, 0x70, 0x3e, 0x20, 0x75, 0x14, 0xbf, 0xbd, 0x72,
	0xab, 0x28, 0xab, 0x01, 0xfb, 0xcd, 0x55, 0x31, 0x8e, 0xcd, 0x28, 0x8f, 0xdc, 0xda, 0x62, 0x5c,
	0x07, 0x80, 0x62, 0xdc, 0xc5, 0x85, 0x5b, 0x5f, 0x8c, 0x3b, 0xb9, 0x70, 0x1e, 0x11, 0x5c, 0x98,
	0x2f, 0x59, 0xe4, 0x5a, 0x28, 0x41, 0xc5, 0x11, 0x8b, 0x1c, 0x97, 0xd4, 0xc7, 0x34, 0xa2, 0x71,
	0xc0, 0xdc, 0x86, 0x92, 0x68, 0x16, 0x66, 0xe3, 0xa1, 0x1f, 0xd0, 0x2c, 0x74, 0x89, 0x9a, 0x8d,
	0x87, 0x6d, 0x9a, 0x85, 0xce, 0x36, 0xa9, 0xa6, 0x09, 0x8f, 0xa5, 0xdb, 0x44, 0x58, 0x31, 0xce,
	0x53, 0xd2, 0x4c, 0xb3, 0xe4, 0x92, 0xc7, 0x01, 0xf3, 0x79, 0xe8, 0xb6, 0x50, 0x46, 0x0c, 0xd4,
	0x0d, 0x9d, 0x1f, 0x13, 0xcb, 0x70, 0xee, 0xfa, 0x4e, 0xe9, 0x45, 0xf3, 0x0b, 0xfb, 0x95, 0x71,
	0xcb, 0x70, 0x2e, 0x46, 0x19, 0x63, 0x5e, 0xa1, 0x01, 0x5f, 0x0f, 0xb8, 0x9c, 0xc3, 0x54, 0x1b,
	0xea, 0xeb, 0xc0, 0x76, 0x43, 0xe7, 0x39, 0xa9, 0x00, 0xe5, 0x6e, 0xde, 0x32, 0x05, 0x4a, 0x61,
	0x38, 0xcd, 0x18, 0x85, 0xe1, 0xb6, 0x1a, 0x0e, 0xac, 0x1a, 0x0e, 0x94, 0xbb, 0x75, 0xdb, 0x70,
	0x90, 0x82, 0x55, 0x68, 0x18, 0x66, 0x4c, 0x08, 0xd7, 0x51, 0x56, 0xd1, 0xac, 0x63, 0x93, 0xb5,
	0x4b, 0x9e, 0xba, 0xf7, 0x77, 0x4a, 0x2f, 0xaa, 0x1e, 0x90, 0xe0, 0xe9, 0x31, 0x8d, 0xa7, 0xca,
	0xd3, 0xdb, 0xca, 0xd3, 0x00, 0xa0, 0xa7, 0x9f, 0x92, 0xe6, 0x38, 0xa3, 0x71, 0x30, 0x51, 0xe2,
	0x07, 0xca, 0x2a, 0x0a, 0x42, 0x85, 0xc7, 0x04, 0x95, 0xd1, 0xcc, 0x0f, 0x17, 0x83, 0x81, 0x77,
	0x9e, 0x93, 0x0d, 0x9c, 0x19, 0x18, 0x35, 0xfe, 0x03, 0xd4, 0x68, 0x01, 0x0a, 0xae, 0x30, 0x91,
	0x86, 0xce, 0xe5, 0x41, 0x12, 0xbb, 0xee, 0x22, 0x0c, 0xbb, 0x41, 0x12, 0xc3, 0x76, 0x11, 0x7f,
	0x74, 0x73, 0xbb, 0xaf, 0x79, 0xc4, 0x3c, 0x94, 0x3a, 0x9f, 0x90, 0x6a, 0x96, 0x44, 0x4c, 0xb8,
	0x8f, 0x77, 0xd6, 0xae, 0xab, 0x79, 0x49, 0xc4, 0x3c, 0x25, 0x76, 0x7e, 0x44, 0x6a, 0xe7, 0x59,
	0x92, 0xa7, 0xc2, 0xfd, 0x10, 0x15, 0xb7, 0x96, 0x15, 0xdf, 0x80, 0xc4, 0xd3, 0x0a, 0xce, 0x21,
	0x71, 0xa2, 0xe4, 0x9c, 0x0b, 0xc9, 0x03, 0xe1, 0x6b, 0xe3, 0x09, 0xf7, 0x23, 0x1c, 0xf6, 0xa8,
	0x18, 0x76, 0x64, 0x54, 0xf6, 0x94, 0x86, 0xb7, 0x15, 0x5d, 0x43, 0x84, 0xf3, 0x73, 0xb2, 0x71,
	0x91, 0xd3, 0x88, 0x9f, 0xf1, 0x80, 0x4a, 0x9e, 0xc4, 0xc2, 0x7d, 0x82, 0xb3, 0x3c, 0x2c, 0x66,
	0x39, 0x59, 0x16, 0x7b, 0xd7, 0xb4, 0x9d, 0x57, 0xda, 0x3e, 0x72, 0x9e, 0x32, 0xf7, 0xff, 0x76,
	0x4a, 0x2f, 0x36, 0x96, 0xd6, 0x0d, 0x89, 0x3d, 0x9a, 0xa7, 0x4c, 0x99, 0x0c, 0x28, 0xf0, 0x7d,
	0x90, 0x31, 0x2a, 0x59, 0xe8, 0x8e, 0x95, 0xef, 0x35, 0x0b, 0x92, 0x3c, 0x0d, 0x51, 0x12, 0xe8,
	0x2c, 0x52, 0xec, 0xb3, 0x2f, 0x88, 0x75, 0x1c, 0x47, 0xf3, 0x1e, 0x8b, 0x73, 0x30, 0xe6, 0x8c,
	0xc5, 0xb9, 0x70, 0x9f, 0xde, 0x34, 0x26, 0x28, 0x78, 0x4a, 0xfc, 0xec, 0x15, 0xa9, 0xc3, 0x98,
	0x61, 0x76, 0xe9, 0x7c, 0x4c, 0x2a, 0x22, 0xbb, 0x14, 0x6e, 0x09, 0x47, 0x6c, 0x2e, 0x8f, 0x18,
	0x66, 0x97, 0x1e, 0x0a, 0x8d, 0xfe, 0x5e, 0xca, 0x41, 0x9f, 0xa6, 0x7c, 0xa5, 0xfe, 0x5e, 0xca,
	0x3d, 0x14, 0x3e, 0xfb, 0x7d, 0x19, 0x4b, 0x17, 0xb8, 0xf9, 0x46, 0xe9, 0x72, 0x48, 0x65, 0xa9,
	0x6a, 0x21, 0x0d, 0x58, 0x4a, 0xe5, 0x44, 0x17, 0x2b, 0xa4, 0x01, 0x13, 0xfc, 0x57, 0xa6, 0x44,
	0x21, 0xed, 0xec, 0x92, 0xd6, 0x19, 0x8f, 0x98, 0xcf, 0xae, 0xd2, 0x88, 0xf2, 0x58, 0x97, 0xa8,
	0x26, 0x60, 0x1d, 0x05, 0xe1, 0xb0, 0x24, 0x93, 0x58, 0xa1, 0xaa, 0x1e, 0xd2, 0xe0, 0x06, 0x1c,
	0x86, 0x6e, 0xa8, 0x5f, 0x73, 0x03, 0x2c, 0x52, 0xb9, 0xe1, 0x4c, 0x53, 0x90, 0x39, 0xa8, 0x2f,
	0xf2, 0xb3, 0x33, 0x7e, 0xa5, 0xcb, 0x16, 0x01, 0x68, 0x88, 0xc8, 0x9d, 0xfc, 0xf4, 0x8f, 0x12,
	0xda, 0x04, 0x32, 0x7d, 0x95, 0x4d, 0x82, 0x24, 0x2c, 0x6c, 0x02, 0x34, 0x60, 0x92, 0x5d, 0x49,
	0x63, 0x13, 0xa0, 0x8b, 0xcd, 0x55, 0x96, 0x36, 0xb7, 0x45, 0x2a, 0x29, 0xd4, 0x1a, 0x65, 0x8b,
	0xb5, 0x54, 0x95, 0xbb, 0x60, 0xc2, 0xa3, 0x30, 0x63, 0xb1, 0x5b, 0xbb, 0x19, 0x09, 0xaa, 0xdc,
	0x19, 0x0d, 0x28, 0x2b, 0x53, 0x36, 0x77, 0x43, 0x35, 0x7e, 0xca, 0xe6, 0x50, 0x65, 0x25, 0x97,
	0x11, 0x73, 0x99, 0xaa, 0xb2, 0xc8, 0xdc, 0x69, 0xd3, 0x7f, 0x2f, 0x11, 0xcb, 0xe4, 0xe7, 0x8d,
	0x5d, 0x3f, 0x21, 0x04, 0x33, 0x76, 0xf9, 0x14, 0x6b, 0x20, 0x82, 0xc5, 0xe5, 0x63, 0xb2, 0xae,
	0xc4, 0xc6, 0xdb, 0xca, 0x12, 0x2d, 0x04, 0x8d, 0xbb, 0x8b, 0xf2, 0x51, 0x79, 0x7f, 0xf9, 0xf8,
	0x84, 0x54, 0x21, 0xcb, 0x84, 0x5b, 0xbd, 0x4d, 0x0f, 0xc5, 0x77, 0xda, 0xe4, 0xef, 0xd6, 0xd0,
	0xb3, 0x30, 0xcd, 0xaa, 0x83, 0x1a, 0x16, 0xf0, 0xce, 0x41, 0x0d, 0x00, 0xee, 0x70, 0x97, 0xb4,
	0x50, 0xf8, 0xee, 0x06, 0x9b, 0x80, 0x2d, 0xed, 0x4f, 0x65, 0x74, 0xe5, 0xbd, 0x19, 0x5d, 0xa4,
	0x71, 0xf5, 0x3d, 0x69, 0x5c, 0xe4, 0x6e, 0xed, 0x3d, 0xb9, 0xbb, 0xb0, 0x54, 0xfd, 0xe6, 0x17,
	0xa1, 0x64, 0x19, 0x4b, 0x99, 0xb8, 0xb3, 0x56, 0xc7, 0x5d, 0xe3, 0x16, 0x3b, 0xff, 0x77, 0xe2,
	0xee, 0xb7, 0x55, 0x74, 0x09, 0x16, 0xc5, 0xeb, 0x2e, 0xd1, 0xdf, 0x2d, 0x2f, 0xbe, 0xbb, 0x2a,
	0xd5, 0xb6, 0x49, 0x8d, 0xfb, 0x9f, 0x7f, 0xe5, 0xc7, 0xa6, 0x00, 0xf1, 0xcf, 0xbf, 0xea, 0x83,
	0x66, 0xc4, 0xe3, 0xa9, 0x4e, 0x36, 0xa4, 0x21, 0x4e, 0xd9, 0x95, 0x64, 0x59, 0x4c, 0x23, 0x1f,
	0x85, 0xaa, 0x39, 0x6a, 0x19, 0xf0, 0x08, 0x94, 0x1e, 0x92, 0x9a, 0xa4, 0xd9, 0x39, 0x93, 0xa6,
	0x3d, 0x52, 0x5c, 0x91, 0xd1, 0x96, 0xae, 0x72, 0x90, 0xd1, 0xdb, 0xa4, 0x3a, 0xa6, 0xe1, 0xb9,
	0xea, 0x8a, 0xaa, 0x9e, 0x62, 0xd4, 0x59, 0x1f, 0x9e, 0x33, 0x3f, 0x4c, 0x02, 0xdd, 0x15, 0x59,
	0x08, 0x1c, 0x24, 0x01, 0x44, 0x92, 0x12, 0x0a, 0x49, 0x65, 0x2e, 0x74, 0x7b, 0xd4, 0x44, 0x6c,
	0x88, 0x10, 0x6c, 0x9b, 0x06, 0x91, 0x6e, 0x8e, 0x80, 0x84, 0x6f, 0x4f, 0x78, 0xa8, 0x3a, 0x22,
	0xcb, 0x43, 0x1a, 0x7a, 0x82, 0x90, 0x0b, 0x3a, 0x8e, 0x98, 0x6a, 0x7e, 0x2c, 0xaf, 0xe0, 0x9d,
	0x97, 0xc4, 0x06, 0x9d, 0x6e, 0xbc, 0x9f, 0x31, 0x1a, 0x06, 0x59, 0x3e, 0x1b, 0x63, 0x2b, 0x64,
	0x79, 0x37, 0x70, 0x98, 0x47, 0x4c, 0x92, 0x4c, 0x06, 0xb9, 0xc4, 0x2e, 0xc8, 0xf2, 0x0a, 0x1e,
	0x0c, 0x66, 0x68, 0x3f, 0x4b, 0x12, 0x89, 0x0d, 0x91, 0xe5, 0xb5, 0x0c, 0xe8, 0x25, 0x09, 0x1a,
	0x21, 0x63, 0xb9, 0x60, 0xd8, 0x04, 0x59, 0x9e, 0x62, 0x60, 0xc9, 0xd8, 0x53, 0xdc, 0xd7, 0x3e,
	0x81, 0x0e, 0xc2, 0x04, 0xe2, 0xf6, 0xea, 0x40, 0x7c, 0x70, 0x4b, 0xe2, 0x2c, 0x02, 0x71, 0x9b,
	0x54, 0xb1, 0xa6, 0x60, 0x13, 0x64, 0x79, 0x8a, 0xf9, 0x01, 0x83, 0xf1, 0x8f, 0x25, 0x52, 0x53,
	0x29, 0x76, 0x23, 0x16, 0x5d, 0x52, 0x17, 0x2c, 0xbb, 0xe4, 0x81, 0x29, 0x0e, 0x86, 0x85, 0x80,
	0x99, 0x31, 0x39, 0x49, 0x42, 0x1d, 0x95, 0x9a, 0x83, 0xb3, 0x89, 0xa6, 0xbc, 0x28, 0x19, 0x2a,
	0x38, 0x09, 0x4d, 0xb9, 0xa9, 0x18, 0xdf, 0x63, 0x85, 0xd0, 0x0f, 0xfc, 0x20, 0x2b, 0x14, 0xd9,
	0xe5, 0xf5, 0x15, 0x8a, 0xec, 0xf2, 0xfb, 0xac, 0xf0, 0x0f, 0x6b, 0xc4, 0xbe, 0xde, 0xb1, 0xad,
	0x3a, 0x50, 0xb8, 0xf0, 0x43, 0x76, 0x46, 0xf3, 0x48, 0xe2, 0x72, 0x2d, 0xaf, 0xc1, 0xc5, 0x81,
	0x02, 0x8a, 0x3b, 0x0a, 0x2f, 0x56, 0x8c, 0xbd, 0x2a, 0x36, 0xe6, 0x40, 0xe1, 0x52, 0x57, 0x55,
	0x3c, 0x94, 0xfe, 0xaf, 0xdc, 0x32, 0xee, 0xe2, 0x9d, 0x7f, 0x95, 0xc9, 0xfa, 0x3b, 0x9d, 0xf0,
	0x0f, 0xe6, 0x9a, 0x0f, 0x48, 0x5d, 0x4c, 0x12, 0xcc, 0x6f, 0x15, 0x48, 0x35, 0x60, 0xbb, 0xa1,
	0xf3, 0x29, 0xb1, 0x2e, 0x72, 0xaa, 0x5a, 0xba, 0x2a, 0xb6, 0x74, 0xf6, 0x72, 0x53, 0x8e, 0x1d,
	0x5d, 0xfd, 0x42, 0x11, 0xce, 0x4f, 0x48, 0x03, 0x94, 0xa1, 0x83, 0x13, 0xab, 0x3a, 0x22, 0xbc,
	0x8f, 0xc0, 0x7c, 0x40, 0x08, 0xf0, 0x34, 0xa8, 0x9b, 0x08, 0x56, 0x15, 0x9b, 0x5c, 0xe4, 0xd4,
	0x44, 0xf0, 0x13, 0x02, 0x9c, 0x1f, 0xe7, 0xb3, 0x31, 0xcb, 0x74, 0xed, 0x86, 0x2f, 0xf4, 0x11,
	0x00, 0xb1, 0x90, 0x34, 0x93, 0x3e, 0x5c, 0xe9, 0xf5, 0xdd, 0xb6, 0x81, 0xc8, 0x88, 0xcf, 0x18,
	0x5c, 0x89, 0x59, 0x1c, 0x2a, 0xa1, 0x2a, 0xe4, 0x75, 0x16, 0x87, 0x28, 0xba, 0x8b, 0xf1, 0xff,
	0xac, 0xce, 0xba, 0xe1, 0x24, 0x31, 0x2d, 0x56, 0xb8, 0xdc, 0x7e, 0xa0, 0xf9, 0xb0, 0xfd, 0x50,
	0xde, 0x80, 0x3a, 0x9c, 0x9a, 0xf6, 0x03, 0x85, 0x66, 0x9f, 0x2a, 0xbf, 0x9b, 0x80, 0x99, 0x8d,
	0x3e, 0x20, 0x35, 0x2e, 0x7c, 0x31, 0x51, 0x67, 0xa3, 0xe5, 0x55, 0xb9, 0x18, 0x4e, 0xf0, 0xc2,
	0x2d, 0x26, 0xf2, 0x46, 0x8a, 0x4f, 0xe4, 0xd2, 0x38, 0x9a, 0x2e, 0xb5, 0xa5, 0x55, 0x9a, 0x82,
	0xd3, 0x3e, 0x22, 0x0d, 0x9a, 0xa6, 0x82, 0x05, 0x19, 0x93, 0xe6, 0x0d, 0xa1, 0x00, 0x54, 0x1d,
	0xa6, 0xa1, 0x6a, 0xd1, 0xcb, 0x9e, 0x62, 0xc0, 0x5a, 0x48, 0xf8, 0x6f, 0xd5, 0x03, 0x42, 0xd9,
	0xab, 0x23, 0xff, 0x4d, 0xb4, 0x10, 0x9d, 0xbd, 0x45, 0x2b, 0x1b, 0xd1, 0xeb, 0xb7, 0x0b, 0xd1,
	0x4c, 0xa0, 0x8d, 0x8d, 0xa8, 0x27, 0xb0, 0xd9, 0xa6, 0x62, 0x82, 0x67, 0x64, 0xd5, 0x43, 0xba,
	0x38, 0x86, 0x5b, 0x4b, 0x8d, 0xf5, 0x63, 0x62, 0x05, 0xc9, 0x6c, 0xc6, 0x62, 0x29, 0x30, 0x9d,
	0xab, 0x5e, 0xc1, 0x9b, 0xab, 0xf8, 0xc6, 0xe2, 0x2a, 0x5e, 0xbc, 0x4c, 0x6c, 0xaa, 0xc5, 0xab,
	0x97, 0x89, 0xe7, 0xa4, 0x12, 0x25, 0xe7, 0x09, 0xa6, 0xe8, 0xca, 0x3b, 0x30, 0x48, 0xf1, 0xb8,
	0x8a, 0xa8, 0x10, 0xfc, 0x6c, 0xee, 0x6e, 0xdd, 0x16, 0x9d, 0x46, 0xa3, 0xa8, 0x56, 0xce, 0x2d,
	0xfd, 0x99, 0xaa, 0x56, 0x70, 0xfb, 0x9e, 0x9d, 0x0b, 0xf7, 0xfe, 0x2d, 0xf3, 0xa1, 0x74, 0xc5,
	0x05, 0x77, 0xfb, 0x3f, 0xba, 0xe0, 0xde, 0x25, 0x5e, 0xff, 0x59, 0x21, 0xf5, 0x41, 0x96, 0x84,
	0x79, 0x20, 0x57, 0x5e, 0x09, 0x92, 0x24, 0x14, 0xfe, 0xd2, 0x75, 0xa8, 0x81, 0x48, 0x1b, 0xee,
	0x44, 0xbb, 0xa4, 0xa5, 0xc4, 0xe3, 0xf9, 0xd2, 0xe3, 0x56, 0x13, 0xb1, 0x7d, 0x84, 0xe0, 0xbb,
	0x67, 0x34, 0x90, 0x49, 0x36, 0xd7, 0x61, 0x69, 0x58, 0x5d, 0xbf, 0xcd, 0x83, 0x80, 0x0e, 0x4c,
	0xa8, 0xdf, 0xe6, 0x38, 0xd9, 0x25, 0x2d, 0x9a, 0x42, 0x7d, 0xa6, 0x11, 0xa4, 0xb6, 0x0e, 0xd0,
	0xa6, 0xc1, 0xfa, 0xf9, 0x0c, 0xe3, 0x24, 0x65, 0x81, 0x2e, 0x09, 0x48, 0xc3, 0xbc, 0x61, 0x22,
	0xe8, 0x39, 0xf3, 0xcf, 0x92, 0x6c, 0x66, 0x6e, 0x8b, 0x0a, 0x7a, 0x9d, 0x64, 0x38, 0x28, 0x8f,
	0xb9, 0xd4, 0x85, 0x00, 0x69, 0x38, 0x3c, 0x93, 0x14, 0x37, 0xa9, 0x1f, 0xb8, 0x14, 0x07, 0x93,
	0xcd, 0x52, 0x1a, 0x4c, 0x7d, 0x99, 0x48, 0x1a, 0x61, 0x8c, 0x96, 0x3d, 0x82, 0xd0, 0x08, 0x10,
	0xb0, 0xd0, 0x92, 0xbc, 0x85, 0xf2, 0xc6, 0x42, 0xbc, 0x4b, 0x5a, 0x5c, 0xf8, 0x79, 0x3c, 0xce,
	0xe3, 0x10, 0x7a, 0x38, 0xd5, 0xdb, 0x35, 0xb9, 0x38, 0x35, 0x10, 0x3e, 0xae, 0x09, 0x5f, 0xc8,
	0x24, 0xd5, 0x1d, 0x5e, 0x8d, 0x8b, 0xa1, 0x4c, 0x52, 0xbc, 0x70, 0xa1, 0x75, 0x4d, 0x5e, 0x6f,
	0xea, 0x0b, 0x17, 0x80, 0x26, 0xb3, 0x9f, 0x93, 0x0a, 0x14, 0x88, 0x55, 0x11, 0x0d, 0x15, 0xc8,
	0x43, 0x69, 0x11, 0x7d, 0x5b, 0xb7, 0xbe, 0xfd, 0x40, 0xf4, 0xfd, 0x94, 0xb4, 0x52, 0x15, 0x08,
	0xbe, 0x98, 0xe6, 0xea, 0x24, 0x6a, 0x7e, 0x71, 0xbf, 0xd0, 0xd6, 0x51, 0x32, 0x9c, 0xe6, 0x5e,
	0x33, 0x2d, 0xe8, 0xbb, 0x45, 0xdd, 0x6f, 0xd6, 0x08, 0x59, 0xcc, 0x77, 0x23, 0xf0, 0x1e, 0x11,
	0x4b, 0x4c, 0xf3, 0xe5, 0x6b, 0x5a, 0x5d, 0x4c, 0x73, 0x2c, 0x93, 0xcf, 0xc8, 0x3a, 0x95, 0x32,
	0xe3, 0x7e, 0xc4, 0x85, 0xf4, 0xc7, 0xaa, 0x14, 0xb6, 0xbc, 0x26, 0x82, 0x47, 0x5c, 0xc8, 0x7d,
	0xb9, 0xc8, 0xfe, 0xca, 0x72, 0xf6, 0xc3, 0x39, 0xc0, 0xa2, 0xc8, 0x4f, 0x33, 0x68, 0x9f, 0xaa,
	0xca, 0x57, 0x80, 0x0c, 0x00, 0x00, 0x5f, 0xcd, 0x68, 0x36, 0x65, 0x52, 0x2b, 0xd4, 0x50, 0xa1,
	0xa9, 0x30, 0xa5, 0x02, 0x33, 0xd0, 0x88, 0x69, 0x85, 0xba, 0x9e, 0x81, 0x46, 0x4c, 0x89, 0x9f,
	0x93, 0x8d, 0x85, 0xd8, 0x67, 0x59, 0xaa, 0x2b, 0x64, 0xab, 0x50, 0xe9, 0x64, 0x58, 0x9a, 0x84,
	0x4c, 0x82, 0xa9, 0xae, 0x91, 0x8a, 0xd1, 0x27, 0x72, 0x30, 0x61, 0xc1, 0x94, 0xa9, 0x67, 0x56,
	0x3c, 0x91, 0xdb, 0x0a, 0x80, 0x6b, 0x20, 0xfa, 0x1d, 0x43, 0x70, 0xd9, 0x85, 0xda, 0x88, 0x9e,
	0x12, 0xdf, 0xc9, 0x17, 0x7f, 0x2d, 0x91, 0xda, 0x71, 0x16, 0xc2, 0x2d, 0xf2, 0xba, 0x1f, 0x76,
	0x49, 0x2b, 0x01, 0x89, 0x39, 0x5b, 0xf5, 0x99, 0x84, 0x98, 0x3e, 0x5d, 0xe1, 0xfa, 0xc0, 0x32,
	0xae, 0x92, 0x14, 0x74, 0xf4, 0xbb, 0x80, 0x02, 0xb5, 0xd2, 0x97, 0x44, 0x8d, 0xf1, 0xb9, 0x64,
	0x33, 0x73, 0x7b, 0x76, 0x8a, 0x4d, 0xe0, 0xd7, 0xbb, 0x92, 0xcd, 0x3c, 0x92, 0x18, 0xf2, 0x6e,
	0x7b, 0xf9, 0x5b, 0x99, 0x34, 0x8a, 0xd9, 0x6e, 0x6c, 0x67, 0xc7, 0x14, 0x2c, 0x08, 0x2e, 0x1e,
	0xea, 0xed, 0xa8, 0x1a, 0x37, 0x9c, 0xe6, 0x5d, 0x0c, 0x3c, 0xbd, 0x50, 0xd3, 0xfa, 0xd4, 0xd5,
	0x8a, 0x42, 0xe7, 0xff, 0x49, 0x0d, 0x49, 0xa1, 0x1b, 0xd3, 0xcd, 0x77, 0x97, 0x2f, 0x3c, 0x2d,
	0xc6, 0xb7, 0xf9, 0x98, 0xcb, 0x77, 0xe3, 0x0c, 0x90, 0x22, 0x4a, 0x52, 0x3a, 0xf7, 0x97, 0x54,
	0x54, 0xa4, 0xb5, 0x52, 0x3a, 0x3f, 0x2d, 0xb4, 0x1e, 0x63, 0x43, 0x15, 0x4b, 0x68, 0x3d, 0x55,
	0xa0, 0x15, 0xbc, 0x32, 0x79, 0x1c, 0xfa, 0x85, 0x82, 0x09, 0x33, 0x16, 0x87, 0x27, 0x46, 0xe9,
	0x29, 0x69, 0x62, 0x51, 0xd2, 0xdf, 0x50, 0xc1, 0x46, 0x10, 0x52, 0x5f, 0xb8, 0x83, 0x79, 0x5f,
	0x7e, 0x4a, 0x1a, 0xd0, 0xf6, 0xc7, 0xd8, 0xc6, 0x59, 0xa4, 0xd2, 0xdf, 0xeb, 0x75, 0xec, 0x7b,
	0x4e, 0x83, 0x54, 0x07, 0x87, 0xc7, 0xfd, 0x8e, 0x5d, 0x02, 0xb2, 0xd3, 0xdb, 0xeb, 0x1e, 0xd9,
	0xe5, 0x97, 0x3f, 0x23, 0x96, 0x79, 0x54, 0x75, 0x5a, 0xc4, 0x1a, 0x1c, 0xed, 0x8d, 0x5e, 0x1f,
	0x7b, 0x3d, 0xfb, 0x1e, 0x8c, 0x1c, 0x1e, 0x1e, 0x0f, 0xec, 0x12, 0xe0, 0xed, 0xd3, 0xe1, 0xe8,
	0xb8, 0xd7, 0xf1, 0xec, 0xb2, 0x43, 0x48, 0x75, 0xef, 0xa0, 0xd7, 0xed, 0xdb, 0x7f, 0xf9, 0xc5,
	0xcb, 0x90, 0x58, 0xe6, 0x2d, 0xd0, 0x69, 0x92, 0xfa, 0xe9, 0xb0, 0xe3, 0x1d, 0x1d, 0xbf, 0xb1,
	0xef, 0x01, 0x03, 0x83, 0x81, 0x29, 0x39, 0x9b, 0xa4, 0x69, 0xe6, 0xed, 0xf6, 0xde, 0xd8, 0x65,
	0x00, 0xba, 0xfd, 0x83, 0xce, 0xb7, 0x47, 0xfb, 0x23, 0x00, 0xd6, 0x9c, 0x0d, 0x42, 0x06, 0xde,
	0xf1, 0xc1, 0x69, 0x1b, 0xf9, 0x0a, 0x7c, 0xf1, 0x78, 0x74, 0xd8, 0xf1, 0x80, 0xab, 0xbe, 0xfc,
	0x75, 0x99, 0xd4, 0x75, 0x7f, 0xea, 0x10, 0x52, 0xeb, 0x1e, 0xb4, 0xf7, 0xbc, 0x03, 0xfb, 0x9e,
	0xb3, 0x4e, 0x1a, 0xfb, 0x7b, 0xfd, 0xf6, 0xd7, 0xc8, 0x96, 0x60, 0x92, 0xfd, 0xee, 0x77, 0x47,
	0xdd, 0x76, 0xa7, 0x3f, 0xec, 0xd8, 0x65, 0xa7, 0x4e, 0xd6, 0x0e, 0x7a, 0x6d, 0x7b, 0x0d, 0x89,
	0x61, 0xdb, 0xae, 0x00, 0xf1, 0x66, 0x38, 0xb0, 0xab, 0x48, 0xf4, 0x06, 0x76, 0x0d, 0x88, 0xc1,
	0xa0, 0x6d, 0xd7, 0x81, 0xe8, 0x1e, 0x1c, 0xd9, 0x96, 0x53, 0x23, 0xe5, 0xf6, 0xc8, 0x6e, 0x00,
	0xd0, 0x3f, 0x68, 0xdb, 0x04, 0xd6, 0xb2, 0x37, 0x1a, 0x1d, 0x7b, 0xfd, 0xce, 0x2f, 0xed, 0x26,
	0x8e, 0x1c, 0x9d, 0xd8, 0x2d, 0x20, 0x86, 0x27, 0x6d, 0x7b, 0x1d, 0x06, 0x9c, 0x0c, 0xed, 0x0d,
	0xb0, 0xd7, 0x71, 0xb7, 0x77, 0x64, 0x6f, 0x82, 0xe8, 0xf0, 0xbb, 0x81, 0x6d, 0x03, 0xf4, 0xa6,
	0x37, 0x68, 0xdb, 0x5b, 0xb0, 0xec, 0xd1, 0xa1, 0xd7, 0xe9, 0xb4, 0x6d, 0x07, 0xac, 0xff, 0xf5,
	0xe1, 0xb7, 0x5f, 0x7f, 0x67, 0xdf, 0x37, 0x66, 0x3a, 0xf5, 0x8e, 0xec, 0x6d, 0x67, 0x9b, 0xd8,
	0x8b, 0xf5, 0xef, 0x1d, 0x78, 0x9d, 0xce, 0xd0, 0x7e, 0x00, 0xda, 0x68, 0x0a, 0xfb, 0xe1, 0xe0,
	0xde, 0xb8, 0x86, 0x7f, 0x73, 0x7d, 0xf9, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x83, 0x98,
	0xfc, 0x2f, 0x1b, 0x00, 0x00,
}
