// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/dbmodel/dbmodel.proto

package dbmodel

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Timestamp from public import google/protobuf/timestamp.proto
type Timestamp = timestamp.Timestamp

type TreeType int32

const (
	TreeType_AREA  TreeType = 0
	TreeType_PRD   TreeType = 1
	TreeType_QUA   TreeType = 2
	TreeType_USER  TreeType = 3
	TreeType_FILE  TreeType = 4
	TreeType_DEP   TreeType = 5
	TreeType_MENU  TreeType = 6
	TreeType_LOGIN TreeType = 7
	TreeType_SEX   TreeType = 8
	TreeType_OTHER TreeType = 99
)

var TreeType_name = map[int32]string{
	0:  "AREA",
	1:  "PRD",
	2:  "QUA",
	3:  "USER",
	4:  "FILE",
	5:  "DEP",
	6:  "MENU",
	7:  "LOGIN",
	8:  "SEX",
	99: "OTHER",
}

var TreeType_value = map[string]int32{
	"AREA":  0,
	"PRD":   1,
	"QUA":   2,
	"USER":  3,
	"FILE":  4,
	"DEP":   5,
	"MENU":  6,
	"LOGIN": 7,
	"SEX":   8,
	"OTHER": 99,
}

func (x TreeType) String() string {
	return proto.EnumName(TreeType_name, int32(x))
}

func (TreeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{0}
}

type LoginType int32

const (
	LoginType_NAME  LoginType = 0
	LoginType_PHONE LoginType = 1
	LoginType_EMAIL LoginType = 2
)

var LoginType_name = map[int32]string{
	0: "NAME",
	1: "PHONE",
	2: "EMAIL",
}

var LoginType_value = map[string]int32{
	"NAME":  0,
	"PHONE": 1,
	"EMAIL": 2,
}

func (x LoginType) String() string {
	return proto.EnumName(LoginType_name, int32(x))
}

func (LoginType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{1}
}

type SysUser struct {
	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName  string `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	TrueName  string `protobuf:"bytes,3,opt,name=true_name,json=trueName,proto3" json:"true_name,omitempty"`
	UserPhone string `protobuf:"bytes,4,opt,name=user_phone,json=userPhone,proto3" json:"user_phone,omitempty"`
	//string user_password=22;
	//string wx_open_id=23;
	UserWx            string              `protobuf:"bytes,5,opt,name=user_wx,json=userWx,proto3" json:"user_wx,omitempty"`
	UserEmail         string              `protobuf:"bytes,6,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	UserQq            string              `protobuf:"bytes,7,opt,name=user_qq,json=userQq,proto3" json:"user_qq,omitempty"`
	UserTel           string              `protobuf:"bytes,8,opt,name=user_tel,json=userTel,proto3" json:"user_tel,omitempty"`
	Balance           string              `protobuf:"bytes,9,opt,name=balance,proto3" json:"balance,omitempty"`
	IdCard            string              `protobuf:"bytes,10,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`
	Point             string              `protobuf:"bytes,11,opt,name=point,proto3" json:"point,omitempty"`
	ProvinceId        string              `protobuf:"bytes,12,opt,name=province_id,json=provinceId,proto3" json:"province_id,omitempty"`
	Province          *SysArea            `protobuf:"bytes,13,opt,name=province,proto3" json:"province,omitempty"`
	CityId            string              `protobuf:"bytes,14,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	City              *SysArea            `protobuf:"bytes,15,opt,name=city,proto3" json:"city,omitempty"`
	AreaId            string              `protobuf:"bytes,16,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	Area              *SysArea            `protobuf:"bytes,17,opt,name=area,proto3" json:"area,omitempty"`
	Address           string              `protobuf:"bytes,18,opt,name=address,proto3" json:"address,omitempty"`
	Vip               int32               `protobuf:"varint,19,opt,name=vip,proto3" json:"vip,omitempty"`
	BankName          string              `protobuf:"bytes,20,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	BranchName        string              `protobuf:"bytes,21,opt,name=branch_name,json=branchName,proto3" json:"branch_name,omitempty"`
	Bankcard          string              `protobuf:"bytes,22,opt,name=bankcard,proto3" json:"bankcard,omitempty"`
	BankCardName      string              `protobuf:"bytes,23,opt,name=bank_card_name,json=bankCardName,proto3" json:"bank_card_name,omitempty"`
	UserIcon          string              `protobuf:"bytes,24,opt,name=user_icon,json=userIcon,proto3" json:"user_icon,omitempty"`
	Icon              *SysFile            `protobuf:"bytes,25,opt,name=icon,proto3" json:"icon,omitempty"`
	Roles             []*SysRole          `protobuf:"bytes,26,rep,name=roles,proto3" json:"roles,omitempty"`
	Groups            []*SysGroup         `protobuf:"bytes,27,rep,name=groups,proto3" json:"groups,omitempty"`
	LogisticsAddresss []*LogisticsAddress `protobuf:"bytes,28,rep,name=logistics_addresss,json=logisticsAddresss,proto3" json:"logistics_addresss,omitempty"`
	Qualifications    []*Qualification    `protobuf:"bytes,29,rep,name=qualifications,proto3" json:"qualifications,omitempty"`
	//UserType user_type=30;
	UserType             *SysTree   `protobuf:"bytes,30,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`
	UserTypeId           string     `protobuf:"bytes,31,opt,name=user_type_id,json=userTypeId,proto3" json:"user_type_id,omitempty"`
	Shops                []*SysShop `protobuf:"bytes,32,rep,name=shops,proto3" json:"shops,omitempty"`
	Created              string     `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string     `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SysUser) Reset()         { *m = SysUser{} }
func (m *SysUser) String() string { return proto.CompactTextString(m) }
func (*SysUser) ProtoMessage()    {}
func (*SysUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{0}
}

func (m *SysUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysUser.Unmarshal(m, b)
}
func (m *SysUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysUser.Marshal(b, m, deterministic)
}
func (m *SysUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysUser.Merge(m, src)
}
func (m *SysUser) XXX_Size() int {
	return xxx_messageInfo_SysUser.Size(m)
}
func (m *SysUser) XXX_DiscardUnknown() {
	xxx_messageInfo_SysUser.DiscardUnknown(m)
}

var xxx_messageInfo_SysUser proto.InternalMessageInfo

func (m *SysUser) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SysUser) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *SysUser) GetTrueName() string {
	if m != nil {
		return m.TrueName
	}
	return ""
}

func (m *SysUser) GetUserPhone() string {
	if m != nil {
		return m.UserPhone
	}
	return ""
}

func (m *SysUser) GetUserWx() string {
	if m != nil {
		return m.UserWx
	}
	return ""
}

func (m *SysUser) GetUserEmail() string {
	if m != nil {
		return m.UserEmail
	}
	return ""
}

func (m *SysUser) GetUserQq() string {
	if m != nil {
		return m.UserQq
	}
	return ""
}

func (m *SysUser) GetUserTel() string {
	if m != nil {
		return m.UserTel
	}
	return ""
}

func (m *SysUser) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *SysUser) GetIdCard() string {
	if m != nil {
		return m.IdCard
	}
	return ""
}

func (m *SysUser) GetPoint() string {
	if m != nil {
		return m.Point
	}
	return ""
}

func (m *SysUser) GetProvinceId() string {
	if m != nil {
		return m.ProvinceId
	}
	return ""
}

func (m *SysUser) GetProvince() *SysArea {
	if m != nil {
		return m.Province
	}
	return nil
}

func (m *SysUser) GetCityId() string {
	if m != nil {
		return m.CityId
	}
	return ""
}

func (m *SysUser) GetCity() *SysArea {
	if m != nil {
		return m.City
	}
	return nil
}

func (m *SysUser) GetAreaId() string {
	if m != nil {
		return m.AreaId
	}
	return ""
}

func (m *SysUser) GetArea() *SysArea {
	if m != nil {
		return m.Area
	}
	return nil
}

func (m *SysUser) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SysUser) GetVip() int32 {
	if m != nil {
		return m.Vip
	}
	return 0
}

func (m *SysUser) GetBankName() string {
	if m != nil {
		return m.BankName
	}
	return ""
}

func (m *SysUser) GetBranchName() string {
	if m != nil {
		return m.BranchName
	}
	return ""
}

func (m *SysUser) GetBankcard() string {
	if m != nil {
		return m.Bankcard
	}
	return ""
}

func (m *SysUser) GetBankCardName() string {
	if m != nil {
		return m.BankCardName
	}
	return ""
}

func (m *SysUser) GetUserIcon() string {
	if m != nil {
		return m.UserIcon
	}
	return ""
}

func (m *SysUser) GetIcon() *SysFile {
	if m != nil {
		return m.Icon
	}
	return nil
}

func (m *SysUser) GetRoles() []*SysRole {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *SysUser) GetGroups() []*SysGroup {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *SysUser) GetLogisticsAddresss() []*LogisticsAddress {
	if m != nil {
		return m.LogisticsAddresss
	}
	return nil
}

func (m *SysUser) GetQualifications() []*Qualification {
	if m != nil {
		return m.Qualifications
	}
	return nil
}

func (m *SysUser) GetUserType() *SysTree {
	if m != nil {
		return m.UserType
	}
	return nil
}

func (m *SysUser) GetUserTypeId() string {
	if m != nil {
		return m.UserTypeId
	}
	return ""
}

func (m *SysUser) GetShops() []*SysShop {
	if m != nil {
		return m.Shops
	}
	return nil
}

func (m *SysUser) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *SysUser) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

type OnlyMenu struct {
	Menus                []*SysMenu `protobuf:"bytes,31,rep,name=menus,proto3" json:"menus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *OnlyMenu) Reset()         { *m = OnlyMenu{} }
func (m *OnlyMenu) String() string { return proto.CompactTextString(m) }
func (*OnlyMenu) ProtoMessage()    {}
func (*OnlyMenu) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{1}
}

func (m *OnlyMenu) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlyMenu.Unmarshal(m, b)
}
func (m *OnlyMenu) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlyMenu.Marshal(b, m, deterministic)
}
func (m *OnlyMenu) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlyMenu.Merge(m, src)
}
func (m *OnlyMenu) XXX_Size() int {
	return xxx_messageInfo_OnlyMenu.Size(m)
}
func (m *OnlyMenu) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlyMenu.DiscardUnknown(m)
}

var xxx_messageInfo_OnlyMenu proto.InternalMessageInfo

func (m *OnlyMenu) GetMenus() []*SysMenu {
	if m != nil {
		return m.Menus
	}
	return nil
}

type OnlySrv struct {
	Srvs                 []*SysSrv `protobuf:"bytes,1,rep,name=srvs,proto3" json:"srvs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *OnlySrv) Reset()         { *m = OnlySrv{} }
func (m *OnlySrv) String() string { return proto.CompactTextString(m) }
func (*OnlySrv) ProtoMessage()    {}
func (*OnlySrv) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{2}
}

func (m *OnlySrv) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlySrv.Unmarshal(m, b)
}
func (m *OnlySrv) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlySrv.Marshal(b, m, deterministic)
}
func (m *OnlySrv) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlySrv.Merge(m, src)
}
func (m *OnlySrv) XXX_Size() int {
	return xxx_messageInfo_OnlySrv.Size(m)
}
func (m *OnlySrv) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlySrv.DiscardUnknown(m)
}

var xxx_messageInfo_OnlySrv proto.InternalMessageInfo

func (m *OnlySrv) GetSrvs() []*SysSrv {
	if m != nil {
		return m.Srvs
	}
	return nil
}

type OnlyApi struct {
	Apis                 []*SysApi `protobuf:"bytes,1,rep,name=apis,proto3" json:"apis,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *OnlyApi) Reset()         { *m = OnlyApi{} }
func (m *OnlyApi) String() string { return proto.CompactTextString(m) }
func (*OnlyApi) ProtoMessage()    {}
func (*OnlyApi) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{3}
}

func (m *OnlyApi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlyApi.Unmarshal(m, b)
}
func (m *OnlyApi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlyApi.Marshal(b, m, deterministic)
}
func (m *OnlyApi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlyApi.Merge(m, src)
}
func (m *OnlyApi) XXX_Size() int {
	return xxx_messageInfo_OnlyApi.Size(m)
}
func (m *OnlyApi) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlyApi.DiscardUnknown(m)
}

var xxx_messageInfo_OnlyApi proto.InternalMessageInfo

func (m *OnlyApi) GetApis() []*SysApi {
	if m != nil {
		return m.Apis
	}
	return nil
}

type SysFile struct {
	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Path        string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Size        string `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`
	FileExplain string `protobuf:"bytes,5,opt,name=file_explain,json=fileExplain,proto3" json:"file_explain,omitempty"`
	Sort        int32  `protobuf:"varint,6,opt,name=sort,proto3" json:"sort,omitempty"`
	// FileType file_type=7;//图片类型
	FileType             *SysTree `protobuf:"bytes,7,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	FileTypeId           string   `protobuf:"bytes,8,opt,name=file_type_id,json=fileTypeId,proto3" json:"file_type_id,omitempty"`
	FileSuffix           string   `protobuf:"bytes,9,opt,name=file_suffix,json=fileSuffix,proto3" json:"file_suffix,omitempty"`
	Created              string   `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string   `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SysFile) Reset()         { *m = SysFile{} }
func (m *SysFile) String() string { return proto.CompactTextString(m) }
func (*SysFile) ProtoMessage()    {}
func (*SysFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{4}
}

func (m *SysFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysFile.Unmarshal(m, b)
}
func (m *SysFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysFile.Marshal(b, m, deterministic)
}
func (m *SysFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysFile.Merge(m, src)
}
func (m *SysFile) XXX_Size() int {
	return xxx_messageInfo_SysFile.Size(m)
}
func (m *SysFile) XXX_DiscardUnknown() {
	xxx_messageInfo_SysFile.DiscardUnknown(m)
}

var xxx_messageInfo_SysFile proto.InternalMessageInfo

func (m *SysFile) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SysFile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SysFile) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *SysFile) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *SysFile) GetFileExplain() string {
	if m != nil {
		return m.FileExplain
	}
	return ""
}

func (m *SysFile) GetSort() int32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *SysFile) GetFileType() *SysTree {
	if m != nil {
		return m.FileType
	}
	return nil
}

func (m *SysFile) GetFileTypeId() string {
	if m != nil {
		return m.FileTypeId
	}
	return ""
}

func (m *SysFile) GetFileSuffix() string {
	if m != nil {
		return m.FileSuffix
	}
	return ""
}

func (m *SysFile) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *SysFile) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

type SysTree struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 string     `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Text                 string     `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Sort                 int32      `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Type                 TreeType   `protobuf:"varint,7,opt,name=type,proto3,enum=dbmodel.TreeType" json:"type,omitempty"`
	PId                  string     `protobuf:"bytes,5,opt,name=p_id,json=pId,proto3" json:"p_id,omitempty"`
	Children             []*SysTree `protobuf:"bytes,6,rep,name=children,proto3" json:"children,omitempty"`
	Key                  string     `protobuf:"bytes,100,opt,name=key,proto3" json:"key,omitempty"`
	Title                string     `protobuf:"bytes,101,opt,name=title,proto3" json:"title,omitempty"`
	Created              string     `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string     `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SysTree) Reset()         { *m = SysTree{} }
func (m *SysTree) String() string { return proto.CompactTextString(m) }
func (*SysTree) ProtoMessage()    {}
func (*SysTree) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{5}
}

func (m *SysTree) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysTree.Unmarshal(m, b)
}
func (m *SysTree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysTree.Marshal(b, m, deterministic)
}
func (m *SysTree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysTree.Merge(m, src)
}
func (m *SysTree) XXX_Size() int {
	return xxx_messageInfo_SysTree.Size(m)
}
func (m *SysTree) XXX_DiscardUnknown() {
	xxx_messageInfo_SysTree.DiscardUnknown(m)
}

var xxx_messageInfo_SysTree proto.InternalMessageInfo

func (m *SysTree) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SysTree) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *SysTree) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *SysTree) GetSort() int32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *SysTree) GetType() TreeType {
	if m != nil {
		return m.Type
	}
	return TreeType_AREA
}

func (m *SysTree) GetPId() string {
	if m != nil {
		return m.PId
	}
	return ""
}

func (m *SysTree) GetChildren() []*SysTree {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *SysTree) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SysTree) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SysTree) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *SysTree) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

type SysArea struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 string     `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Text                 string     `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Sort                 int32      `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	PId                  string     `protobuf:"bytes,5,opt,name=p_id,json=pId,proto3" json:"p_id,omitempty"`
	Children             []*SysArea `protobuf:"bytes,6,rep,name=children,proto3" json:"children,omitempty"`
	ShortName            string     `protobuf:"bytes,7,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	CityCode             string     `protobuf:"bytes,8,opt,name=city_code,json=cityCode,proto3" json:"city_code,omitempty"`
	ZipCode              string     `protobuf:"bytes,9,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	MergerName           string     `protobuf:"bytes,10,opt,name=merger_name,json=mergerName,proto3" json:"merger_name,omitempty"`
	Lng                  float32    `protobuf:"fixed32,11,opt,name=lng,proto3" json:"lng,omitempty"`
	Lat                  float32    `protobuf:"fixed32,12,opt,name=lat,proto3" json:"lat,omitempty"`
	Pinyin               string     `protobuf:"bytes,13,opt,name=pinyin,proto3" json:"pinyin,omitempty"`
	Key                  string     `protobuf:"bytes,100,opt,name=key,proto3" json:"key,omitempty"`
	Title                string     `protobuf:"bytes,101,opt,name=title,proto3" json:"title,omitempty"`
	Created              string     `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string     `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SysArea) Reset()         { *m = SysArea{} }
func (m *SysArea) String() string { return proto.CompactTextString(m) }
func (*SysArea) ProtoMessage()    {}
func (*SysArea) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{6}
}

func (m *SysArea) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysArea.Unmarshal(m, b)
}
func (m *SysArea) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysArea.Marshal(b, m, deterministic)
}
func (m *SysArea) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysArea.Merge(m, src)
}
func (m *SysArea) XXX_Size() int {
	return xxx_messageInfo_SysArea.Size(m)
}
func (m *SysArea) XXX_DiscardUnknown() {
	xxx_messageInfo_SysArea.DiscardUnknown(m)
}

var xxx_messageInfo_SysArea proto.InternalMessageInfo

func (m *SysArea) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SysArea) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *SysArea) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *SysArea) GetSort() int32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *SysArea) GetPId() string {
	if m != nil {
		return m.PId
	}
	return ""
}

func (m *SysArea) GetChildren() []*SysArea {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *SysArea) GetShortName() string {
	if m != nil {
		return m.ShortName
	}
	return ""
}

func (m *SysArea) GetCityCode() string {
	if m != nil {
		return m.CityCode
	}
	return ""
}

func (m *SysArea) GetZipCode() string {
	if m != nil {
		return m.ZipCode
	}
	return ""
}

func (m *SysArea) GetMergerName() string {
	if m != nil {
		return m.MergerName
	}
	return ""
}

func (m *SysArea) GetLng() float32 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func (m *SysArea) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *SysArea) GetPinyin() string {
	if m != nil {
		return m.Pinyin
	}
	return ""
}

func (m *SysArea) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SysArea) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SysArea) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *SysArea) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

//用户组请求
type SysGroup struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupName            string     `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	GroupExplain         string     `protobuf:"bytes,3,opt,name=group_explain,json=groupExplain,proto3" json:"group_explain,omitempty"`
	Roles                []*SysRole `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	Users                []*SysRole `protobuf:"bytes,5,rep,name=users,proto3" json:"users,omitempty"`
	Created              string     `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string     `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SysGroup) Reset()         { *m = SysGroup{} }
func (m *SysGroup) String() string { return proto.CompactTextString(m) }
func (*SysGroup) ProtoMessage()    {}
func (*SysGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{7}
}

func (m *SysGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysGroup.Unmarshal(m, b)
}
func (m *SysGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysGroup.Marshal(b, m, deterministic)
}
func (m *SysGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysGroup.Merge(m, src)
}
func (m *SysGroup) XXX_Size() int {
	return xxx_messageInfo_SysGroup.Size(m)
}
func (m *SysGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_SysGroup.DiscardUnknown(m)
}

var xxx_messageInfo_SysGroup proto.InternalMessageInfo

func (m *SysGroup) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SysGroup) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *SysGroup) GetGroupExplain() string {
	if m != nil {
		return m.GroupExplain
	}
	return ""
}

func (m *SysGroup) GetRoles() []*SysRole {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *SysGroup) GetUsers() []*SysRole {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *SysGroup) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *SysGroup) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

//角色请求
type SysRole struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoleName             string     `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	RoleExplain          string     `protobuf:"bytes,3,opt,name=role_explain,json=roleExplain,proto3" json:"role_explain,omitempty"`
	Menus                []*SysMenu `protobuf:"bytes,4,rep,name=menus,proto3" json:"menus,omitempty"`
	Srvs                 []*SysSrv  `protobuf:"bytes,5,rep,name=srvs,proto3" json:"srvs,omitempty"`
	Apis                 []*SysApi  `protobuf:"bytes,6,rep,name=apis,proto3" json:"apis,omitempty"`
	Users                []*SysUser `protobuf:"bytes,7,rep,name=users,proto3" json:"users,omitempty"`
	PId                  string     `protobuf:"bytes,8,opt,name=p_id,json=pId,proto3" json:"p_id,omitempty"`
	Children             []*SysRole `protobuf:"bytes,9,rep,name=children,proto3" json:"children,omitempty"`
	Key                  string     `protobuf:"bytes,100,opt,name=key,proto3" json:"key,omitempty"`
	Title                string     `protobuf:"bytes,101,opt,name=title,proto3" json:"title,omitempty"`
	Created              string     `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string     `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SysRole) Reset()         { *m = SysRole{} }
func (m *SysRole) String() string { return proto.CompactTextString(m) }
func (*SysRole) ProtoMessage()    {}
func (*SysRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{8}
}

func (m *SysRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysRole.Unmarshal(m, b)
}
func (m *SysRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysRole.Marshal(b, m, deterministic)
}
func (m *SysRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysRole.Merge(m, src)
}
func (m *SysRole) XXX_Size() int {
	return xxx_messageInfo_SysRole.Size(m)
}
func (m *SysRole) XXX_DiscardUnknown() {
	xxx_messageInfo_SysRole.DiscardUnknown(m)
}

var xxx_messageInfo_SysRole proto.InternalMessageInfo

func (m *SysRole) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SysRole) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *SysRole) GetRoleExplain() string {
	if m != nil {
		return m.RoleExplain
	}
	return ""
}

func (m *SysRole) GetMenus() []*SysMenu {
	if m != nil {
		return m.Menus
	}
	return nil
}

func (m *SysRole) GetSrvs() []*SysSrv {
	if m != nil {
		return m.Srvs
	}
	return nil
}

func (m *SysRole) GetApis() []*SysApi {
	if m != nil {
		return m.Apis
	}
	return nil
}

func (m *SysRole) GetUsers() []*SysUser {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *SysRole) GetPId() string {
	if m != nil {
		return m.PId
	}
	return ""
}

func (m *SysRole) GetChildren() []*SysRole {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *SysRole) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SysRole) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SysRole) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *SysRole) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

type SysMenu struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key                  string     `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Text                 string     `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	I_18N                string     `protobuf:"bytes,4,opt,name=i_18_n,json=i18N,proto3" json:"i_18_n,omitempty"`
	Link                 string     `protobuf:"bytes,5,opt,name=link,proto3" json:"link,omitempty"`
	ExternalLink         string     `protobuf:"bytes,6,opt,name=external_link,json=externalLink,proto3" json:"external_link,omitempty"`
	Target               string     `protobuf:"bytes,7,opt,name=target,proto3" json:"target,omitempty"`
	Sort                 string     `protobuf:"bytes,8,opt,name=sort,proto3" json:"sort,omitempty"`
	Badge                int32      `protobuf:"varint,9,opt,name=badge,proto3" json:"badge,omitempty"`
	BadgeDoc             string     `protobuf:"bytes,10,opt,name=badge_doc,json=badgeDoc,proto3" json:"badge_doc,omitempty"`
	BadgeStatus          string     `protobuf:"bytes,11,opt,name=badge_status,json=badgeStatus,proto3" json:"badge_status,omitempty"`
	Acl                  string     `protobuf:"bytes,12,opt,name=acl,proto3" json:"acl,omitempty"`
	Hide                 bool       `protobuf:"varint,13,opt,name=hide,proto3" json:"hide,omitempty"`
	Disabled             bool       `protobuf:"varint,14,opt,name=disabled,proto3" json:"disabled,omitempty"`
	HideInBreadcrumb     bool       `protobuf:"varint,15,opt,name=hideInBreadcrumb,proto3" json:"hideInBreadcrumb,omitempty"`
	Shortcut             bool       `protobuf:"varint,16,opt,name=shortcut,proto3" json:"shortcut,omitempty"`
	ShortcutRoot         bool       `protobuf:"varint,17,opt,name=shortcut_root,json=shortcutRoot,proto3" json:"shortcut_root,omitempty"`
	Reuse                bool       `protobuf:"varint,18,opt,name=reuse,proto3" json:"reuse,omitempty"`
	Icon                 string     `protobuf:"bytes,19,opt,name=icon,proto3" json:"icon,omitempty"`
	PId                  string     `protobuf:"bytes,20,opt,name=p_id,json=pId,proto3" json:"p_id,omitempty"`
	Children             []*SysMenu `protobuf:"bytes,21,rep,name=children,proto3" json:"children,omitempty"`
	Group                bool       `protobuf:"varint,22,opt,name=group,proto3" json:"group,omitempty"`
	Title                string     `protobuf:"bytes,101,opt,name=title,proto3" json:"title,omitempty"`
	Created              string     `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string     `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SysMenu) Reset()         { *m = SysMenu{} }
func (m *SysMenu) String() string { return proto.CompactTextString(m) }
func (*SysMenu) ProtoMessage()    {}
func (*SysMenu) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{9}
}

func (m *SysMenu) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysMenu.Unmarshal(m, b)
}
func (m *SysMenu) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysMenu.Marshal(b, m, deterministic)
}
func (m *SysMenu) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysMenu.Merge(m, src)
}
func (m *SysMenu) XXX_Size() int {
	return xxx_messageInfo_SysMenu.Size(m)
}
func (m *SysMenu) XXX_DiscardUnknown() {
	xxx_messageInfo_SysMenu.DiscardUnknown(m)
}

var xxx_messageInfo_SysMenu proto.InternalMessageInfo

func (m *SysMenu) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SysMenu) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SysMenu) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *SysMenu) GetI_18N() string {
	if m != nil {
		return m.I_18N
	}
	return ""
}

func (m *SysMenu) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *SysMenu) GetExternalLink() string {
	if m != nil {
		return m.ExternalLink
	}
	return ""
}

func (m *SysMenu) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *SysMenu) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *SysMenu) GetBadge() int32 {
	if m != nil {
		return m.Badge
	}
	return 0
}

func (m *SysMenu) GetBadgeDoc() string {
	if m != nil {
		return m.BadgeDoc
	}
	return ""
}

func (m *SysMenu) GetBadgeStatus() string {
	if m != nil {
		return m.BadgeStatus
	}
	return ""
}

func (m *SysMenu) GetAcl() string {
	if m != nil {
		return m.Acl
	}
	return ""
}

func (m *SysMenu) GetHide() bool {
	if m != nil {
		return m.Hide
	}
	return false
}

func (m *SysMenu) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *SysMenu) GetHideInBreadcrumb() bool {
	if m != nil {
		return m.HideInBreadcrumb
	}
	return false
}

func (m *SysMenu) GetShortcut() bool {
	if m != nil {
		return m.Shortcut
	}
	return false
}

func (m *SysMenu) GetShortcutRoot() bool {
	if m != nil {
		return m.ShortcutRoot
	}
	return false
}

func (m *SysMenu) GetReuse() bool {
	if m != nil {
		return m.Reuse
	}
	return false
}

func (m *SysMenu) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *SysMenu) GetPId() string {
	if m != nil {
		return m.PId
	}
	return ""
}

func (m *SysMenu) GetChildren() []*SysMenu {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *SysMenu) GetGroup() bool {
	if m != nil {
		return m.Group
	}
	return false
}

func (m *SysMenu) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SysMenu) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *SysMenu) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

type SysApi struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Service              string   `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	ApiExplain           string   `protobuf:"bytes,4,opt,name=api_explain,json=apiExplain,proto3" json:"api_explain,omitempty"`
	Created              string   `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string   `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SysApi) Reset()         { *m = SysApi{} }
func (m *SysApi) String() string { return proto.CompactTextString(m) }
func (*SysApi) ProtoMessage()    {}
func (*SysApi) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{10}
}

func (m *SysApi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysApi.Unmarshal(m, b)
}
func (m *SysApi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysApi.Marshal(b, m, deterministic)
}
func (m *SysApi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysApi.Merge(m, src)
}
func (m *SysApi) XXX_Size() int {
	return xxx_messageInfo_SysApi.Size(m)
}
func (m *SysApi) XXX_DiscardUnknown() {
	xxx_messageInfo_SysApi.DiscardUnknown(m)
}

var xxx_messageInfo_SysApi proto.InternalMessageInfo

func (m *SysApi) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SysApi) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *SysApi) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *SysApi) GetApiExplain() string {
	if m != nil {
		return m.ApiExplain
	}
	return ""
}

func (m *SysApi) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *SysApi) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

type SysSrv struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Service              string   `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	SrvExplain           string   `protobuf:"bytes,4,opt,name=srv_explain,json=srvExplain,proto3" json:"srv_explain,omitempty"`
	Created              string   `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string   `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SysSrv) Reset()         { *m = SysSrv{} }
func (m *SysSrv) String() string { return proto.CompactTextString(m) }
func (*SysSrv) ProtoMessage()    {}
func (*SysSrv) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{11}
}

func (m *SysSrv) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysSrv.Unmarshal(m, b)
}
func (m *SysSrv) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysSrv.Marshal(b, m, deterministic)
}
func (m *SysSrv) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysSrv.Merge(m, src)
}
func (m *SysSrv) XXX_Size() int {
	return xxx_messageInfo_SysSrv.Size(m)
}
func (m *SysSrv) XXX_DiscardUnknown() {
	xxx_messageInfo_SysSrv.DiscardUnknown(m)
}

var xxx_messageInfo_SysSrv proto.InternalMessageInfo

func (m *SysSrv) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SysSrv) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *SysSrv) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *SysSrv) GetSrvExplain() string {
	if m != nil {
		return m.SrvExplain
	}
	return ""
}

func (m *SysSrv) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *SysSrv) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

type LogisticsAddress struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsDefault            bool     `protobuf:"varint,2,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	User                 *SysUser `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	ProvinceId           string   `protobuf:"bytes,12,opt,name=province_id,json=provinceId,proto3" json:"province_id,omitempty"`
	Province             *SysArea `protobuf:"bytes,13,opt,name=province,proto3" json:"province,omitempty"`
	CityId               string   `protobuf:"bytes,14,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	City                 *SysArea `protobuf:"bytes,15,opt,name=city,proto3" json:"city,omitempty"`
	AreaId               string   `protobuf:"bytes,16,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	Area                 *SysArea `protobuf:"bytes,17,opt,name=area,proto3" json:"area,omitempty"`
	Address              string   `protobuf:"bytes,18,opt,name=address,proto3" json:"address,omitempty"`
	Created              string   `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string   `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogisticsAddress) Reset()         { *m = LogisticsAddress{} }
func (m *LogisticsAddress) String() string { return proto.CompactTextString(m) }
func (*LogisticsAddress) ProtoMessage()    {}
func (*LogisticsAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{12}
}

func (m *LogisticsAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogisticsAddress.Unmarshal(m, b)
}
func (m *LogisticsAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogisticsAddress.Marshal(b, m, deterministic)
}
func (m *LogisticsAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogisticsAddress.Merge(m, src)
}
func (m *LogisticsAddress) XXX_Size() int {
	return xxx_messageInfo_LogisticsAddress.Size(m)
}
func (m *LogisticsAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_LogisticsAddress.DiscardUnknown(m)
}

var xxx_messageInfo_LogisticsAddress proto.InternalMessageInfo

func (m *LogisticsAddress) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LogisticsAddress) GetIsDefault() bool {
	if m != nil {
		return m.IsDefault
	}
	return false
}

func (m *LogisticsAddress) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *LogisticsAddress) GetUser() *SysUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *LogisticsAddress) GetProvinceId() string {
	if m != nil {
		return m.ProvinceId
	}
	return ""
}

func (m *LogisticsAddress) GetProvince() *SysArea {
	if m != nil {
		return m.Province
	}
	return nil
}

func (m *LogisticsAddress) GetCityId() string {
	if m != nil {
		return m.CityId
	}
	return ""
}

func (m *LogisticsAddress) GetCity() *SysArea {
	if m != nil {
		return m.City
	}
	return nil
}

func (m *LogisticsAddress) GetAreaId() string {
	if m != nil {
		return m.AreaId
	}
	return ""
}

func (m *LogisticsAddress) GetArea() *SysArea {
	if m != nil {
		return m.Area
	}
	return nil
}

func (m *LogisticsAddress) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *LogisticsAddress) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *LogisticsAddress) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

type Qualification struct {
	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsDefault bool   `protobuf:"varint,2,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	UserId    string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ShopId    string `protobuf:"bytes,4,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	//QuaType qua_type=5;
	QuaType              *SysTree   `protobuf:"bytes,5,opt,name=qua_type,json=quaType,proto3" json:"qua_type,omitempty"`
	QuaTypeId            string     `protobuf:"bytes,11,opt,name=qua_type_id,json=quaTypeId,proto3" json:"qua_type_id,omitempty"`
	QuaFiles             []*SysFile `protobuf:"bytes,6,rep,name=qua_files,json=quaFiles,proto3" json:"qua_files,omitempty"`
	QuaExplain           string     `protobuf:"bytes,7,opt,name=qua_explain,json=quaExplain,proto3" json:"qua_explain,omitempty"`
	QuaNumber            string     `protobuf:"bytes,8,opt,name=qua_number,json=quaNumber,proto3" json:"qua_number,omitempty"`
	StartTime            string     `protobuf:"bytes,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              string     `protobuf:"bytes,10,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Created              string     `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string     `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Qualification) Reset()         { *m = Qualification{} }
func (m *Qualification) String() string { return proto.CompactTextString(m) }
func (*Qualification) ProtoMessage()    {}
func (*Qualification) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{13}
}

func (m *Qualification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Qualification.Unmarshal(m, b)
}
func (m *Qualification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Qualification.Marshal(b, m, deterministic)
}
func (m *Qualification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Qualification.Merge(m, src)
}
func (m *Qualification) XXX_Size() int {
	return xxx_messageInfo_Qualification.Size(m)
}
func (m *Qualification) XXX_DiscardUnknown() {
	xxx_messageInfo_Qualification.DiscardUnknown(m)
}

var xxx_messageInfo_Qualification proto.InternalMessageInfo

func (m *Qualification) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Qualification) GetIsDefault() bool {
	if m != nil {
		return m.IsDefault
	}
	return false
}

func (m *Qualification) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Qualification) GetShopId() string {
	if m != nil {
		return m.ShopId
	}
	return ""
}

func (m *Qualification) GetQuaType() *SysTree {
	if m != nil {
		return m.QuaType
	}
	return nil
}

func (m *Qualification) GetQuaTypeId() string {
	if m != nil {
		return m.QuaTypeId
	}
	return ""
}

func (m *Qualification) GetQuaFiles() []*SysFile {
	if m != nil {
		return m.QuaFiles
	}
	return nil
}

func (m *Qualification) GetQuaExplain() string {
	if m != nil {
		return m.QuaExplain
	}
	return ""
}

func (m *Qualification) GetQuaNumber() string {
	if m != nil {
		return m.QuaNumber
	}
	return ""
}

func (m *Qualification) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *Qualification) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *Qualification) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Qualification) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

type SysShop struct {
	Id                   string           `protobuf:"bytes,100,opt,name=id,proto3" json:"id,omitempty"`
	ShopName             string           `protobuf:"bytes,1,opt,name=shop_name,json=shopName,proto3" json:"shop_name,omitempty"`
	ShopExplain          string           `protobuf:"bytes,2,opt,name=shop_explain,json=shopExplain,proto3" json:"shop_explain,omitempty"`
	IsSht                bool             `protobuf:"varint,3,opt,name=is_sht,json=isSht,proto3" json:"is_sht,omitempty"`
	ShtExplain           string           `protobuf:"bytes,4,opt,name=sht_explain,json=shtExplain,proto3" json:"sht_explain,omitempty"`
	AppId                string           `protobuf:"bytes,5,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Appsecret            string           `protobuf:"bytes,6,opt,name=appsecret,proto3" json:"appsecret,omitempty"`
	Grade                float32          `protobuf:"fixed32,7,opt,name=grade,proto3" json:"grade,omitempty"`
	GradeWl              float32          `protobuf:"fixed32,8,opt,name=grade_wl,json=gradeWl,proto3" json:"grade_wl,omitempty"`
	GradeFw              float32          `protobuf:"fixed32,9,opt,name=grade_fw,json=gradeFw,proto3" json:"grade_fw,omitempty"`
	GradeMs              float32          `protobuf:"fixed32,10,opt,name=grade_ms,json=gradeMs,proto3" json:"grade_ms,omitempty"`
	Cash                 int32            `protobuf:"varint,11,opt,name=cash,proto3" json:"cash,omitempty"`
	Sort                 int32            `protobuf:"varint,12,opt,name=sort,proto3" json:"sort,omitempty"`
	Comments             int32            `protobuf:"varint,13,opt,name=comments,proto3" json:"comments,omitempty"`
	Vip                  int32            `protobuf:"varint,14,opt,name=vip,proto3" json:"vip,omitempty"`
	Point                float32          `protobuf:"fixed32,15,opt,name=point,proto3" json:"point,omitempty"`
	Logo                 *SysFile         `protobuf:"bytes,16,opt,name=logo,proto3" json:"logo,omitempty"`
	Classify             []*SysFile       `protobuf:"bytes,17,rep,name=classify,proto3" json:"classify,omitempty"`
	User                 []*SysUser       `protobuf:"bytes,18,rep,name=user,proto3" json:"user,omitempty"`
	Imgs                 []*SysFile       `protobuf:"bytes,19,rep,name=imgs,proto3" json:"imgs,omitempty"`
	Qualifications       []*Qualification `protobuf:"bytes,20,rep,name=qualifications,proto3" json:"qualifications,omitempty"`
	ProvinceId           string           `protobuf:"bytes,21,opt,name=province_id,json=provinceId,proto3" json:"province_id,omitempty"`
	Province             *SysArea         `protobuf:"bytes,22,opt,name=province,proto3" json:"province,omitempty"`
	CityId               string           `protobuf:"bytes,23,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	City                 *SysArea         `protobuf:"bytes,24,opt,name=city,proto3" json:"city,omitempty"`
	AreaId               string           `protobuf:"bytes,25,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	Area                 *SysArea         `protobuf:"bytes,26,opt,name=area,proto3" json:"area,omitempty"`
	Address              string           `protobuf:"bytes,27,opt,name=address,proto3" json:"address,omitempty"`
	Created              string           `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string           `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SysShop) Reset()         { *m = SysShop{} }
func (m *SysShop) String() string { return proto.CompactTextString(m) }
func (*SysShop) ProtoMessage()    {}
func (*SysShop) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{14}
}

func (m *SysShop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysShop.Unmarshal(m, b)
}
func (m *SysShop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysShop.Marshal(b, m, deterministic)
}
func (m *SysShop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysShop.Merge(m, src)
}
func (m *SysShop) XXX_Size() int {
	return xxx_messageInfo_SysShop.Size(m)
}
func (m *SysShop) XXX_DiscardUnknown() {
	xxx_messageInfo_SysShop.DiscardUnknown(m)
}

var xxx_messageInfo_SysShop proto.InternalMessageInfo

func (m *SysShop) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SysShop) GetShopName() string {
	if m != nil {
		return m.ShopName
	}
	return ""
}

func (m *SysShop) GetShopExplain() string {
	if m != nil {
		return m.ShopExplain
	}
	return ""
}

func (m *SysShop) GetIsSht() bool {
	if m != nil {
		return m.IsSht
	}
	return false
}

func (m *SysShop) GetShtExplain() string {
	if m != nil {
		return m.ShtExplain
	}
	return ""
}

func (m *SysShop) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *SysShop) GetAppsecret() string {
	if m != nil {
		return m.Appsecret
	}
	return ""
}

func (m *SysShop) GetGrade() float32 {
	if m != nil {
		return m.Grade
	}
	return 0
}

func (m *SysShop) GetGradeWl() float32 {
	if m != nil {
		return m.GradeWl
	}
	return 0
}

func (m *SysShop) GetGradeFw() float32 {
	if m != nil {
		return m.GradeFw
	}
	return 0
}

func (m *SysShop) GetGradeMs() float32 {
	if m != nil {
		return m.GradeMs
	}
	return 0
}

func (m *SysShop) GetCash() int32 {
	if m != nil {
		return m.Cash
	}
	return 0
}

func (m *SysShop) GetSort() int32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *SysShop) GetComments() int32 {
	if m != nil {
		return m.Comments
	}
	return 0
}

func (m *SysShop) GetVip() int32 {
	if m != nil {
		return m.Vip
	}
	return 0
}

func (m *SysShop) GetPoint() float32 {
	if m != nil {
		return m.Point
	}
	return 0
}

func (m *SysShop) GetLogo() *SysFile {
	if m != nil {
		return m.Logo
	}
	return nil
}

func (m *SysShop) GetClassify() []*SysFile {
	if m != nil {
		return m.Classify
	}
	return nil
}

func (m *SysShop) GetUser() []*SysUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *SysShop) GetImgs() []*SysFile {
	if m != nil {
		return m.Imgs
	}
	return nil
}

func (m *SysShop) GetQualifications() []*Qualification {
	if m != nil {
		return m.Qualifications
	}
	return nil
}

func (m *SysShop) GetProvinceId() string {
	if m != nil {
		return m.ProvinceId
	}
	return ""
}

func (m *SysShop) GetProvince() *SysArea {
	if m != nil {
		return m.Province
	}
	return nil
}

func (m *SysShop) GetCityId() string {
	if m != nil {
		return m.CityId
	}
	return ""
}

func (m *SysShop) GetCity() *SysArea {
	if m != nil {
		return m.City
	}
	return nil
}

func (m *SysShop) GetAreaId() string {
	if m != nil {
		return m.AreaId
	}
	return ""
}

func (m *SysShop) GetArea() *SysArea {
	if m != nil {
		return m.Area
	}
	return nil
}

func (m *SysShop) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SysShop) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *SysShop) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

type Product struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GoodsCode            string        `protobuf:"bytes,2,opt,name=goods_code,json=goodsCode,proto3" json:"goods_code,omitempty"`
	GoodsName            string        `protobuf:"bytes,97,opt,name=goods_name,json=goodsName,proto3" json:"goods_name,omitempty"`
	GoodsByname          string        `protobuf:"bytes,3,opt,name=goods_byname,json=goodsByname,proto3" json:"goods_byname,omitempty"`
	Factory              string        `protobuf:"bytes,4,opt,name=factory,proto3" json:"factory,omitempty"`
	PrdAddress           string        `protobuf:"bytes,5,opt,name=prd_address,json=prdAddress,proto3" json:"prd_address,omitempty"`
	ApprovalNum          string        `protobuf:"bytes,6,opt,name=approval_num,json=approvalNum,proto3" json:"approval_num,omitempty"`
	Spec                 string        `protobuf:"bytes,7,opt,name=spec,proto3" json:"spec,omitempty"`
	DosageForm           string        `protobuf:"bytes,8,opt,name=dosage_form,json=dosageForm,proto3" json:"dosage_form,omitempty"`
	Unit                 string        `protobuf:"bytes,9,opt,name=unit,proto3" json:"unit,omitempty"`
	Opcode               string        `protobuf:"bytes,10,opt,name=opcode,proto3" json:"opcode,omitempty"`
	MpackTotal           float32       `protobuf:"fixed32,11,opt,name=mpack_total,json=mpackTotal,proto3" json:"mpack_total,omitempty"`
	PackTotal            float32       `protobuf:"fixed32,12,opt,name=pack_total,json=packTotal,proto3" json:"pack_total,omitempty"`
	IsUnbundled          bool          `protobuf:"varint,13,opt,name=is_unbundled,json=isUnbundled,proto3" json:"is_unbundled,omitempty"`
	IsStop               bool          `protobuf:"varint,14,opt,name=is_stop,json=isStop,proto3" json:"is_stop,omitempty"`
	GoodsExplain         string        `protobuf:"bytes,15,opt,name=goods_explain,json=goodsExplain,proto3" json:"goods_explain,omitempty"`
	Shop                 *SysShop      `protobuf:"bytes,16,opt,name=shop,proto3" json:"shop,omitempty"`
	Imgs                 []*SysFile    `protobuf:"bytes,17,rep,name=imgs,proto3" json:"imgs,omitempty"`
	ProductSkus          []*ProductSku `protobuf:"bytes,18,rep,name=product_skus,json=productSkus,proto3" json:"product_skus,omitempty"`
	ProductClassifyId    string        `protobuf:"bytes,19,opt,name=product_classify_id,json=productClassifyId,proto3" json:"product_classify_id,omitempty"`
	ProductClassify      *SysTree      `protobuf:"bytes,20,opt,name=product_classify,json=productClassify,proto3" json:"product_classify,omitempty"`
	AreaId               string        `protobuf:"bytes,21,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	Area                 *SysArea      `protobuf:"bytes,22,opt,name=area,proto3" json:"area,omitempty"`
	Created              string        `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string        `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{15}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetGoodsCode() string {
	if m != nil {
		return m.GoodsCode
	}
	return ""
}

func (m *Product) GetGoodsName() string {
	if m != nil {
		return m.GoodsName
	}
	return ""
}

func (m *Product) GetGoodsByname() string {
	if m != nil {
		return m.GoodsByname
	}
	return ""
}

func (m *Product) GetFactory() string {
	if m != nil {
		return m.Factory
	}
	return ""
}

func (m *Product) GetPrdAddress() string {
	if m != nil {
		return m.PrdAddress
	}
	return ""
}

func (m *Product) GetApprovalNum() string {
	if m != nil {
		return m.ApprovalNum
	}
	return ""
}

func (m *Product) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

func (m *Product) GetDosageForm() string {
	if m != nil {
		return m.DosageForm
	}
	return ""
}

func (m *Product) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *Product) GetOpcode() string {
	if m != nil {
		return m.Opcode
	}
	return ""
}

func (m *Product) GetMpackTotal() float32 {
	if m != nil {
		return m.MpackTotal
	}
	return 0
}

func (m *Product) GetPackTotal() float32 {
	if m != nil {
		return m.PackTotal
	}
	return 0
}

func (m *Product) GetIsUnbundled() bool {
	if m != nil {
		return m.IsUnbundled
	}
	return false
}

func (m *Product) GetIsStop() bool {
	if m != nil {
		return m.IsStop
	}
	return false
}

func (m *Product) GetGoodsExplain() string {
	if m != nil {
		return m.GoodsExplain
	}
	return ""
}

func (m *Product) GetShop() *SysShop {
	if m != nil {
		return m.Shop
	}
	return nil
}

func (m *Product) GetImgs() []*SysFile {
	if m != nil {
		return m.Imgs
	}
	return nil
}

func (m *Product) GetProductSkus() []*ProductSku {
	if m != nil {
		return m.ProductSkus
	}
	return nil
}

func (m *Product) GetProductClassifyId() string {
	if m != nil {
		return m.ProductClassifyId
	}
	return ""
}

func (m *Product) GetProductClassify() *SysTree {
	if m != nil {
		return m.ProductClassify
	}
	return nil
}

func (m *Product) GetAreaId() string {
	if m != nil {
		return m.AreaId
	}
	return ""
}

func (m *Product) GetArea() *SysArea {
	if m != nil {
		return m.Area
	}
	return nil
}

func (m *Product) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Product) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

type ProductSku struct {
	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SkuName string `protobuf:"bytes,2,opt,name=sku_name,json=skuName,proto3" json:"sku_name,omitempty"`
	//Attributes: datatypes.JSON([]byte(`{"name": "jinzhu", "age": 18, "tags": ["tag1", "tag2"], "orgs": {"orga": "orga"}}`)),
	AttriListBt  []byte  `protobuf:"bytes,3,opt,name=attri_list_bt,json=attriListBt,proto3" json:"attri_list_bt,omitempty"`
	Point        float32 `protobuf:"fixed32,4,opt,name=point,proto3" json:"point,omitempty"`
	SellPrice    float32 `protobuf:"fixed32,5,opt,name=sell_price,json=sellPrice,proto3" json:"sell_price,omitempty"`
	MarketPrice  float32 `protobuf:"fixed32,6,opt,name=market_price,json=marketPrice,proto3" json:"market_price,omitempty"`
	SalePrice    float32 `protobuf:"fixed32,7,opt,name=sale_price,json=salePrice,proto3" json:"sale_price,omitempty"`
	SalePriceErp float32 `protobuf:"fixed32,8,opt,name=sale_price_erp,json=salePriceErp,proto3" json:"sale_price_erp,omitempty"`
	Stock        float32 `protobuf:"fixed32,9,opt,name=stock,proto3" json:"stock,omitempty"`
	IsChecked    bool    `protobuf:"varint,10,opt,name=is_checked,json=isChecked,proto3" json:"is_checked,omitempty"`
	//float  mpack_total = 11;//中包装数量
	//float pack_total = 12;//件包装数量
	BatchNumber          string     `protobuf:"bytes,11,opt,name=batch_number,json=batchNumber,proto3" json:"batch_number,omitempty"`
	ProdutionDate        string     `protobuf:"bytes,12,opt,name=prodution_date,json=produtionDate,proto3" json:"prodution_date,omitempty"`
	EffectiveDate        string     `protobuf:"bytes,13,opt,name=effective_date,json=effectiveDate,proto3" json:"effective_date,omitempty"`
	Goods                *Product   `protobuf:"bytes,14,opt,name=goods,proto3" json:"goods,omitempty"`
	Imgs                 []*SysFile `protobuf:"bytes,15,rep,name=imgs,proto3" json:"imgs,omitempty"`
	ProductId            string     `protobuf:"bytes,16,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	CostPrice            float32    `protobuf:"fixed32,17,opt,name=cost_price,json=costPrice,proto3" json:"cost_price,omitempty"`
	Created              string     `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string     `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProductSku) Reset()         { *m = ProductSku{} }
func (m *ProductSku) String() string { return proto.CompactTextString(m) }
func (*ProductSku) ProtoMessage()    {}
func (*ProductSku) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{16}
}

func (m *ProductSku) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductSku.Unmarshal(m, b)
}
func (m *ProductSku) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductSku.Marshal(b, m, deterministic)
}
func (m *ProductSku) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductSku.Merge(m, src)
}
func (m *ProductSku) XXX_Size() int {
	return xxx_messageInfo_ProductSku.Size(m)
}
func (m *ProductSku) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductSku.DiscardUnknown(m)
}

var xxx_messageInfo_ProductSku proto.InternalMessageInfo

func (m *ProductSku) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProductSku) GetSkuName() string {
	if m != nil {
		return m.SkuName
	}
	return ""
}

func (m *ProductSku) GetAttriListBt() []byte {
	if m != nil {
		return m.AttriListBt
	}
	return nil
}

func (m *ProductSku) GetPoint() float32 {
	if m != nil {
		return m.Point
	}
	return 0
}

func (m *ProductSku) GetSellPrice() float32 {
	if m != nil {
		return m.SellPrice
	}
	return 0
}

func (m *ProductSku) GetMarketPrice() float32 {
	if m != nil {
		return m.MarketPrice
	}
	return 0
}

func (m *ProductSku) GetSalePrice() float32 {
	if m != nil {
		return m.SalePrice
	}
	return 0
}

func (m *ProductSku) GetSalePriceErp() float32 {
	if m != nil {
		return m.SalePriceErp
	}
	return 0
}

func (m *ProductSku) GetStock() float32 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *ProductSku) GetIsChecked() bool {
	if m != nil {
		return m.IsChecked
	}
	return false
}

func (m *ProductSku) GetBatchNumber() string {
	if m != nil {
		return m.BatchNumber
	}
	return ""
}

func (m *ProductSku) GetProdutionDate() string {
	if m != nil {
		return m.ProdutionDate
	}
	return ""
}

func (m *ProductSku) GetEffectiveDate() string {
	if m != nil {
		return m.EffectiveDate
	}
	return ""
}

func (m *ProductSku) GetGoods() *Product {
	if m != nil {
		return m.Goods
	}
	return nil
}

func (m *ProductSku) GetImgs() []*SysFile {
	if m != nil {
		return m.Imgs
	}
	return nil
}

func (m *ProductSku) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *ProductSku) GetCostPrice() float32 {
	if m != nil {
		return m.CostPrice
	}
	return 0
}

func (m *ProductSku) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *ProductSku) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

type Orders struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNumber          string       `protobuf:"bytes,2,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	SerialNumber         string       `protobuf:"bytes,3,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	OrderItems           []*OrderItem `protobuf:"bytes,4,rep,name=order_items,json=orderItems,proto3" json:"order_items,omitempty"`
	ProvinceId           string       `protobuf:"bytes,12,opt,name=province_id,json=provinceId,proto3" json:"province_id,omitempty"`
	Province             *SysArea     `protobuf:"bytes,13,opt,name=province,proto3" json:"province,omitempty"`
	CityId               string       `protobuf:"bytes,14,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	City                 *SysArea     `protobuf:"bytes,15,opt,name=city,proto3" json:"city,omitempty"`
	AreaId               string       `protobuf:"bytes,16,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	Area                 *SysArea     `protobuf:"bytes,17,opt,name=area,proto3" json:"area,omitempty"`
	Address              string       `protobuf:"bytes,18,opt,name=address,proto3" json:"address,omitempty"`
	Created              string       `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string       `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Orders) Reset()         { *m = Orders{} }
func (m *Orders) String() string { return proto.CompactTextString(m) }
func (*Orders) ProtoMessage()    {}
func (*Orders) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{17}
}

func (m *Orders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Orders.Unmarshal(m, b)
}
func (m *Orders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Orders.Marshal(b, m, deterministic)
}
func (m *Orders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Orders.Merge(m, src)
}
func (m *Orders) XXX_Size() int {
	return xxx_messageInfo_Orders.Size(m)
}
func (m *Orders) XXX_DiscardUnknown() {
	xxx_messageInfo_Orders.DiscardUnknown(m)
}

var xxx_messageInfo_Orders proto.InternalMessageInfo

func (m *Orders) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Orders) GetOrderNumber() string {
	if m != nil {
		return m.OrderNumber
	}
	return ""
}

func (m *Orders) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *Orders) GetOrderItems() []*OrderItem {
	if m != nil {
		return m.OrderItems
	}
	return nil
}

func (m *Orders) GetProvinceId() string {
	if m != nil {
		return m.ProvinceId
	}
	return ""
}

func (m *Orders) GetProvince() *SysArea {
	if m != nil {
		return m.Province
	}
	return nil
}

func (m *Orders) GetCityId() string {
	if m != nil {
		return m.CityId
	}
	return ""
}

func (m *Orders) GetCity() *SysArea {
	if m != nil {
		return m.City
	}
	return nil
}

func (m *Orders) GetAreaId() string {
	if m != nil {
		return m.AreaId
	}
	return ""
}

func (m *Orders) GetArea() *SysArea {
	if m != nil {
		return m.Area
	}
	return nil
}

func (m *Orders) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Orders) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Orders) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

type OrderItem struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GoodsSkuId           string   `protobuf:"bytes,2,opt,name=goods_sku_id,json=goodsSkuId,proto3" json:"goods_sku_id,omitempty"`
	OrderId              string   `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Orders               *Orders  `protobuf:"bytes,4,opt,name=orders,proto3" json:"orders,omitempty"`
	UnitPrice            float32  `protobuf:"fixed32,5,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	PayUnitPrice         float32  `protobuf:"fixed32,6,opt,name=pay_unit_price,json=payUnitPrice,proto3" json:"pay_unit_price,omitempty"`
	Quantity             float32  `protobuf:"fixed32,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	SendQuantity         float32  `protobuf:"fixed32,8,opt,name=send_quantity,json=sendQuantity,proto3" json:"send_quantity,omitempty"`
	TotalPrice           float32  `protobuf:"fixed32,9,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Created              string   `protobuf:"bytes,98,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string   `protobuf:"bytes,99,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderItem) Reset()         { *m = OrderItem{} }
func (m *OrderItem) String() string { return proto.CompactTextString(m) }
func (*OrderItem) ProtoMessage()    {}
func (*OrderItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_e330dd2b497970ae, []int{18}
}

func (m *OrderItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderItem.Unmarshal(m, b)
}
func (m *OrderItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderItem.Marshal(b, m, deterministic)
}
func (m *OrderItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderItem.Merge(m, src)
}
func (m *OrderItem) XXX_Size() int {
	return xxx_messageInfo_OrderItem.Size(m)
}
func (m *OrderItem) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderItem.DiscardUnknown(m)
}

var xxx_messageInfo_OrderItem proto.InternalMessageInfo

func (m *OrderItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OrderItem) GetGoodsSkuId() string {
	if m != nil {
		return m.GoodsSkuId
	}
	return ""
}

func (m *OrderItem) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *OrderItem) GetOrders() *Orders {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *OrderItem) GetUnitPrice() float32 {
	if m != nil {
		return m.UnitPrice
	}
	return 0
}

func (m *OrderItem) GetPayUnitPrice() float32 {
	if m != nil {
		return m.PayUnitPrice
	}
	return 0
}

func (m *OrderItem) GetQuantity() float32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *OrderItem) GetSendQuantity() float32 {
	if m != nil {
		return m.SendQuantity
	}
	return 0
}

func (m *OrderItem) GetTotalPrice() float32 {
	if m != nil {
		return m.TotalPrice
	}
	return 0
}

func (m *OrderItem) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *OrderItem) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

func init() {
	proto.RegisterEnum("dbmodel.TreeType", TreeType_name, TreeType_value)
	proto.RegisterEnum("dbmodel.LoginType", LoginType_name, LoginType_value)
	proto.RegisterType((*SysUser)(nil), "dbmodel.SysUser")
	proto.RegisterType((*OnlyMenu)(nil), "dbmodel.OnlyMenu")
	proto.RegisterType((*OnlySrv)(nil), "dbmodel.OnlySrv")
	proto.RegisterType((*OnlyApi)(nil), "dbmodel.OnlyApi")
	proto.RegisterType((*SysFile)(nil), "dbmodel.SysFile")
	proto.RegisterType((*SysTree)(nil), "dbmodel.SysTree")
	proto.RegisterType((*SysArea)(nil), "dbmodel.SysArea")
	proto.RegisterType((*SysGroup)(nil), "dbmodel.SysGroup")
	proto.RegisterType((*SysRole)(nil), "dbmodel.SysRole")
	proto.RegisterType((*SysMenu)(nil), "dbmodel.SysMenu")
	proto.RegisterType((*SysApi)(nil), "dbmodel.SysApi")
	proto.RegisterType((*SysSrv)(nil), "dbmodel.SysSrv")
	proto.RegisterType((*LogisticsAddress)(nil), "dbmodel.LogisticsAddress")
	proto.RegisterType((*Qualification)(nil), "dbmodel.Qualification")
	proto.RegisterType((*SysShop)(nil), "dbmodel.SysShop")
	proto.RegisterType((*Product)(nil), "dbmodel.Product")
	proto.RegisterType((*ProductSku)(nil), "dbmodel.ProductSku")
	proto.RegisterType((*Orders)(nil), "dbmodel.Orders")
	proto.RegisterType((*OrderItem)(nil), "dbmodel.OrderItem")
}

func init() { proto.RegisterFile("proto/dbmodel/dbmodel.proto", fileDescriptor_e330dd2b497970ae) }

var fileDescriptor_e330dd2b497970ae = []byte{
	// 2638 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x59, 0xcf, 0x6f, 0x1b, 0xc7,
	0xf5, 0x8f, 0x24, 0xfe, 0x58, 0x0e, 0x69, 0x89, 0x5a, 0xcb, 0xf6, 0x5a, 0x8e, 0x23, 0xd9, 0x51,
	0xf2, 0xcd, 0x37, 0x69, 0x1d, 0x24, 0x01, 0x8a, 0x00, 0x05, 0x0a, 0x28, 0x36, 0x9d, 0x10, 0x90,
	0x65, 0x79, 0x29, 0x21, 0xbd, 0x2d, 0x86, 0xbb, 0x43, 0x72, 0xc0, 0xe5, 0xee, 0x6a, 0x67, 0x56,
	0x16, 0xf3, 0x27, 0xf4, 0xd4, 0x43, 0x2f, 0x6d, 0x0f, 0xbd, 0xf5, 0x5c, 0xf4, 0x0f, 0xe8, 0x5f,
	0x52, 0xf4, 0xd0, 0x7b, 0xff, 0x87, 0xe2, 0xbd, 0x37, 0xb3, 0xa4, 0x44, 0x4a, 0x8d, 0x65, 0xb7,
	0x97, 0xf6, 0xc4, 0x99, 0xcf, 0x7b, 0x33, 0x3b, 0xf3, 0x7e, 0x7c, 0xe6, 0xcd, 0x90, 0x3d, 0xc8,
	0xf2, 0x54, 0xa7, 0x9f, 0x47, 0xfd, 0x49, 0x1a, 0x89, 0xd8, 0xfe, 0x3e, 0x41, 0xd4, 0xad, 0x9b,
	0xee, 0xf6, 0xce, 0x30, 0x4d, 0x87, 0xb1, 0xf8, 0x1c, 0xe1, 0x7e, 0x31, 0xf8, 0x5c, 0xcb, 0x89,
	0x50, 0x9a, 0x4f, 0x32, 0xd2, 0x7c, 0xfc, 0x0f, 0x87, 0xd5, 0x7b, 0x53, 0x75, 0xa2, 0x44, 0xee,
	0xae, 0xb3, 0x55, 0x19, 0x79, 0x2b, 0xbb, 0x2b, 0x9f, 0x34, 0xfc, 0x55, 0x19, 0xb9, 0x0f, 0x58,
	0xa3, 0x50, 0x22, 0x0f, 0x12, 0x3e, 0x11, 0xde, 0x2a, 0xc2, 0x0e, 0x00, 0x87, 0x7c, 0x22, 0x40,
	0xa8, 0xf3, 0x42, 0x90, 0x70, 0x8d, 0x84, 0x00, 0xa0, 0xf0, 0x21, 0x63, 0x38, 0x32, 0x1b, 0xa5,
	0x89, 0xf0, 0x2a, 0x28, 0xc5, 0xb9, 0x8e, 0x00, 0x70, 0xef, 0xb1, 0x3a, 0x8a, 0x5f, 0x9f, 0x7b,
	0x55, 0x94, 0xd5, 0xa0, 0xfb, 0xfd, 0x79, 0x39, 0x4e, 0x4c, 0xb8, 0x8c, 0xbd, 0xda, 0x6c, 0x5c,
	0x07, 0x80, 0x72, 0xdc, 0xe9, 0xa9, 0x57, 0x9f, 0x8d, 0x7b, 0x75, 0xea, 0xde, 0x67, 0xb8, 0xb0,
	0x40, 0x8b, 0xd8, 0x73, 0x50, 0x82, 0x8a, 0xc7, 0x22, 0x76, 0x3d, 0x56, 0xef, 0xf3, 0x98, 0x27,
	0xa1, 0xf0, 0x1a, 0x24, 0x31, 0x5d, 0x98, 0x4d, 0x46, 0x41, 0xc8, 0xf3, 0xc8, 0x63, 0x34, 0x9b,
	0x8c, 0x9e, 0xf2, 0x3c, 0x72, 0xb7, 0x58, 0x35, 0x4b, 0x65, 0xa2, 0xbd, 0x26, 0xc2, 0xd4, 0x71,
	0x77, 0x58, 0x33, 0xcb, 0xd3, 0x33, 0x99, 0x84, 0x22, 0x90, 0x91, 0xd7, 0x42, 0x19, 0xb3, 0x50,
	0x37, 0x72, 0x7f, 0xc2, 0x1c, 0xdb, 0xf3, 0x6e, 0xed, 0xae, 0x7c, 0xd2, 0xfc, 0xb2, 0xfd, 0xc4,
	0xba, 0xa5, 0x37, 0x55, 0xfb, 0xb9, 0xe0, 0x7e, 0xa9, 0x01, 0x5f, 0x0f, 0xa5, 0x9e, 0xc2, 0x54,
	0xeb, 0xf4, 0x75, 0xe8, 0x76, 0x23, 0x77, 0x8f, 0x55, 0xa0, 0xe5, 0x6d, 0x5c, 0x31, 0x05, 0x4a,
	0x61, 0x38, 0xcf, 0x05, 0x87, 0xe1, 0x6d, 0x1a, 0x0e, 0x5d, 0x1a, 0x0e, 0x2d, 0x6f, 0xf3, 0xaa,
	0xe1, 0x20, 0x05, 0xab, 0xf0, 0x28, 0xca, 0x85, 0x52, 0x9e, 0x4b, 0x56, 0x31, 0x5d, 0xb7, 0xcd,
	0xd6, 0xce, 0x64, 0xe6, 0xdd, 0xde, 0x5d, 0xf9, 0xa4, 0xea, 0x43, 0x13, 0x3c, 0xdd, 0xe7, 0xc9,
	0x98, 0x3c, 0xbd, 0x45, 0x9e, 0x06, 0x00, 0x3d, 0xbd, 0xc3, 0x9a, 0xfd, 0x9c, 0x27, 0xe1, 0x88,
	0xc4, 0x77, 0xc8, 0x2a, 0x04, 0xa1, 0xc2, 0x36, 0x43, 0x65, 0x34, 0xf3, 0xdd, 0xd9, 0x60, 0xe8,
	0xbb, 0x7b, 0x6c, 0x1d, 0x67, 0x86, 0x0e, 0x8d, 0xbf, 0x87, 0x1a, 0x2d, 0x40, 0xc1, 0x15, 0x36,
	0xd2, 0xd0, 0xb9, 0x32, 0x4c, 0x13, 0xcf, 0x9b, 0x85, 0x61, 0x37, 0x4c, 0x13, 0xd8, 0x2e, 0xe2,
	0xf7, 0x17, 0xb7, 0xfb, 0x5c, 0xc6, 0xc2, 0x47, 0xa9, 0xfb, 0x31, 0xab, 0xe6, 0x69, 0x2c, 0x94,
	0xb7, 0xbd, 0xbb, 0x76, 0x59, 0xcd, 0x4f, 0x63, 0xe1, 0x93, 0xd8, 0xfd, 0x7f, 0x56, 0x1b, 0xe6,
	0x69, 0x91, 0x29, 0xef, 0x01, 0x2a, 0x6e, 0xce, 0x2b, 0x7e, 0x0b, 0x12, 0xdf, 0x28, 0xb8, 0xdf,
	0x31, 0x37, 0x4e, 0x87, 0x52, 0x69, 0x19, 0xaa, 0xc0, 0x18, 0x4f, 0x79, 0xef, 0xe3, 0xb0, 0xfb,
	0xe5, 0xb0, 0x03, 0xab, 0xb2, 0x4f, 0x1a, 0xfe, 0x66, 0x7c, 0x09, 0x51, 0xee, 0x2f, 0xd8, 0xfa,
	0x69, 0xc1, 0x63, 0x39, 0x90, 0x21, 0xd7, 0x32, 0x4d, 0x94, 0xf7, 0x10, 0x67, 0xb9, 0x5b, 0xce,
	0xf2, 0x6a, 0x5e, 0xec, 0x5f, 0xd2, 0x76, 0x7f, 0x6a, 0xec, 0xa3, 0xa7, 0x99, 0xf0, 0x3e, 0x58,
	0xb4, 0xc3, 0x71, 0x2e, 0x04, 0x59, 0xec, 0x78, 0x9a, 0x09, 0x77, 0x97, 0xb5, 0x4a, 0x75, 0x08,
	0x9f, 0x1d, 0x72, 0x99, 0x95, 0x77, 0x23, 0xb0, 0x96, 0x1a, 0xa5, 0x99, 0xf2, 0x76, 0x17, 0xad,
	0xd5, 0x1b, 0xa5, 0x99, 0x4f, 0x62, 0x08, 0xa2, 0x30, 0x17, 0x5c, 0x8b, 0xc8, 0xeb, 0x53, 0x10,
	0x99, 0x2e, 0x48, 0x8a, 0x2c, 0x42, 0x49, 0x68, 0xd2, 0x91, 0xba, 0x8f, 0xbf, 0x64, 0xce, 0xcb,
	0x24, 0x9e, 0xbe, 0x10, 0x49, 0x01, 0xdf, 0x99, 0x88, 0xa4, 0x50, 0xde, 0xce, 0xe2, 0x77, 0x40,
	0xc1, 0x27, 0xf1, 0xe3, 0x27, 0xac, 0x0e, 0x63, 0x7a, 0xf9, 0x99, 0xfb, 0x21, 0xab, 0xa8, 0xfc,
	0x4c, 0x79, 0x2b, 0x38, 0x62, 0xe3, 0xc2, 0xca, 0xf2, 0x33, 0x1f, 0x85, 0x56, 0x7f, 0x3f, 0x93,
	0xa0, 0xcf, 0x33, 0xb9, 0x54, 0x7f, 0x3f, 0x93, 0x3e, 0x0a, 0x1f, 0xff, 0x79, 0x15, 0x39, 0x10,
	0xe2, 0x65, 0x81, 0x03, 0x5d, 0x56, 0x99, 0xa3, 0x3f, 0x6c, 0x03, 0x96, 0x71, 0x3d, 0x32, 0xac,
	0x87, 0x6d, 0xc0, 0x94, 0xfc, 0xc1, 0x72, 0x1d, 0xb6, 0xdd, 0x47, 0xac, 0x35, 0x90, 0xb1, 0x08,
	0xc4, 0x79, 0x16, 0x73, 0x99, 0x18, 0xae, 0x6b, 0x02, 0xd6, 0x21, 0x08, 0x87, 0xa5, 0xb9, 0x46,
	0xaa, 0xab, 0xfa, 0xd8, 0x06, 0x7f, 0xe2, 0x30, 0xf4, 0x67, 0xfd, 0x2a, 0x7f, 0x82, 0x8a, 0xf5,
	0x67, 0xa9, 0x0e, 0xfe, 0x24, 0xfe, 0x63, 0x56, 0xde, 0x8d, 0x20, 0x47, 0x51, 0x43, 0x15, 0x83,
	0x81, 0x3c, 0x37, 0x34, 0x88, 0x0a, 0x3d, 0x44, 0x6e, 0xe4, 0xc8, 0xdf, 0x92, 0xd1, 0x60, 0x31,
	0xcb, 0x8c, 0x16, 0xa6, 0x51, 0x69, 0x34, 0x68, 0x03, 0xa6, 0xc5, 0xb9, 0xb6, 0x46, 0x83, 0x76,
	0xb9, 0xfb, 0xca, 0xdc, 0xee, 0x3f, 0x62, 0x95, 0x72, 0xe3, 0xeb, 0x73, 0x09, 0x08, 0x1f, 0x82,
	0xfd, 0xf8, 0x28, 0x76, 0x37, 0x59, 0x25, 0x83, 0xdd, 0x92, 0x4d, 0xd7, 0x32, 0xe2, 0xdf, 0x70,
	0x24, 0xe3, 0x28, 0x17, 0x89, 0x57, 0x5b, 0x8c, 0x28, 0x32, 0x9b, 0xd5, 0x00, 0x9e, 0x1b, 0x8b,
	0xa9, 0x17, 0xd1, 0xf8, 0xb1, 0x98, 0x02, 0xed, 0x6b, 0xa9, 0x63, 0xe1, 0x09, 0xa2, 0x7d, 0xec,
	0xdc, 0xc8, 0x36, 0x7f, 0x5c, 0x43, 0xdb, 0x00, 0xdf, 0xbe, 0x53, 0xdb, 0xbc, 0xf9, 0xa6, 0xe9,
	0xd0, 0x29, 0x37, 0xfd, 0x90, 0x31, 0x35, 0x4a, 0x73, 0x4d, 0x64, 0x4b, 0x67, 0x68, 0x03, 0x11,
	0xcb, 0xb4, 0x78, 0x26, 0xe1, 0x02, 0x29, 0x8e, 0x1c, 0x00, 0x9e, 0xc2, 0x22, 0xef, 0x33, 0xe7,
	0x07, 0x99, 0x91, 0xcc, 0x9c, 0xa4, 0x3f, 0xc8, 0x0c, 0x45, 0x3b, 0xac, 0x39, 0x11, 0xf9, 0xd0,
	0x96, 0x0a, 0x74, 0x9a, 0x32, 0x82, 0x70, 0xe2, 0x36, 0x5b, 0x8b, 0x93, 0x21, 0x9e, 0xa7, 0xab,
	0x3e, 0x34, 0x11, 0xe1, 0x1a, 0x4f, 0x51, 0x40, 0xb8, 0x76, 0xef, 0xb2, 0x5a, 0x26, 0x93, 0xa9,
	0x4c, 0xf0, 0xf0, 0x6c, 0xf8, 0xa6, 0xf7, 0x6f, 0x75, 0xd4, 0xdf, 0x57, 0x98, 0x63, 0x99, 0x7d,
	0xc1, 0x53, 0x0f, 0x19, 0x43, 0xae, 0x9f, 0xaf, 0x7f, 0x1a, 0x88, 0xe0, 0x9e, 0x3e, 0x64, 0xb7,
	0x48, 0x6c, 0xd3, 0x9b, 0xbc, 0xd7, 0x42, 0xd0, 0xe6, 0x77, 0x79, 0xf0, 0x54, 0xae, 0x3f, 0x78,
	0x3e, 0x66, 0x55, 0x20, 0x60, 0xe5, 0x55, 0xaf, 0xd2, 0x43, 0xf1, 0x8d, 0x36, 0xf9, 0x6b, 0x8a,
	0x46, 0x98, 0x66, 0x59, 0x89, 0x07, 0x0b, 0xb8, 0x50, 0xe2, 0x01, 0x80, 0x3b, 0x7c, 0xc4, 0x5a,
	0x28, 0xbc, 0xb8, 0xc1, 0x26, 0x60, 0x73, 0xfb, 0x23, 0x0a, 0xaf, 0x5c, 0x4b, 0xe1, 0x25, 0x6f,
	0x57, 0xaf, 0xe1, 0xed, 0x92, 0xac, 0x6b, 0xd7, 0x90, 0xf5, 0xcc, 0x52, 0xf5, 0xc5, 0x2f, 0x42,
	0x15, 0x6b, 0x2d, 0x65, 0x73, 0xc5, 0x59, 0x9e, 0x2b, 0x8d, 0x2b, 0xec, 0xfc, 0x9f, 0x21, 0x88,
	0x5f, 0x55, 0xd1, 0x25, 0x78, 0x0a, 0x5e, 0x76, 0x89, 0xf9, 0xee, 0xea, 0xec, 0xbb, 0xcb, 0xe8,
	0x61, 0x8b, 0xd5, 0x64, 0xf0, 0xc5, 0xd7, 0x41, 0x62, 0x4f, 0x1c, 0xf9, 0xc5, 0xd7, 0x87, 0xa0,
	0x19, 0xcb, 0x64, 0x6c, 0x08, 0x02, 0xdb, 0x10, 0xa7, 0xe2, 0x5c, 0x8b, 0x3c, 0xe1, 0x71, 0x80,
	0x42, 0x2a, 0xab, 0x5b, 0x16, 0x3c, 0x00, 0xa5, 0xbb, 0xac, 0xa6, 0x79, 0x3e, 0x14, 0xda, 0x16,
	0xd6, 0xd4, 0x2b, 0x59, 0xc8, 0x31, 0xc7, 0x1a, 0xb0, 0xd0, 0x16, 0xab, 0xf6, 0x79, 0x34, 0x24,
	0x16, 0xa8, 0xfa, 0xd4, 0xa1, 0x2a, 0x31, 0x1a, 0x8a, 0x20, 0x4a, 0x43, 0xc3, 0x00, 0x0e, 0x02,
	0xcf, 0xd2, 0x10, 0x22, 0x89, 0x84, 0x4a, 0x73, 0x5d, 0x28, 0x53, 0x58, 0x37, 0x11, 0xeb, 0x21,
	0x04, 0xdb, 0xe6, 0x61, 0x6c, 0xca, 0x6a, 0x68, 0xc2, 0xb7, 0x47, 0x32, 0xa2, 0x5a, 0xda, 0xf1,
	0xb1, 0x0d, 0xd5, 0x64, 0x24, 0x15, 0xef, 0xc7, 0x82, 0xca, 0x66, 0xc7, 0x2f, 0xfb, 0xee, 0xa7,
	0xac, 0x0d, 0x3a, 0xdd, 0xe4, 0x9b, 0x5c, 0xf0, 0x28, 0xcc, 0x8b, 0x49, 0x1f, 0x8b, 0x68, 0xc7,
	0x5f, 0xc0, 0x61, 0x1e, 0xa4, 0xbd, 0xb0, 0xd0, 0x58, 0x3f, 0x3b, 0x7e, 0xd9, 0x07, 0x83, 0xd9,
	0x76, 0x90, 0xa7, 0xa9, 0xc6, 0x52, 0xda, 0xf1, 0x5b, 0x16, 0xf4, 0xd3, 0x14, 0x8d, 0x90, 0x8b,
	0x42, 0x09, 0x2c, 0x9f, 0x1d, 0x9f, 0x3a, 0xb0, 0x64, 0xac, 0x46, 0x6f, 0x1b, 0x9f, 0x40, 0xed,
	0x69, 0x03, 0x71, 0x6b, 0x79, 0x20, 0xde, 0xb9, 0x22, 0x71, 0x66, 0x81, 0xb8, 0xc5, 0xaa, 0xc8,
	0x29, 0x58, 0x3e, 0x3b, 0x3e, 0x75, 0xde, 0x61, 0x30, 0xfe, 0x61, 0x85, 0xd5, 0x28, 0xc5, 0x16,
	0x62, 0xd1, 0x63, 0x75, 0x25, 0xf2, 0x33, 0x19, 0x5a, 0x72, 0xb0, 0x5d, 0x08, 0x98, 0x89, 0xd0,
	0xa3, 0x34, 0x32, 0x51, 0x69, 0x7a, 0x70, 0x14, 0xf0, 0x4c, 0x96, 0x94, 0x41, 0xc1, 0xc9, 0x78,
	0x26, 0x2d, 0x63, 0xbc, 0xc5, 0x0a, 0xa1, 0x00, 0x7c, 0x27, 0x2b, 0x54, 0xf9, 0xd9, 0xe5, 0x15,
	0xaa, 0xfc, 0xec, 0x6d, 0x56, 0xf8, 0xfb, 0x35, 0xd6, 0xbe, 0x5c, 0xeb, 0x2f, 0x3b, 0x50, 0xa4,
	0x0a, 0x22, 0x31, 0xe0, 0x45, 0xac, 0x71, 0xb9, 0x8e, 0xdf, 0x90, 0xea, 0x19, 0x01, 0xe5, 0xed,
	0x56, 0x96, 0x2b, 0xc6, 0x5b, 0x0e, 0x5e, 0xe9, 0xa0, 0x85, 0x4b, 0x5d, 0xc6, 0x78, 0x28, 0xfd,
	0x6f, 0xb9, 0x9f, 0xde, 0xc4, 0x3b, 0xbf, 0x5b, 0x63, 0xb7, 0x2e, 0xdc, 0xa1, 0xde, 0x99, 0x6b,
	0xee, 0xb1, 0x3a, 0xdc, 0x85, 0x40, 0x40, 0x81, 0x54, 0x83, 0x6e, 0x37, 0x72, 0x3f, 0x63, 0xce,
	0x69, 0xc1, 0xa9, 0x86, 0xaf, 0x5e, 0x51, 0xc3, 0xd7, 0x4f, 0x0b, 0x8e, 0x25, 0xfc, 0x07, 0xac,
	0x69, 0x95, 0x61, 0x26, 0x62, 0xc7, 0x86, 0x91, 0x76, 0x23, 0xb8, 0x11, 0x80, 0x1c, 0x2a, 0x76,
	0xb5, 0xac, 0xca, 0xc3, 0x9b, 0x2e, 0x7c, 0x0f, 0x1a, 0x0a, 0x22, 0x01, 0xd4, 0x6d, 0x84, 0x13,
	0xa3, 0xb3, 0xd3, 0x82, 0xdb, 0x08, 0x7f, 0xc8, 0xa0, 0x17, 0x24, 0xc5, 0xa4, 0x2f, 0x72, 0xc3,
	0xed, 0xf0, 0x85, 0x43, 0x04, 0xb0, 0x4a, 0xd4, 0x3c, 0xd7, 0x81, 0x96, 0x13, 0x5b, 0xeb, 0x35,
	0x10, 0x39, 0x96, 0x13, 0x2c, 0x04, 0x45, 0x12, 0x91, 0x90, 0x88, 0xbe, 0x2e, 0x92, 0x08, 0x45,
	0x37, 0x71, 0xce, 0x6f, 0xea, 0x78, 0x16, 0xc2, 0xc5, 0xd2, 0xb8, 0x25, 0x9a, 0x2f, 0x4f, 0xd0,
	0xbc, 0x58, 0x9e, 0x90, 0xb7, 0x80, 0xa7, 0x33, 0x5b, 0x9e, 0xa0, 0xd0, 0xee, 0x93, 0xf2, 0xbf,
	0x09, 0x98, 0xdd, 0xe8, 0x1d, 0x56, 0x93, 0x2a, 0x50, 0x23, 0x3a, 0x3b, 0x1d, 0xbf, 0x2a, 0x55,
	0x6f, 0x84, 0x4f, 0x39, 0x6a, 0xa4, 0x17, 0x28, 0x60, 0xa4, 0xe7, 0xc6, 0xf1, 0x6c, 0xae, 0xd4,
	0xae, 0xf2, 0x0c, 0x9c, 0xfa, 0x3e, 0x6b, 0xf0, 0x2c, 0x53, 0x22, 0xcc, 0x85, 0xb6, 0xaf, 0x53,
	0x25, 0x40, 0x3c, 0xcd, 0x23, 0xaa, 0xab, 0x57, 0x7d, 0xea, 0x80, 0xb5, 0xb0, 0x11, 0xbc, 0xa6,
	0xa7, 0xa9, 0x55, 0xbf, 0x8e, 0xfd, 0xef, 0xe3, 0x99, 0x68, 0xf0, 0x1a, 0xad, 0x6c, 0x45, 0xcf,
	0x5f, 0xcf, 0x44, 0x13, 0x85, 0x36, 0xb6, 0xa2, 0x17, 0x0a, 0x2f, 0x10, 0x5c, 0x8d, 0x30, 0x4a,
	0xaa, 0x3e, 0xb6, 0xcb, 0x63, 0xba, 0x35, 0x77, 0x59, 0xd8, 0x66, 0x4e, 0x98, 0x4e, 0x26, 0x22,
	0xd1, 0x0a, 0xd3, 0xbd, 0xea, 0x97, 0x7d, 0xfb, 0xc8, 0xb3, 0x3e, 0x7b, 0xe4, 0x29, 0xdf, 0xbc,
	0x36, 0x68, 0xf1, 0xf4, 0xe6, 0xb5, 0xc7, 0x2a, 0x71, 0x3a, 0x4c, 0x31, 0x85, 0x97, 0xbe, 0xae,
	0x80, 0x14, 0x8f, 0xb3, 0x98, 0x2b, 0x25, 0x07, 0x53, 0x6f, 0xf3, 0xaa, 0xe8, 0xb4, 0x1a, 0x25,
	0x9b, 0xb9, 0x57, 0xd4, 0x6f, 0xc4, 0x66, 0x7b, 0xac, 0x22, 0x27, 0x43, 0xe5, 0xdd, 0xbe, 0x62,
	0x3e, 0x94, 0x2e, 0x79, 0x3a, 0xd9, 0x7a, 0xa3, 0xa7, 0x93, 0x4b, 0x9c, 0x79, 0xe7, 0x5a, 0xce,
	0xbc, 0xfb, 0x26, 0x9c, 0x79, 0x6f, 0x29, 0x67, 0x7a, 0x3f, 0x96, 0x33, 0xef, 0x2f, 0xe5, 0xcc,
	0xed, 0x1f, 0xcb, 0x99, 0x0f, 0xde, 0x9e, 0x33, 0xff, 0x52, 0x63, 0xf5, 0xa3, 0x3c, 0x8d, 0x8a,
	0x50, 0x2f, 0xbd, 0x19, 0xa5, 0x69, 0xa4, 0x82, 0xb9, 0x9b, 0x6c, 0x03, 0x11, 0xbc, 0x0e, 0x96,
	0x62, 0x4c, 0x5b, 0x3e, 0x27, 0xb6, 0x79, 0x4b, 0xe2, 0xfe, 0x74, 0xee, 0xf1, 0xb8, 0x89, 0xd8,
	0x37, 0x08, 0xc1, 0xb2, 0x06, 0x3c, 0xd4, 0x69, 0x3e, 0x35, 0xc9, 0x69, 0xbb, 0xe4, 0xb1, 0xc8,
	0x3e, 0xb8, 0x99, 0xf4, 0x64, 0x59, 0x1e, 0xd9, 0x43, 0xf7, 0x11, 0x6b, 0xf1, 0x0c, 0x3c, 0xc2,
	0x63, 0x20, 0x38, 0x93, 0xa6, 0x4d, 0x8b, 0x1d, 0x16, 0x13, 0xcc, 0x96, 0x4c, 0x84, 0x86, 0x18,
	0xb1, 0x0d, 0xf3, 0x46, 0xa9, 0xe2, 0x43, 0x11, 0x0c, 0xd2, 0x7c, 0x62, 0x1f, 0x51, 0x08, 0x7a,
	0x9e, 0xe6, 0x38, 0xa8, 0x48, 0xa4, 0x36, 0x74, 0x88, 0x6d, 0x28, 0x31, 0xd2, 0x0c, 0x6d, 0x60,
	0x1e, 0x90, 0xa9, 0x87, 0xf7, 0xe1, 0x8c, 0x87, 0xe3, 0x40, 0xa7, 0x9a, 0xc7, 0xe6, 0xda, 0xcb,
	0x10, 0x3a, 0x06, 0x04, 0x2c, 0x34, 0x27, 0xa7, 0x4b, 0x70, 0x63, 0x26, 0x7e, 0xc4, 0x5a, 0x52,
	0x05, 0x45, 0xd2, 0x2f, 0x92, 0x08, 0x2a, 0x5d, 0xaa, 0x80, 0x9b, 0x52, 0x9d, 0x58, 0x08, 0x1f,
	0xaf, 0x55, 0xa0, 0x74, 0x9a, 0x99, 0x3a, 0xb8, 0x26, 0x55, 0x4f, 0xa7, 0x19, 0x5e, 0x4b, 0xd1,
	0xba, 0x96, 0xdd, 0x36, 0xcc, 0xb5, 0x14, 0x40, 0xcb, 0x6f, 0x7b, 0xac, 0x02, 0x34, 0xb9, 0x2c,
	0xaf, 0xf1, 0x81, 0x0f, 0xa5, 0x65, 0x0e, 0x6e, 0x5e, 0x9b, 0x83, 0x3f, 0x63, 0xad, 0x8c, 0xe2,
	0x24, 0x50, 0xe3, 0x42, 0x99, 0xbc, 0xbe, 0x5d, 0x6a, 0x9b, 0x20, 0xea, 0x8d, 0x0b, 0xbf, 0x99,
	0x95, 0x6d, 0xe5, 0x3e, 0x61, 0xb7, 0xed, 0x38, 0xcb, 0x0d, 0x10, 0xf9, 0x54, 0x3a, 0x6f, 0x1a,
	0xd1, 0x53, 0x23, 0xe9, 0x46, 0xee, 0xcf, 0x59, 0xfb, 0xb2, 0x3e, 0xd6, 0xd4, 0xcb, 0x4e, 0xd6,
	0x8d, 0x4b, 0xc3, 0xe7, 0x53, 0xeb, 0xce, 0xd2, 0xd4, 0xba, 0xfb, 0xaf, 0x52, 0xeb, 0x8d, 0x13,
	0xe8, 0x6f, 0x15, 0xc6, 0x66, 0x7b, 0x5f, 0xc8, 0xa1, 0xfb, 0xcc, 0x51, 0xe3, 0x62, 0xfe, 0xe2,
	0x5d, 0x57, 0xe3, 0x02, 0x13, 0xe4, 0x31, 0xbb, 0xc5, 0xb5, 0xce, 0x65, 0x10, 0x4b, 0xa5, 0x83,
	0x3e, 0x1d, 0x5e, 0x2d, 0xbf, 0x89, 0xe0, 0x81, 0x54, 0xfa, 0x1b, 0x3d, 0xe3, 0xeb, 0xca, 0x3c,
	0x5f, 0xc3, 0xc9, 0x2d, 0xe2, 0x38, 0xc8, 0x72, 0x28, 0x88, 0xab, 0x14, 0x57, 0x80, 0x1c, 0x01,
	0x00, 0x71, 0x35, 0xe1, 0xf9, 0x58, 0x68, 0xa3, 0x50, 0x43, 0x85, 0x26, 0x61, 0xa4, 0x02, 0x33,
	0xf0, 0x58, 0x18, 0x85, 0xba, 0x99, 0x81, 0xc7, 0x82, 0xc4, 0x7b, 0x6c, 0x7d, 0x26, 0x0e, 0x44,
	0x9e, 0x99, 0x33, 0xad, 0x55, 0xaa, 0x74, 0x72, 0x3c, 0x4c, 0x94, 0x4e, 0xc3, 0xb1, 0x39, 0xd5,
	0xa8, 0x63, 0x6a, 0xac, 0x70, 0x24, 0xc2, 0xb1, 0xa0, 0xbf, 0x5c, 0xb0, 0xc6, 0x7a, 0x4a, 0x00,
	0xdd, 0x11, 0x75, 0x38, 0xb2, 0x65, 0x49, 0x79, 0x47, 0xd4, 0xe1, 0xc8, 0x14, 0x26, 0x1f, 0xb1,
	0x75, 0x74, 0x2c, 0x90, 0x77, 0x00, 0x56, 0x36, 0x55, 0xee, 0xad, 0x12, 0x7d, 0xc6, 0xb5, 0x00,
	0x35, 0x31, 0x18, 0x88, 0x50, 0xcb, 0x33, 0x41, 0x6a, 0xf4, 0xa2, 0x74, 0xab, 0x44, 0x51, 0xed,
	0x63, 0x56, 0xc5, 0xa4, 0xc0, 0x04, 0x9a, 0xf7, 0xbd, 0xf1, 0x9a, 0x4f, 0xe2, 0x32, 0x0d, 0x36,
	0xae, 0x4d, 0x03, 0x48, 0x69, 0x13, 0x9e, 0x65, 0xcd, 0xdb, 0x30, 0x48, 0x17, 0x29, 0x33, 0x4c,
	0x95, 0x35, 0xfc, 0x26, 0xd9, 0x15, 0x10, 0xb2, 0xeb, 0x4d, 0x02, 0xec, 0x4f, 0x6b, 0xac, 0xf6,
	0x32, 0x8f, 0x44, 0xbe, 0x78, 0xd3, 0x78, 0xc4, 0x5a, 0x29, 0x48, 0xac, 0x2d, 0x4d, 0x69, 0x84,
	0x98, 0xb1, 0x25, 0xdc, 0x72, 0x45, 0x2e, 0x89, 0x25, 0x41, 0xc7, 0x3c, 0x5f, 0x11, 0x68, 0x94,
	0xbe, 0x62, 0x34, 0x26, 0x90, 0x5a, 0x4c, 0xec, 0x23, 0x8f, 0x5b, 0x5a, 0x00, 0xbf, 0xde, 0xd5,
	0x62, 0xe2, 0xb3, 0xd4, 0x36, 0xd5, 0xff, 0x2e, 0x22, 0x57, 0xbb, 0xec, 0xaf, 0xab, 0xac, 0x51,
	0x1a, 0x6d, 0xc1, 0x6b, 0xbb, 0xf6, 0x60, 0x04, 0x62, 0x90, 0x91, 0xf1, 0x1a, 0x9d, 0xa5, 0xbd,
	0x71, 0xd1, 0x45, 0xd2, 0x30, 0xfe, 0xb0, 0x17, 0x91, 0x3a, 0x19, 0x3e, 0x72, 0xff, 0x8f, 0xd5,
	0xb0, 0xa9, 0xcc, 0x35, 0x71, 0xe3, 0xa2, 0x97, 0x94, 0x6f, 0xc4, 0xf8, 0x1f, 0x6b, 0x22, 0xf5,
	0x45, 0x8e, 0x00, 0xa4, 0xcc, 0xf0, 0x8c, 0x4f, 0x83, 0x39, 0x15, 0x62, 0x89, 0x56, 0xc6, 0xa7,
	0x27, 0xa5, 0xd6, 0x36, 0x5e, 0x6f, 0x12, 0x0d, 0xf6, 0x27, 0x92, 0x28, 0xfb, 0x14, 0x59, 0x49,
	0x14, 0x94, 0x0a, 0x96, 0x22, 0x44, 0x12, 0xbd, 0xb2, 0x4a, 0x3b, 0xac, 0x89, 0x87, 0x9f, 0xf9,
	0x06, 0x11, 0x05, 0x43, 0xe8, 0xc6, 0x19, 0xf1, 0x69, 0xcc, 0x1c, 0xfb, 0x37, 0x81, 0xeb, 0xb0,
	0xca, 0xbe, 0xdf, 0xd9, 0x6f, 0xbf, 0xe7, 0xd6, 0xd9, 0xda, 0x91, 0xff, 0xac, 0xbd, 0x02, 0x8d,
	0x57, 0x27, 0xfb, 0xed, 0x55, 0x90, 0x9d, 0xf4, 0x3a, 0x7e, 0x7b, 0x0d, 0x5a, 0xcf, 0xbb, 0x07,
	0x9d, 0x76, 0x05, 0x84, 0xcf, 0x3a, 0x47, 0xed, 0x2a, 0x40, 0x2f, 0x3a, 0x87, 0x27, 0xed, 0x9a,
	0xdb, 0x60, 0xd5, 0x83, 0x97, 0xdf, 0x76, 0x0f, 0xdb, 0x75, 0x90, 0xf6, 0x3a, 0xbf, 0x6c, 0x3b,
	0x80, 0xbd, 0x3c, 0xfe, 0xae, 0xe3, 0xb7, 0xc3, 0x4f, 0x3f, 0x63, 0x0d, 0xb8, 0xf2, 0x27, 0xf6,
	0x73, 0x87, 0xfb, 0x2f, 0x3a, 0xed, 0xf7, 0x40, 0xe3, 0xe8, 0xbb, 0x97, 0x87, 0x9d, 0xf6, 0x0a,
	0x34, 0x3b, 0x2f, 0xf6, 0xbb, 0x07, 0xed, 0xd5, 0xa3, 0xf7, 0xfa, 0x35, 0xfc, 0xc3, 0xfd, 0xab,
	0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0xab, 0x63, 0xe6, 0xa6, 0xb9, 0x1f, 0x00, 0x00,
}
