// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/dbmodel/model.proto

package dbmodel

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PageReq struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Row                  int32    `protobuf:"varint,2,opt,name=row,proto3" json:"row,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageReq) Reset()         { *m = PageReq{} }
func (m *PageReq) String() string { return proto.CompactTextString(m) }
func (*PageReq) ProtoMessage()    {}
func (*PageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3634f3d6f6246585, []int{0}
}

func (m *PageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageReq.Unmarshal(m, b)
}
func (m *PageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageReq.Marshal(b, m, deterministic)
}
func (m *PageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageReq.Merge(m, src)
}
func (m *PageReq) XXX_Size() int {
	return xxx_messageInfo_PageReq.Size(m)
}
func (m *PageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PageReq.DiscardUnknown(m)
}

var xxx_messageInfo_PageReq proto.InternalMessageInfo

func (m *PageReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PageReq) GetRow() int32 {
	if m != nil {
		return m.Row
	}
	return 0
}

type PageResp struct {
	Total                int64      `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data                 []*any.Any `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PageResp) Reset()         { *m = PageResp{} }
func (m *PageResp) String() string { return proto.CompactTextString(m) }
func (*PageResp) ProtoMessage()    {}
func (*PageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3634f3d6f6246585, []int{1}
}

func (m *PageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageResp.Unmarshal(m, b)
}
func (m *PageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageResp.Marshal(b, m, deterministic)
}
func (m *PageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageResp.Merge(m, src)
}
func (m *PageResp) XXX_Size() int {
	return xxx_messageInfo_PageResp.Size(m)
}
func (m *PageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PageResp.DiscardUnknown(m)
}

var xxx_messageInfo_PageResp proto.InternalMessageInfo

func (m *PageResp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PageResp) GetData() []*any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

//
//message DelReq{
//int64 id=1;
//}
//message EditResp{
//int64 id=1;
//}
type Id struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Id) Reset()         { *m = Id{} }
func (m *Id) String() string { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()    {}
func (*Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_3634f3d6f6246585, []int{2}
}

func (m *Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Id.Unmarshal(m, b)
}
func (m *Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Id.Marshal(b, m, deterministic)
}
func (m *Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Id.Merge(m, src)
}
func (m *Id) XXX_Size() int {
	return xxx_messageInfo_Id.Size(m)
}
func (m *Id) XXX_DiscardUnknown() {
	xxx_messageInfo_Id.DiscardUnknown(m)
}

var xxx_messageInfo_Id proto.InternalMessageInfo

func (m *Id) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Tree struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Children             []*Tree  `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tree) Reset()         { *m = Tree{} }
func (m *Tree) String() string { return proto.CompactTextString(m) }
func (*Tree) ProtoMessage()    {}
func (*Tree) Descriptor() ([]byte, []int) {
	return fileDescriptor_3634f3d6f6246585, []int{3}
}

func (m *Tree) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tree.Unmarshal(m, b)
}
func (m *Tree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tree.Marshal(b, m, deterministic)
}
func (m *Tree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tree.Merge(m, src)
}
func (m *Tree) XXX_Size() int {
	return xxx_messageInfo_Tree.Size(m)
}
func (m *Tree) XXX_DiscardUnknown() {
	xxx_messageInfo_Tree.DiscardUnknown(m)
}

var xxx_messageInfo_Tree proto.InternalMessageInfo

func (m *Tree) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Tree) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Tree) GetChildren() []*Tree {
	if m != nil {
		return m.Children
	}
	return nil
}

type TreeResp struct {
	Data                 []*Tree  `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TreeResp) Reset()         { *m = TreeResp{} }
func (m *TreeResp) String() string { return proto.CompactTextString(m) }
func (*TreeResp) ProtoMessage()    {}
func (*TreeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3634f3d6f6246585, []int{4}
}

func (m *TreeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TreeResp.Unmarshal(m, b)
}
func (m *TreeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TreeResp.Marshal(b, m, deterministic)
}
func (m *TreeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TreeResp.Merge(m, src)
}
func (m *TreeResp) XXX_Size() int {
	return xxx_messageInfo_TreeResp.Size(m)
}
func (m *TreeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TreeResp.DiscardUnknown(m)
}

var xxx_messageInfo_TreeResp proto.InternalMessageInfo

func (m *TreeResp) GetData() []*Tree {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*PageReq)(nil), "dbmodel.PageReq")
	proto.RegisterType((*PageResp)(nil), "dbmodel.PageResp")
	proto.RegisterType((*Id)(nil), "dbmodel.Id")
	proto.RegisterType((*Tree)(nil), "dbmodel.Tree")
	proto.RegisterType((*TreeResp)(nil), "dbmodel.TreeResp")
}

func init() { proto.RegisterFile("proto/dbmodel/model.proto", fileDescriptor_3634f3d6f6246585) }

var fileDescriptor_3634f3d6f6246585 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x4f, 0x4d, 0x4f, 0xc4, 0x20,
	0x10, 0x4d, 0x69, 0xd7, 0xed, 0x8e, 0xd1, 0x18, 0xd2, 0x43, 0xd7, 0xd3, 0xca, 0xa9, 0x1e, 0x84,
	0x44, 0x7f, 0x81, 0x47, 0x3d, 0x19, 0xe2, 0xc5, 0x23, 0x95, 0xb1, 0x36, 0x62, 0xa9, 0x15, 0x63,
	0xfa, 0xef, 0x0d, 0x03, 0x7a, 0xf2, 0x42, 0x66, 0xde, 0x9b, 0xf7, 0x01, 0xec, 0xe7, 0xc5, 0x07,
	0xaf, 0x6c, 0xff, 0xee, 0x2d, 0x3a, 0x45, 0xaf, 0x24, 0x8c, 0x6f, 0x33, 0x78, 0xbe, 0x1f, 0xbc,
	0x1f, 0x1c, 0x2a, 0x82, 0xfb, 0xaf, 0x17, 0x65, 0xa6, 0x35, 0xdd, 0x08, 0x05, 0xdb, 0x07, 0x33,
	0xa0, 0xc6, 0x0f, 0xce, 0xa1, 0x9a, 0xcd, 0x80, 0x6d, 0x71, 0x28, 0xba, 0x8d, 0xa6, 0x99, 0x9f,
	0x41, 0xb9, 0xf8, 0xef, 0x96, 0x11, 0x14, 0x47, 0x71, 0x0f, 0x75, 0x12, 0x7c, 0xce, 0xbc, 0x81,
	0x4d, 0xf0, 0xc1, 0x38, 0x92, 0x94, 0x3a, 0x2d, 0xbc, 0x83, 0xca, 0x9a, 0x60, 0x5a, 0x76, 0x28,
	0xbb, 0xe3, 0xeb, 0x46, 0xa6, 0x70, 0xf9, 0x1b, 0x2e, 0x6f, 0xa7, 0x55, 0xd3, 0x85, 0x68, 0x80,
	0xdd, 0x59, 0x7e, 0x0a, 0x6c, 0xb4, 0x64, 0xb1, 0xd3, 0x6c, 0xb4, 0xe2, 0x09, 0xaa, 0xc7, 0x05,
	0x91, 0xdc, 0xc7, 0xe0, 0x30, 0x53, 0x69, 0x89, 0x8d, 0xde, 0x70, 0xa5, 0x46, 0x3b, 0x1d, 0x47,
	0x7e, 0x09, 0xf5, 0xf3, 0xeb, 0xe8, 0xec, 0x82, 0x53, 0x5b, 0x52, 0xe6, 0x89, 0xcc, 0x3f, 0x97,
	0xd1, 0x48, 0xff, 0xd1, 0xe2, 0x0a, 0x6a, 0x42, 0x62, 0xf9, 0x8b, 0x5c, 0xb3, 0xf8, 0x4f, 0x42,
	0x54, 0x7f, 0x44, 0x9d, 0x6f, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xcf, 0xa7, 0x58, 0x64,
	0x01, 0x00, 0x00,
}
